### ISSUE TITLE
[Crash] Thermos 23 - java.lang.NullPointerException: Ticking entity

### ISSUE THREAD

**Issue by Esctogrillo** [TCPR/Thermos#100]
- Crash report: http://pastebin.com/GuYU1Q47
 - Starts to happen with Thermos 23.
 - I don't know how to reproduce.

Edit
 - Maybe this happen on Infernal Mobs drop the player tinker's contruct sword?

Edit²
 - I found this on log: http://pastebin.com/dbNTaUgM
 - A player died and the server crashed.

**Comment by iKaneki-Ken** [comment]
Yay, more crashes being caused by Infernal Mobs.

**Comment by Esctogrillo** [comment]
Yeah =/

**Comment by iKaneki-Ken** [comment]
Alright, the crash is being caused by the mobs special power "Vengeance".

**Comment by Robotia** [comment]
Looks to be that the mod is trying to custom drop it's own items. Will investigate.

**Comment by Robotia** [comment]
Its*

**Comment by Esctogrillo** [comment]
I deactivated the Vengeance type mob on Infernal Mobs config. Let's try.

**Comment by Robotia** [comment]
Let me know what happens.

**Comment by Esctogrillo** [comment]
Another crash now: http://pastebin.com/h8AvsRm2
TheTitanic10 (Moderator) said that happens when him was killed by the Pigzombie.
Look, I removed the Infernal Mobs. If do you want to fix, ok, I will put it back. If not, ok too.

**Comment by Esctogrillo** [comment]
Wait!
Look this console error on player death: http://pastebin.com/vS2tXnhp
(Server does not crash)
(Without Infernal Mobs)

**Comment by iKaneki-Ken** [comment]
Try turning off the explosion part of Nether Ores.

**Comment by Robotia** [comment]
It is related to the DamageSource for death, think it's because of the indirect damage fixes.

**Comment by Robotia** [comment]
Turns out it is because Tinker's Construct stores a reference to the old player object, which gets ruined when the player is cloned. Might need to transfer all properties back to the old player object and use that instead...

**Comment by iKaneki-Ken** [comment]
@Robotia But I haven't experienced this issue before at all and I'm using all the commits with Tinkers' Construct.

**Comment by Robotia** [comment]
@iKaneki-Ken Tinker's Construct stores references to player objects as: ` public WeakReference<EntityPlayer> parent;`. A WeakReference will no longer exist when the old player, before the respawn occurs, is removed. This results in a TC-caused crash, which shouldn't exist. Thermos should store the previous player so that the WeakReference is maintained.

**Comment by Robotia** [comment]
Wait...I think I just found a bug in the ReverseCloner from Prototik...going to investigate this now.

**Comment by Robotia** [comment]
@Esctogrillo Have you tried B24?

**Comment by Esctogrillo** [comment]
I'ts all working fine now, thanks @Robotia :)
