### ISSUE TITLE
MobiusCore and Opis need to be fixed for Thermos

### ISSUE THREAD

**Issue by enterprise12nx** [TCPR/Thermos#101]
Using B23 with new libraries, server crashes on startup(BisectHosting, saw you said server hosts may not like this build)
[crash-2016-02-13_16.16.39-server.txt](https://github.com/TCPR/Thermos/files/129414/crash-2016-02-13_16.16.39-server.txt)

**Comment by Robotia** [comment]
@enterprise12nx MobiusCore and Opis are broken by the latest build, will fix after I see what's up with it. :+1:

**Comment by iKaneki-Ken** [comment]
Enterprise, with all due respect, it was stated very clearly in the changelogs that opis is broken, a issue did not need to be opened for this as it is known that Opis is broken.

>Known Issues:
>
>Opis is broken
>3rd Party Hosters may be mad b/c of the core locking. (to confirm)

**Comment by Robotia** [comment]
@iKaneki-Ken No he is having issues with MobiusCore, I just renamed the issue, I did not post that that was broken, but it is now :confused: . Have to add that to the release notes.

**Comment by iKaneki-Ken** [comment]
Gotcha. Well that means he's 50% in the clear then.

**Comment by enterprise12nx** [comment]
I didnt realize it was crashing because of that, it had started up with it added before, just using it crashed it(using /opis) 
I forgot to remove it, and thought it was crashing for this reason

"3rd Party Hosters may be mad b/c of the core locking. (to confirm)"
I use a server host soo figured it was that, not opis
@iKaneki-Ken
@Robotia

**Comment by Robotia** [comment]
@enterprise12nx It shouldn't be a problem. A poorly-run 3rd party hoster would put all the Minecraft servers on the same operating system, which is a serious security vulnerability. Normally, good hosts will use either a virtual machine or a chroot, to prevent one server from affecting other servers. Thus, it should not be a problem for most people.

**Comment by Robotia** [comment]
@enterprise12nx Actually...can you try the regular mobius core?

**Comment by Cracks777** [comment]
Just to see if it works?

**Comment by Robotia** [comment]
Yes, I have a suspicion that it might.

**Comment by Cracks777** [comment]
nope.

**Comment by Cracks777** [comment]
mobius core isnt needed if you use the mapless version anyway

**Comment by Cracks777** [comment]
at least on build 22

**Comment by Robotia** [comment]
Hmm, I might need to revert some stuff on B23 for it to work again.

**Comment by Cracks777** [comment]
ok, well i can test if you revert some of the changes

**Comment by Cracks777** [comment]
but as of build 22 opis mapless works without mobius core and no crashes.

**Comment by Cracks777** [comment]
Description: Exception in server tick loop

java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    net/minecraft/world/World.func_72939_s()V @541: aload_2
  Reason:
    Type integer (current frame, locals[2]) is not assignable to reference type
  Current Frame:
    bci: @541
    flags: { }
    locals: { 'net/minecraft/world/World', 'net/openhft/affinity/AffinityLock', integer, 'net/minecraft/entity/Entity', top, top, top, top, integer }
    stack: { 'mcp/mobius/mobiuscore/profiler/ProfilerSection' }
  Bytecode:
    0x0000000: b806 8b4c 2ab4 01e8 1306 8cb6 0315 2ab4
    0x0000010: 01e8 1306 8eb6 0315 2a03 b506 902a 03b5
    0x0000020: 0692 033d 1c2a b401 17b9 0380 0100 a200
    0x0000030: 9a2a b401 171c b903 8402 00c0 04bb 4e2d
    0x0000040: c700 06a7 007f 2d59 b406 9504 60b5 0695
    0x0000050: 2db6 0698 a700 593a 0419 0413 069a b800
    0x0000060: cf3a 0519 0513 069c b600 d53a 062d c700
    0x0000070: 1119 0613 069e 1306 a0b6 02c0 a700 092d
    0x0000080: 1906 b606 a4b2 06a9 9900 1bb8 06af b206
    0x0000090: b519 05b6 06b9 b906 bf03 002a 2db6 06c1
    0x00000a0: a700 0dbb 00e3 5919 05b7 00e6 bf2d b405
    0x00000b0: 5399 0011 2ab4 0117 1c84 02ff b905 db02
    0x00000c0: 0057 8402 01a7 ff5f 2ab4 01e8 1306 c2b6
    0x00000d0: 06c5 2ab4 010b 2ab4 010d b906 c802 0057
    0x00000e0: 033d 1c2a b401 0db9 0380 0100 a200 412a
    0x00000f0: b401 0d1c b903 8402 00c0 04bb 4e2d b405
    0x0000100: ca36 042d b405 cd36 072d b405 d099 001a
    0x0000110: 2a15 0415 07b6 02d7 9900 0f2a 1504 1507
    0x0000120: b602 ad2d b605 d384 0201 a7ff b803 3d1c
    0x0000130: 2ab4 010d b903 8001 00a2 001a 2a2a b401
    0x0000140: 0d1c b903 8402 00c0 04bb b605 c584 0201
    0x0000150: a7ff df2a b401 0db9 06c9 0100 2ab4 01e8
    0x0000160: 1306 cbb6 06c5 2ab8 06d0 2ab4 0236 b406
    0x0000170: d4b6 06d9 0336 082a b405 d99c 0008 2a03
    0x0000180: b505 d92a b406 dbb6 06e0 1508 2ab4 010b
    0x0000190: b903 8001 00a2 0189 1508 100a 7099 000d
    0x00001a0: 2ab4 06db b606 e399 0177 2a2a b405 d92a
    0x00001b0: b401 0bb9 0380 0100 a200 0a2a b405 d9a7
    0x00001c0: 0004 03b5 05d9 2ab4 010b 2ab4 05d9 b903
    0x00001d0: 8402 00c0 04bb 4e2d b405 c1c6 0028 2db4
    0x00001e0: 05c1 b405 539a 0011 2db4 05c1 b405 bb2d
    0x00001f0: a600 06a7 011b 2db4 05c1 01b5 05bb 2d01
    0x0000200: b505 c12a b401 e813 06e5 b603 152d b405
    0x0000210: 539a 0069 b206 e8b6 06d9 b206 ee2c b606
    0x0000220: f22a 2db6 06f5 b206 ee2c b606 f8b2 06e8
    0x0000230: b606 fba7 0047 3a09 1909 1306 9ab8 00cf
    0x0000240: 3a05 1905 1306 9cb6 00d5 3a06 2d19 06b6
    0x0000250: 06a4 b206 a999 001b b806 afb2 06b5 1905
    0x0000260: b606 b9b9 06bf 0300 2a2d b606 c1a7 000d
    0x0000270: bb00 e359 1905 b700 e6bf 2ab4 01e8 b603
    0x0000280: 1b2a b401 e813 06c2 b603 152d b405 5399
    0x0000290: 0078 2db4 05ca 3604 2db4 05cd 3607 2db4
    0x00002a0: 05d0 9900 1a2a 1504 1507 b602 d799 000f
    0x00002b0: 2a15 0415 07b6 02ad 2db6 05d3 2ab4 05d9
    0x00002c0: 2ab4 010b b903 8001 00a2 001b 2ab4 010b
    0x00002d0: 2a59 b405 d95a 0464 b505 d9b9 05db 0200
    0x00002e0: 57a7 0021 b807 00bb 0702 59b7 0703 1307
    0x00002f0: 05b6 0709 2db6 070c b607 0f03 bd00 04b6
    0x0000300: 0713 2a2d b605 c52a b401 e8b6 031b 2a59
    0x0000310: b405 d904 60b5 05d9 8408 01a7 fe6f 2ab4
    0x0000320: 0236 b406 d4b6 06fb 2ab4 01e8 1307 15b6
    0x0000330: 06c5 2ab4 0236 b407 18b6 06d9 2a04 b507
    0x0000340: 1a2a b401 13b9 071d 0100 9a00 ee2a b401
    0x0000350: 13b9 057f 0100 3a09 1909 b902 9801 0099
    0x0000360: 0026 1909 b902 9c01 003a 0a19 0ac0 071f
    0x0000370: 3a0b 190b 04b6 0722 a700 053a 0c19 0bb6
    0x0000380: 0725 a7ff d6bb 0108 592a b401 0fb9 0380
    0x0000390: 0100 b707 273a 092a b401 0fb9 057f 0100
    0x00003a0: 3a0a 190a b902 9801 0099 004d 190a b902
    0x00003b0: 9c01 003a 0b03 360c 190b c007 1fb6 072a
    0x00003c0: 9a00 0704 a700 0403 360c a700 1a3a 0d2a
    0x00003d0: b401 1319 0bb9 072d 0200 360c a700 083a
    0x00003e0: 0e03 360c 150c 9900 0d19 0919 0bb9 050b
    0x00003f0: 0200 57a7 ffaf 2a19 09b5 010f 2ab4 0113
    0x0000400: b905 7f01 003a 0a19 0ab9 0298 0100 9900
    0x0000410: 2119 0ab9 029c 0100 3a0b 190b c007 1f3a
    0x0000420: 0c19 0c03 b607 22a7 0005 3a0d a7ff db2a
    0x0000430: b401 13b9 06c9 0100 0336 092a b407 2fb6
    0x0000440: 06e0 1509 2ab4 010f b903 8001 00a2 01a5
    0x0000450: 1509 100a 7099 000d 2ab4 072f b606 e399
    0x0000460: 0193 2a2a b407 312a b401 0fb9 0380 0100
    0x0000470: a200 0a2a b407 31a7 0004 03b5 0731 2ab4
    0x0000480: 010f 2ab4 0731 b903 8402 00c0 071f 3a0a
    0x0000490: 190a c700 2b2a b601 bbb6 0734 1307 36b6
    0x00004a0: 073b 8409 ff2a b401 0f2a 59b4 0731 5a04
    0x00004b0: 64b5 0731 b905 db02 0057 a701 2819 0ab6
    0x00004c0: 073e 9900 6684 09ff 2ab4 010f 2a59 b407
    0x00004d0: 315a 0464 b507 31b9 05db 0200 572a 190a
    0x00004e0: b407 4107 7a19 0ab4 0744 077a b602 d799
    0x00004f0: 00f3 2a19 0ab4 0741 077a 190a b407 4407
    0x0000500: 7ab6 02ad 3a0b 190b c600 1d19 0b19 0ab4
    0x0000510: 0741 100f 7e19 0ab4 0747 190a b407 4410
    0x0000520: 0f7e b607 4aa7 00bd 190a b607 4d99 00b5
    0x0000530: 190a 2ab8 0751 9900 ac2a 190a b407 4119
    0x0000540: 0ab4 0747 190a b407 44b6 00b9 9900 9619
    0x0000550: 0ab4 0754 b606 d92a 59b4 0692 0460 b506
    0x0000560: 92b2 0757 1909 b606 f219 0ab6 075a b207
    0x0000570: 5719 09b6 06f8 190a b407 54b6 06fb a700
    0x0000580: 643a 0b19 0ab4 0754 b606 fb19 0b13 075c
    0x0000590: b800 cf3a 0519 0513 075e b600 d53a 0619
    0x00005a0: 0a19 06b6 0761 b207 6499 002f b806 afb2
    0x00005b0: 06b5 1905 b606 b9b9 06bf 0300 190a b607
    0x00005c0: 672a 190a b407 4119 0ab4 0747 190a b407
    0x00005d0: 44b6 0769 57a7 000d bb00 e359 1905 b700
    0x00005e0: e6bf 2a59 b407 3104 60b5 0731 8409 01a7
    0x00005f0: fe53 2ab4 0236 b407 18b6 06fb 2ab4 0236
    0x0000600: b407 6cb6 06d9 2a03 b507 1a2a 03b5 071a
    0x0000610: 2ab4 01e8 1307 6eb6 06c5 2ab4 0111 b907
    0x0000620: 1d01 009a 00a0 0336 0a15 0a2a b401 11b9
    0x0000630: 0380 0100 a200 862a b401 1115 0ab9 0384
    0x0000640: 0200 c007 1f3a 0b19 0bb6 073e 9a00 202a
    0x0000650: b401 0f19 0bb9 072d 0200 9a00 5a2a b401
    0x0000660: 0f19 0bb9 050b 0200 57a7 004b 2a19 0bb4
    0x0000670: 0741 077a 190b b407 4407 7ab6 02d7 9900
    0x0000680: 362a 190b b407 4107 7a19 0bb4 0744 077a
    0x0000690: b602 ad3a 0c19 0cc6 001d 190c 190b b407
    0x00006a0: 4110 0f7e 190b b407 4719 0bb4 0744 100f
    0x00006b0: 7eb6 074a 840a 01a7 ff72 2ab4 0111 b906
    0x00006c0: c901 002a b402 36b4 076c b606 fb2a b401
    0x00006d0: e8b6 031b 2ab4 01e8 b603 1b2b b607 71b1
    0x00006e0:                                        
  Exception Handler Table:
    bci [70, 84] => handler: 87
    bci [532, 563] => handler: 566
    bci [882, 888] => handler: 891
    bci [952, 970] => handler: 973
    bci [975, 988] => handler: 991
    bci [1057, 1063] => handler: 1066
    bci [1359, 1406] => handler: 1409
  Stackmap Table:
    append_frame(@36,Object[#1671],Integer)
    append_frame(@70,Object[#1211])
    same_locals_1_stack_item_frame(@87,Object[#181])
    append_frame(@127,Object[#181],Object[#203],Object[#221])
    same_frame(@133)
    same_frame(@163)
    chop_frame(@173,3)
    same_frame(@194)
    chop_frame(@200,1)
    same_frame(@226)
    full_frame(@295,{Object[#2],Object[#1671],Integer,Object[#1211],Integer,Top,Top,Integer},{})
    full_frame(@301,{Object[#2],Object[#1671],Integer},{})
    same_frame(@303)
    same_frame(@339)
    full_frame(@387,{Object[#2],Object[#1671],Integer,Top,Top,Top,Top,Top,Integer},{})
    same_frame(@394)
    same_frame(@426)
    same_locals_1_stack_item_frame(@450,Object[#2])
    full_frame(@451,{Object[#2],Object[#1671],Integer,Top,Top,Top,Top,Top,Integer},{Object[#2],Integer})
    full_frame(@502,{Object[#2],Object[#1671],Integer,Object[#1211],Top,Top,Top,Top,Integer},{})
    same_frame(@515)
    same_locals_1_stack_item_frame(@566,Object[#181])
    full_frame(@624,{Object[#2],Object[#1671],Integer,Object[#1211],Top,Object[#203],Object[#221],Top,Integer,Object[#181]},{})
    full_frame(@634,{Object[#2],Object[#1671],Integer,Object[#1211],Top,Top,Top,Top,Integer},{})
    full_frame(@700,{Object[#2],Object[#1671],Integer,Object[#1211],Integer,Top,Top,Integer,Integer},{})
    same_frame(@740)
    same_frame(@770)
    full_frame(@775,{Object[#2],Object[#1671],Integer,Object[#1211],Top,Top,Top,Top,Integer},{})
    same_frame(@782)
    full_frame(@798,{Object[#2],Object[#1671],Integer,Top,Top,Top,Top,Top,Integer},{})
    append_frame(@856,Object[#661])
    full_frame(@891,{Object[#2],Object[#1671],Integer,Top,Top,Top,Top,Top,Integer,Object[#661],Object[#4],Object[#1823]},{Object[#1669]})
    same_frame(@893)
    chop_frame(@901,2)
    full_frame(@930,{Object[#2],Object[#1671],Integer,Top,Top,Top,Top,Top,Integer,Object[#264],Object[#661]},{})
    append_frame(@967,Object[#4],Integer)
    same_locals_1_stack_item_frame(@968,Integer)
    same_locals_1_stack_item_frame(@973,Object[#1669])
    full_frame(@991,{Object[#2],Object[#1671],Integer,Top,Top,Top,Top,Top,Integer,Object[#264],Object[#661],Object[#4],Integer,Object[#1669]},{Object[#1669]})
    chop_frame(@996,1)
    same_frame(@1011)
    chop_frame(@1014,2)
    same_frame(@1031)
    full_frame(@1066,{Object[#2],Object[#1671],Integer,Top,Top,Top,Top,Top,Integer,Object[#264],Object[#661],Object[#4],Object[#1823]},{Object[#1669]})
    same_frame(@1068)
    chop_frame(@1071,2)
    chop_frame(@1080,2)
    append_frame(@1090,Integer)
    same_frame(@1122)
    same_locals_1_stack_item_frame(@1146,Object[#2])
    full_frame(@1147,{Object[#2],Object[#1671],Integer,Top,Top,Top,Top,Top,Integer,Integer},{Object[#2],Integer})
    append_frame(@1213,Object[#1823])
    append_frame(@1317,Object[#195])
    chop_frame(@1320,1)
    same_locals_1_stack_item_extended(@1409,Object[#181])
    full_frame(@1496,{Object[#2],Object[#1671],Integer,Top,Top,Object[#203],Object[#221],Top,Integer,Integer,Object[#1823],Object[#181]},{})
    full_frame(@1506,{Object[#2],Object[#1671],Integer,Top,Top,Top,Top,Top,Integer,Integer,Object[#1823]},{})
    chop_frame(@1522,1)
    append_frame(@1577,Integer)
    append_frame(@1644,Object[#1823])
    same_frame_extended(@1716)
    chop_frame(@1722,1)
    chop_frame(@1731,1)

	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:368)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:632)
	at java.lang.Thread.run(Unknown Source)

**Comment by Cracks777** [comment]
Finaly got a crash report from trying opis.

**Comment by Robotia** [comment]
Just use Pastebin.com in the future

**Comment by tyler2k15** [comment]
Opis works Build 35+

https://github.com/TCPR/Fixes/raw/master/MobiusCore/MobiusCore-1.2.5-KC.jar
http://minecraft.curseforge.com/projects/opis/files/2232520/download

@Robotia This can be closed.

**Comment by MineProjectZ** [comment]
i have this issuse also with the version that you posted

**Comment by Razorskills** [comment]
Who is "you"? Just specify the version number you are using so that we actually know for sure. Also If you are using an super old version. Go here and update: https://github.com/CyberdyneCC/Thermos/releases
