### ISSUE TITLE
Cannot run gradlew command in my Thermos Workspace

### ISSUE THREAD

**Issue by vrackfall** [TCPR/Thermos#102]
I tried to download and build Thermos but the gradlew doesn't work : 
FAILURE: Build failed with an exception.

* Where:
Build file 'F:\Minecraft\Modding\Thermos-Workspace\Thermos\build.gradle' line: 82

* What went wrong:
A problem occurred evaluating root project 'Thermos'.
> Cannot run program "git": CreateProcess error=2, The specified file is not found

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

---------------------------------------

How can I fix that ?
Thanks

**Comment by TerdyTheTerd** [comment]
When you type "git" in you console does is spit out options? Or does it say its not valid. The former means its installed with correct paths, the latter means its not installed correctly.

**Comment by vrackfall** [comment]
Do you mean I had to run the gradlew.bat file from git to it's work ? Or I have to put git in my workspace ?

**Comment by iKaneki-Ken** [comment]
Do the follow.

> * cd {directory you put Thermos in}
> * git pull origin master
> * ./gradlew clean setupCauldron jar

Done.

**Comment by Robotia** [comment]
@vrackfall You need `git` command line. If you are on Windows: http://blog.countableset.ch/2012/06/07/adding-git-to-windows-7-path/

**Comment by vrackfall** [comment]
@Robotia 
Now It's work, thanks :D , you can close the issue
