### ISSUE TITLE
Multiple craft on startup

### ISSUE THREAD

**Issue by ThisMisterious** [TCPR/Thermos#103]
http://pastebin.com/S0TqiPHe

**Comment by iKaneki-Ken** [comment]
This is rather confusing, but it seems you don't have the right library files. They can be found in TCPRs GitHub

**Comment by ThisMisterious** [comment]
Hello, sory for my english i'm french.
I ave download lib with your script on install instruction.

**Comment by ThisMisterious** [comment]
I download and re upload the library, but the problem is still there.

**Comment by Robotia** [comment]
Salut! Je parle francais parce que j'appris dans l'école. :stuck_out_tongue: Mais...je suis parasseux avec les accents, desole!

Vous avez une probleme avec les libraries. Il faut telecharger les nouvelles libraries qui nous avons telecharge vers GitHub. 

Pour B23, telecharger [les](https://github.com/TCPR/Fixes/raw/47d85fe87078f4d8d454e79a1bdc59eb53847be8/Thermos-Libraries/libraries.zip).
Pour B24, telecharger [les](https://github.com/TCPR/Fixes/blob/99cc3d5d9ebd13c5c655ff13d7f889b9fed2d7d3/Thermos-Libraries/libraries.zip?raw=true).

Instructions pour vous:
1. Efface le dossier "libraries" dans votre le dossier de votre serveur.
2. Extrait le zip "libraries" dans le dossier pour votre serveur.
3. Voila, ca marche! :smile:

**Comment by Yive** [comment]
I uploaded a fixed version https://github.com/TCPR/Fixes/blob/master/Thermos-Libraries/libraries.zip The previous one that @Robotia uploaded had a few missing libraries + a few libraries that versions were updated.

**Comment by ThisMisterious** [comment]
yeaaaaaaaaaaaaa Thanks ! :D

**Comment by Robotia** [comment]
Pas de probleme!
