### ISSUE TITLE
Time out Random

### ISSUE THREAD

**Issue by enterprise12nx** [TCPR/Thermos#105]
I noticed in the past build or two, after being up for several hours, everyone will randomly time out, nothing can be put into the console then, but it lists everyone as still on, but reconnecting will always time you out.
Restarting fixes the problem, but this seems to happen 90% of the time, logs show nothing

**Comment by NEXUS2345** [comment]
That is the server threads stalling out. Install Sampler from here: http://files.player.to/sampler-1.58.jar
It is from the developer of FastCraft and IC2 and will create a stall report when the server thread stalls. You can then look at the first item in the stall report, and that is usually the cause.

**Comment by Robotia** [comment]
WarmRoast also works well.

I was having a similar issue on my server with logistics pipes, it might be someone knowingly using a mod item to time out your server.

**Comment by enterprise12nx** [comment]
cant use warmroast on server hosts

**Comment by iKaneki-Ken** [comment]
@enterprise12nx As suggested before. http://files.player.to/sampler-1.58.jar

**Comment by Esctogrillo** [comment]
[stall-2016-02-15_10.26.40.txt](https://github.com/TCPR/Thermos/files/131222/stall-2016-02-15_10.26.40.txt)
I use AutoSaveWorld just for auto-commands, backup (manual) and restart countdown.
And yes, I'm getting timed outs too. A lot of it.

**Comment by spannerman79** [comment]
"Usually" with a stall report the first listed is the actual cause - usually.

I use the term usually loosely though - not everything appears either.  You'll need to do actual profiling though to pin point issues.

**Comment by enterprise12nx** [comment]
so when the server stalls it creates a log telling me what could be the cause?
can this also determine what lags the server?

**Comment by NEXUS2345** [comment]
Not really no, for that sort of thing WarmRoast is best. You could use TickProfiler https://jenkins.nallar.me/job/TickProfiler/branch/1.7.10/23/ as this will be able to identify laggy entities, tile entities, and chunks.

**Comment by iKaneki-Ken** [comment]
@Esctogrillo I highly suggest you use Bukkit's built in autosave and chunk GC. You can find the options for it within bukkit.yml

**Comment by enterprise12nx** [comment]
@iKaneki-Ken i use my host providers auto save feature, should i use bukkits instead?

**Comment by Robotia** [comment]
To all involved: if you downloaded the ThermosServer repo, you may need to redownload the minecraft_server1.7.10.jar if you are having this problem.

**Comment by Esctogrillo** [comment]
@iKaneki-Ken I removed AutoSaveWorld and the timed outs continues...
[stall-2016-02-15_19.16.48.txt](https://github.com/TCPR/Thermos/files/131479/stall-2016-02-15_19.16.48.txt)
But this never happens with KCauldron.

**Comment by Robotia** [comment]
@Esctogrillo Redownload the minecraft_server jar.

**Comment by enterprise12nx** [comment]
@Robotia where is that?

**Comment by NEXUS2345** [comment]
@enterprise12nx https://github.com/TCPR/ThermosServer

**Comment by enterprise12nx** [comment]
happened, heres the stall report
http://pastebin.com/HNVMBZ1n

@iKaneki-Ken @Robotia

**Comment by NEXUS2345** [comment]
Looks like ComputerCraft is causing the stalls in my opinion. It may be worth going around and removing or disabling people's computers one by one to find the culprit.

Sent from Outlook Mobile




On Tue, Feb 16, 2016 at 12:17 PM -0800, "enterprise12nx" <notifications@github.com> wrote:





happened, heres the stall report
http://pastebin.com/HNVMBZ1n

@iKaneki-Ken @Robotia

---

**Comment by Esctogrillo** [comment]
@Robotia Continues...: 
[stall-2016-02-16_19.53.53.txt](https://github.com/TCPR/Thermos/files/133395/stall-2016-02-16_19.53.53.txt)

**Comment by NEXUS2345** [comment]
@Esctogrillo can you give us a copy of your spigot.yml and cauldron.yml please?

**Comment by Esctogrillo** [comment]
[bukkit.yml.txt](https://github.com/TCPR/Thermos/files/133468/bukkit.yml.txt)
[spigot.yml.txt](https://github.com/TCPR/Thermos/files/133469/spigot.yml.txt)

**Comment by spannerman79** [comment]
Anti xray should be disabled - it was always buggy, not even bloodmc could get it working correctly with cauldron.  If you want anti xray use a plugin.  Search spigot resource page

**Comment by NEXUS2345** [comment]
@Esctogrillo can you give us the cauldron.yml as well please, as I asked for previous to this.

@enterprise12nx @Esctogrillo how often do you restart your servers? Our servers are not experiencing these stalls with 6 hour restarts. Also, what are your JVM parameters when launching the server?

**Comment by enterprise12nx** [comment]
@NEXUS2345 i restart mine every 6 hours as well, mine is run by BisectHosting, so they have their own startup

**Comment by Cracks777** [comment]
what host are you guys using? my server has been up for 2 days without restarts and still running 19.98 tps with 3-4 players on at all times?

**Comment by NEXUS2345** [comment]
@Cracks777 host doesn't really matter, any server with a significant player base (20+ concurrent users, possibly less) should have a restart schedule to do a complete clear of the Heap space and allow for configuration updates to occur.

@Esctogrillo Robotia already told you to try redownloading minecraft_server.jar, have you attempted this?

@enterprise12nx did you read my last set of feedback? Seems to be possibly something with ComputerCraft, although a second stall report would allow me to confirm this for sure.

**Comment by enterprise12nx** [comment]
@NEXUS2345 yes, but fixing it, could happen again at any time, when it happens again i'll post it here.

If anything, is there a way to have the server restart when it hangs like that for say 30 seconds?

**Comment by iKaneki-Ken** [comment]
@enterprise12nx Unfortunately no there isn't as the main server there is still kept alive, it's just ComputerCrafts thread that's stalling the server.

**Comment by NEXUS2345** [comment]
@enterprise12nx it would most likely have to be an external application. Possibly a python script that detects the creation of a new stall report and issues a command to kill the Java process and then restarts the server. The issue is, as @iKaneki-Ken mentions, that the server is still technically up and running, but is stuck in an infinite loop or has an extremely long queue of data waiting for processing, which is why you get timeouts from the server as opposed to it completely crashing.

**Comment by Esctogrillo** [comment]
@NEXUS2345 I restart my server manually with Stop command. And I already re-download minecraft_server.jar
[cauldron.yml.txt](https://github.com/TCPR/Thermos/files/133541/cauldron.yml.txt)

**Comment by Robotia** [comment]
@Esctogrillo Limit the computer-craft program execution time. Also, run warmroast when the server times out so you can identify if the problem is on the main server thread.

**Comment by Esctogrillo** [comment]
@Robotia Modpack without computer craft. I will use warmroast, but when server is running normally or after a timed out?

**Comment by Robotia** [comment]
@Esctogrillo Use WarmRoast when the server times out, I want to see what item it is. Do you have logistics pipes?

**Comment by Esctogrillo** [comment]
@Robotia Nope. Modlist [here] (https://github.com/TheKingdomServer/JordannPack)

**Comment by NEXUS2345** [comment]
@Esctogrillo could you try setting the following option inside cauldron.yml to true:
`load-chunk-on-forge-tick: false`

@enterprise12nx could you provide your bukkit.yml, spigot.yml and cauldron.yml please?

**Comment by enterprise12nx** [comment]
[bukkit.txt](https://github.com/TCPR/Thermos/files/135017/bukkit.txt)
[cauldron.txt](https://github.com/TCPR/Thermos/files/135018/cauldron.txt)
[spigot.txt](https://github.com/TCPR/Thermos/files/135019/spigot.txt)

**Comment by enterprise12nx** [comment]
So it stalled a lot today, here they are xD


[stall reports.zip](https://github.com/TCPR/Thermos/files/135146/stall.reports.zip)

**Comment by NEXUS2345** [comment]
@enterprise12nx it looks like Project Red volcano generation is causing your stalls. Might be advisable to disable them in the config if possible.

**Comment by Robotia** [comment]
Hmm, in that case, this is probably related to world generation and the fix we made. Will look into this.

**Comment by enterprise12nx** [comment]
ok @Robotia our worlds almost completely generated now, so you may have to have others test it

**Comment by linkinkov** [comment]
Sometimes also have this problem and cant reproduce

**Comment by Robotia** [comment]
It seems to be world gen lockup

**Comment by spannerman79** [comment]
@Robotia this happens even with Vanilla Forge.  I think the issue comes down to mods that do world gen and how they implement their generation.  There isn't a single mod or group of mods that I can point my finger at and say "these have dodgy worldgen coding" either.

**Comment by Robotia** [comment]
@spannerman79 true, I'm thinking maybe world gen should be set up as a cancellable thread...

**Comment by spannerman79** [comment]
Good idea - just might have to be careful how you do it, or ores/mod specific resources might not generate correctly, or mods that hook into village generation creating even more fubar villages (compared to how minecraft creates some villages lol)

**Comment by linkinkov** [comment]
How it can be worldgen problem then i have all world pregen?

**Comment by NEXUS2345** [comment]
@linkinkov you are likely having a different stall, get Sampler and when a stall report is produced, post it here using pastebin or github gist.

**Comment by Robotia** [comment]
Share a stall log please. And I think it's world gen because the server is set so it doesn't crash when world gen locks up.

**Comment by Esctogrillo** [comment]
![warmroast](https://cloud.githubusercontent.com/assets/14919996/13206061/8606c090-d8d5-11e5-9e99-ef33bb694899.png)
[stall-2016-02-21_19.29.59.txt](https://github.com/TCPR/Thermos/files/139905/stall-2016-02-21_19.29.59.txt)
I don't know if the WarmRoast works on Timed Out, in console appers a server timed out error and I'm unable to access localhost:23000 - After timed out all works fine.

**Comment by spannerman79** [comment]
From looking at that stall I would say there are issues with your MySQL server that one of your plugins use. 

Logit looks like to be the issue https://www.spigotmc.org/threads/end-of-logit-development-read-thread.42071/

**Comment by linkinkov** [comment]
My timeout stall report:
http://pastebin.com/XHtziZ1W

**Comment by Robotia** [comment]
@linkinkov disable the spigot async lighting

**Comment by Robotia** [comment]
Spigot watchdog should now auto restart if this happens
