### ISSUE TITLE
How to add a library ?

### ISSUE THREAD

**Issue by vrackfall** [TCPR/Thermos#106]
Hi I wan't to import the tools.jar library of JDK (in the lib folder of the JDK installation of my computer), how can I do that ? 
I tried with eclipse but I don't know how to do after ? 
Do I have to modify build.gradle ? If yes, how ? 
Thanks

**Comment by Robotia** [comment]
Did you run the setupCauldron?

**Comment by vrackfall** [comment]
yep, I also run gradlew eclipse, but now "gradlew tasks" doesn't work or is very slow

**Comment by vrackfall** [comment]
I did not yet add tools.jar

**Comment by Robotia** [comment]
Why do you need to add the JDK tools? It should be part of the project by default.

**Comment by iKaneki-Ken** [comment]
Something tells me you're new to Java development. The tools.jar is library automatically imported when you select your JDK inside your IDE.

**Comment by vrackfall** [comment]
My IDE is eclipse, I'm not really new in java development. it's just that I'm new with Thermos development (I'm better with forge). Just to be sure, after doing "gradlew  setupCauldron" I to do "gradlew eclipse", no ?

**Comment by Robotia** [comment]
Wait...no
All you need to do is /gradlew clean setupCauldron
This includes setting up eclipse.

**Comment by vrackfall** [comment]
Ok, and for accessing the project into eclipse, I've to choose the "eclipse" folder ?

**Comment by vrackfall** [comment]
I opened the workspace "eclipse" in Eclipse but I get this error : 
Could not write metadata for '/Forge'.
F:\Minecraft\Thermos\eclipse\.metadata\.plugins\org.eclipse.core.resources\.projects\Forge\.markers.snap (Le chemin d’accès spécifié est introuvable)

**Comment by Robotia** [comment]
@vrackfall It's messed up, here's how I set it up for myself:
1. `./gradlew clean setupCauldron`
2. Open up Eclipse with default work space (not cauldron)
3. Import the project from `Thermos/eclipse` into your default workspace


Before every ./gradlew clean setupCauldron, I delete the repo in eclipse and re-import it. 

This is likely a bug with the setupCauldron script originating to the Forge one for Minecraft modding, will look into it.

**Comment by vrackfall** [comment]
Ok, so I did all you said, now everything works (or almost), what is my goal : 
Automatically load an JavaAgent ([PMLPremain](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-tools/2602016-partial-modification-loader-pml-9-2-for-minecraft)) without using this argument (by using a batch file on windows) at the server launch :  -javaagent:PMLCore/PMLPremain.jar=-MCSide:Server

That's the file I modifying to do that : http://pastebin.com/6BDSW0SH
What's highlighted is the error (because tools.jar is not find). 
So, I add it with the "libraries" "section of configure build path".
Everything is ok (I think, and it should work).
But when I'm doing gradlew build, I'm getting this error : 

How to fix that ?
Thanks

**Comment by vrackfall** [comment]
@Robotia
Just to explain what I wan't to do with Thermos source : 
Thermos is really cool because it's forge + Bukkit, but we can attach it another thing : [Partial Modification Loader](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-tools/2602016) created by The_WeatherPony. PML work on client, server, forge, liteloader and ... Thermos. It can load special mods :+1:  PMLMods like [that](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1285986). To attach PML to Thermos I just have to add this argument to the Thermos [launch script](https://github.com/TCPR/Thermos/blob/master/INSTALLATION.md) : 
-javaagent:PMLCore/PMLPremain.jar=-MCSide:Server

And everything works perfectly :)

But there is a problem : 

I cannot use the Thermos [launch script](https://github.com/TCPR/Thermos/blob/master/INSTALLATION.md) because my minecraft server is hosted, and I don't have the right to modify it. So I think I find a way to attach PML to Thermos without using it (the launch script).

The way I find is to modify the Thermos main class (cpw.mods.fml.relauncher.ServerLaunchWrapper) like [that](http://pastebin.com/6BDSW0SH) using tools.jar. For now it doesn't work. 
So could you help me ? 
Thanks

**Comment by spannerman79** [comment]
PMLMods would, prob have the same view as mods created with MCreator....

**Comment by Robotia** [comment]
@vrackfall This would take a lot of extra work, 3rd party hosters are never happy when a server attempts to modify their launch scripts. I wouldn't want you getting banned from the provider. :confused:

**Comment by vrackfall** [comment]
@Robotia
I don't wan't to modify the 3rd party hosters launch script, just modify the main class of Thermos.
That way everyone is happy, it just adds something more to my serv. And no, I will not be banned, I've OpenMod (I can use any modified minecraft version, if you see what I mean). I already asked, and they will let me do that. So could you help me to finish the job ?

**Comment by bookerthegeek** [comment]
@vrackfall why not just ask the server hosting to change the startup script? I would recommend switching hosts if they can not provide a good reason why they will not if they wont.

**Comment by vrackfall** [comment]
I cannot switching host now (I've paid for two year, since one year), also the price of the server provider I use is very cheap, so .... Finally I already asked, and they didn't want to change it for me so...

**Comment by Robotia** [comment]
@vrackfall What do you pay a month?

**Comment by vrackfall** [comment]
@vrackfall 
Did you mean, what I pay a month to my server be hosted (It's not product placement) : ### I've the unlimited for 24 month, go [here ](http://www.omgserv.com/en/hosting/minecraft-server/unlimited/)if you wan't to know.

**Comment by bookerthegeek** [comment]
Did they say why they would not consider additional arguments for the startup? 

Who is your host?
& what package are you getting from them?

**Comment by vrackfall** [comment]
@bookerthegeek
Just look up, ^^

**Comment by Robotia** [comment]
This is the problem with using MC hosting services...they do not give you control over your system.

I am sorry @vrackfall but I do not know how to help you with this. :confused: 
I have never used PML and I do not want to modify the code that launches Forge for Thermos; it may make other servers unstable.

**Comment by vrackfall** [comment]
"It may make other servers unstable."
I never talked about other Thermos servers, just mine.
Also, I think I've found the solution, ([here](http://pastebin.com/6BDSW0SH)) with tools.jar.
But, when I'm doing "gradlew build", I'm getting that : 

* What went wrong:
Execution failed for task ':Cauldron:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

So just for know where is the compiler output ?

**Comment by vrackfall** [comment]
"It may make other servers unstable."
I never talked about other Thermos servers, just mine.
Also, I think I've found the solution, (here) with tools.jar.
But, when I'm going to "gradlew build", I'm getting [that ](http://pastebin.com/Qrbpp1cz) in the compiler output (I never touched this class)

**Comment by Robotia** [comment]
@vrackfall Do `git pull`
