### ISSUE TITLE
[Proposal] Fix MobiusCore & Opis Support

### ISSUE THREAD

**Issue by Yive** [TCPR/Thermos#109]
Will be testing out custom sources of MobiusCore & Opis this week to try & add support for them on Thermos.

**Comment by Time6628** [comment]
Might I suggest adding Thermos' own tick profiler similar to opis?

**Comment by Robotia** [comment]
Maybe, but tick profiler is also available.

**Comment by Time6628** [comment]
Yea but I was thinking of something build into thermos itself. Since most lag doesn't happen all the time and there really isn't a way to catch it with tick profiler unless you have all the players using the mod.

**Comment by Cracks777** [comment]
https://github.com/Prototik/MobiusCore/commit/ab4ae9d82ed3c02be63f2536880eb089059bdac9


is this what broke opis, renaming from Kcauldron to thermos?

**Comment by Robotia** [comment]
I wanted to revert everything to fit MinecraftForge style

**Comment by Cracks777** [comment]
?

**Comment by Robotia** [comment]
@Cracks777 I mean that Cauldron should've never become incompatible in the first place. It is absurd to think that you should change something and expect everyone else to make their code compatible with yours

**Comment by Robotia** [comment]
Fulfilled in 36
