### ISSUE TITLE
Tronopolis/RR3:Mainline

### ISSUE THREAD

**Issue by archangelish** [TCPR/Thermos#110]
Hello Thermos team,
My IGN is archangelish I am a mod from the Mainline server at Tronopolis and asked by Tyler one of our owner/IT to send you a message to explain the issue we are experiencing. The First week or so that the server was open when you used a Reinforced watering can with the autonomous activators It worked but when we updated thermos, the AA went from working like it should to only working with weapons. If you are not familiar with the AA they act like a player (IE: Shift clicking (R/L), using items, placing blocks..,.). We have tried adding CoFH to our friends list in Towny like some forums recommend to fix the issue but that did not resolve the problem. If there is ANY info I can provide to you please let me know.
-Thank you for your time
Arch
and the Tronopolis community

**Comment by NEXUS2345** [comment]
Try adding #[CoFH] to your Towny friends list.

**Comment by tyler2k15** [comment]
That doesn't work, it's already been attempted.

**Comment by tyler2k15** [comment]
Attempting to add CoFH, [CoFH], and #[CoFH] all return ``none of those names are valid``

**Comment by NEXUS2345** [comment]
That sounds like an issue with Towny not recognising fake player IDs. It could be to do with Thermos but is more likely either a misconfiguration in Towny or an issue with the Towny plugin itself. We at Prelude use Grief Prevention Plus and FTB Utilities, as they are capable of recognising these fake players.

**Comment by iKaneki-Ken** [comment]
Unfortunately then, it seems you're doing something wrong as Reinforced Watering Cans work on my server with no problems at all.

**Comment by archangelish** [comment]
being that you just put the watering can In to the AA and turn it to no signal, right click and provide power I don't see how we could mess it up @iKaneki-Ken

**Comment by iKaneki-Ken** [comment]
In regards to server configuration files I mean. I'm not saying you messed up putting the Watering Can in the Autonomous Activator, what I'm saying is something is missing inside your protection plugins configuration file that would normally allow items like the Reinforced Watering Can to work.

**Comment by archangelish** [comment]
@iKaneki-Ken could you do me a big favor then? If yes, are you running a server and If so could you send me a copy of your towny configs so WE could compare. please.

**Comment by Robotia** [comment]
Autonomous activators are broken in B23/B24, I have yet to fix them.

**Comment by Robotia** [comment]
Augh I hate closed source mods, time to brute force this one.

**Comment by spannerman79** [comment]
Request permission here perhaps? https://github.com/CoFH/Feedback/issues

**Comment by archangelish** [comment]
Thank you very much @thermos team. For the all the hardwork you guys do!

**Comment by tyler2k15** [comment]
Just for reference, the above issue does not exist on the following kCauldron version (http://prntscr.com/a3ravx)

**Comment by Robotia** [comment]
@tyler2k15 I know, it is due to Thermos' uber protection.

**Comment by tyler2k15** [comment]
I assumed you did as I believe we had this discussion before. Wanted to just make it clear to others that it is indeed isolated to Thermos (when using in conjunction with Towny)

**Comment by Robotia** [comment]
@tyler2k15 See if it is fixed now?

**Comment by tyler2k15** [comment]
Build 25?

**Comment by tyler2k15** [comment]
@robotia

**Comment by Robotia** [comment]
https://github.com/TCPR/Thermos/releases/tag/25
@tyler2k15

**Comment by tyler2k15** [comment]
This issue has been resolved,
