### ISSUE TITLE
Thermos appears to alter the speed at which Lava and water flow

### ISSUE THREAD

**Issue by NEXUS2345** [TCPR/Thermos#117]
In vanilla, a normal cobblestone generator relies on the fact that lava flow slightly faster than water, but with Thermos, this appears to have been inverted, with water flowing significantly faster than lava, leading to the lava being turned to obsidian. For the players on our TerraFirmaCraft server, this has led to them losing items and the ability to produce vanilla cobblestone. If this issue could be fixed, that would be greatly appreciated.

**Comment by Robotia** [comment]
Must be related to https://github.com/TCPR/Thermos/commit/054ad28068e8d675bf27ec9f816e1ed235cd06e1

**Comment by Robotia** [comment]
@NEXUS2345 Have you tried this on PaperSpigot 1.7.10?

**Comment by Robotia** [comment]
Or related to https://github.com/PaperSpigot/Paper/commit/e12f1faed1076d7489be00e4962efd529548134e

**Comment by NEXUS2345** [comment]
Will test with just PaperSpigot just to be sure.

**Comment by Robotia** [comment]
@NEXUS2345 See if it is fixed in B27.

**Comment by Robotia** [comment]
@NEXUS2345 is this fixed?

**Comment by NEXUS2345** [comment]
@Robotia looks like it.
