### ISSUE TITLE
Soul Bound from EnderIO

### ISSUE THREAD

**Issue by AppleObsession** [TCPR/Thermos#118]
It seems SoulBound enchantment does not Bind to player upon death.  The soul bound item disappears when it should stay in your Inventory.

**Comment by Robotia** [comment]
Please share a video or a GIF of this

**Comment by enterprise12nx** [comment]
this happens for anything sould bound my players confirmed

**Comment by archangelish** [comment]
https://drive.google.com/file/d/0B-V6_mCGQ1kCUkZEY0dtcmx4eGc/view?usp=sharing

**Comment by Robotia** [comment]
@archangelish Thank you, will be looking into this.

**Comment by archangelish** [comment]
@Robotia anytime :) thank you guys for your hard work.

**Comment by Robotia** [comment]
Fixed in 36
