### ISSUE TITLE
[Proposal] Default Server Icon

### ISSUE THREAD

**Issue by Robotia** [TCPR/Thermos#120]
Most people don't have server icons...
Was thinking of making a default, unique icon generator for Thermos. Like how on GitHub each person who creates an account gets a different graphic, except the server icon would be something MC related (hopefully).

**Comment by TerdyTheTerd** [comment]
This wont over write server icons right? I have one and would want it over written

**Comment by Robotia** [comment]
It shouldn't

**Comment by spannerman79** [comment]
...famous last words :P

**Comment by Robotia** [comment]
Heh yeah

**Comment by Robotia** [comment]
Done! (thanks to spuri4096 (http://c0dart.org) for his awesome art!)
