### ISSUE TITLE
Players cannot interact / place blocks on "spawn" worlds

### ISSUE THREAD

**Issue by kaziu687** [TCPR/Thermos#121]
When someone without op permission try to place non vanilla block or interact with non vanilla item on world that contain "spawn" word in its name, then message "You cannot use that item here." appears. On my server players have ability to buy small regions on server spawn area, now they are unable to use them. It will be nice to allow disabling world name based protection.

**Comment by iKaneki-Ken** [comment]
Then don't have a world named spawn as your main world.

**Comment by Robotia** [comment]
I will add this option

**Comment by kaziu687** [comment]
Temporarily recompiled thermos with changed ForgeEventFactory.java.patch

**Comment by spannerman79** [comment]
Do a PR with your change to the repo @kaziu687
