### ISSUE TITLE
[Error] Thermos 23>26 - AutoIn does not work properly! Urgent!

### ISSUE THREAD

**Issue by Esctogrillo** [TCPR/Thermos#122]
First, I don't know what version this starts to happen, but I mean was in 23 or 24...

The player try to join but is denied with "Failed to verify username" from AutoIn. Console get this error:
`[AutoIn] [Error] Exception verifying <PlayerName>: Cannot invoke met
hod public abstract com.mojang.authlib.GameProfile com.mojang.authlib.minecraft.
MinecraftSessionService.hasJoinedServer(com.mojang.authlib.GameProfile,java.lang
.String) throws com.mojang.authlib.exceptions.AuthenticationUnavailableException`

Thermos 26 is getting this more than others versions.

Using KCauldron this not happens.

**Comment by Robotia** [comment]
What is auto in?-and please share a longer log

**Comment by Esctogrillo** [comment]
AutoIn is for Premium players to log in server without /register and /login. This is the log, server still on but with this error each player that try to join.

**Comment by spannerman79** [comment]
@Robotia [this](https://www.spigotmc.org/resources/auto-in.578/) is AutoIn

**Comment by Robotia** [comment]
Hmm have you try B25?

**Comment by Robotia** [comment]
Your libraries might be messed up, what version of mojang auth library you have?

`find libraries/ | grep -i auth `

**Comment by Robotia** [comment]
@Esctogrillo is this fixed?

**Comment by Esctogrillo** [comment]
@Robotia Sorry, I'm testing yet. 
With `grep -i auth` nothing happens.

**Comment by Robotia** [comment]
Fixed?

**Comment by Esctogrillo** [comment]
Yes! It's working fine now :-)
