### ISSUE TITLE
[B27] Steve's Carts Cart modifier completely broken

### ISSUE THREAD

**Issue by NEXUS2345** [TCPR/Thermos#123]
Basically, if you attempt to modify a steve's cart by placing it into the cart modifier and then attempt to remove a component, that component will visually appear to be minecraft flint.

Screenshots:
Before attempting to remove: https://gyazo.com/5e6c3aefdc671910e801c1588bc6b683
After attempting to remove: https://gyazo.com/cd6358ffe68af6ef2df095a04edbe092

**Comment by Robotia** [comment]
Related to item nullness checking
