### ISSUE TITLE
Mekanism Flamethrower Not Working

### ISSUE THREAD

**Issue by enterprise12nx** [TCPR/Thermos#124]
So i made a flamethrower from Mekanism, and using it on myself does no damage, nor does using it on anything burnable, it doesnt even place a burning block.

fire spread is enabled on the server(tested to work) as well as in griefpreventionplus's claims(tested to work)

**EDIT: works on mobs on players, just doesnt place a burning block, or however it works!

**Comment by NEXUS2345** [comment]
Double check your WorldGuard settings. If not then I am not sure.

**Comment by Robotia** [comment]
It could be a number of plugins stopping it

**Comment by enterprise12nx** [comment]
plugins:
Clearlagg
Enjin Minecraft Plugin
Essentials:
  # General physics/behavior modifications.
  prevent:
  fire-spread: false
    lava-fire-spread: false
    flint-fire: false
    lightning-fire-spread: true
    fireball-explosion: false
    fireball-fire: false
    fireball-playerdamage: false
Grief Prevention Plus:
  FireSpreads: true
  FireDestroys: true
Groupmanager
Jobs Reborn
Minebackup
Simple Clans
Vault
Votifier
Worldborder
Worldedit
Worldguard
fire:
    disable-lava-fire-spread: false
    disable-all-fire-spread: false
    disable-fire-spread-blocks: []
    lava-spread-blocks: []

**Comment by Robotia** [comment]
Hmm might be some of the fire stuff in essentials

**Comment by enterprise12nx** [comment]
@Robotia how? all fire options are enabled except lightning.

**Comment by Robotia** [comment]
Whoops I read it as false meant disabled

Have you tried an old build like B13?

**Comment by enterprise12nx** [comment]
yes, thats the build im using since the newer ones arent stable yet

**Comment by Robotia** [comment]
Is the flame thrower not working in it? Try B23?

**Comment by enterprise12nx** [comment]
oops i mean im using B23 sorry, i could try B13 i guess

**Comment by enterprise12nx** [comment]
B23: no plugins, fresh world, private server - Flamethrower does not work
B13: no plugins, fresh world, private server - Flamethrower (will edit)

I cannot get B13 it has a zip of what(for me) is nonsense xD
B14 crashes on startup
@Robotia

**Comment by enterprise12nx** [comment]
Well, there was a mode switch for it in the latest update..but no wiki on it, etc
combat mode, i assume is combat only
heat mode..no idea, same as the next "Inferno" mode
Inferno Mode..same as heat?

none burn blocks, but heat and inferno smelt blocks that are not physically placed, like you know dropped on ground

**Comment by Robotia** [comment]
@enterprise12nx I can take a look at the Mekanism code, link me (lazy) :stuck_out_tongue:

**Comment by enterprise12nx** [comment]
https://github.com/aidancbrady/Mekanism

**Comment by Robotia** [comment]
https://github.com/aidancbrady/Mekanism/blob/99fc98faf5dbe60ce18b8484eabfba25b3ace7ae/src/main/java/mekanism/common/entity/EntityFlame.java
Mekanism's Flamethrower does not actually set stuff on fire. This is not Thermos' fault, make a request to @aidancbrady for this.
