### ISSUE TITLE
[User Error] Thermos won't launch

### ISSUE THREAD

**Issue by TerdyTheTerd** [TCPR/Thermos#127]
So this is more than likely an issue on my end, but when I download a new version of thermos, and the new libraries with it, place them both in the server directory (of course deleting the old ones) and try running the server it always says <code>Exception in thread "main" java.lang.NoClassDefFoundError: joptsimple/optionSpec</code> but if I search for "jopt" in the new libraries folder it has several results. Am I missing something simple here? Did configs need to be reset or something else happen while I was gone, because I don't see anything like that in the recent commits or releases, and no one else has reported it so it must be on my end.

Just went and looked inside the jopt-simple-4.9.jar and sure enough the OptionSpec class was there, so idk why for me its saying it can't find it

**Comment by tyler2k15** [comment]
What build @TerdyTheTerd

**Comment by TerdyTheTerd** [comment]
And this is why you post issues, after someone else ask a question you catch your simple mistake. I didn't realize the new libraries folder was called "Thermos-1.7.10-1614.25-libraries" instead I was using the older "libraries.zip" thinking they were the same (I had two "libraries.zip so I thought the second one was the new one). As I figured, simple user error, now I feel really stupid, oh well it happens
