### ISSUE TITLE
Instalation Failiure

### ISSUE THREAD

**Issue by MrsMeowys** [TCPR/Thermos#130]
Hello. I made a bran new linux installation to test out Thermos, from this website: http://tcpr.github.io/Thermos/install#

When I try to launch I get this error:

xxxx:~/ModPackTest/ThermosServer-master$ java -d64 -server -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+UseStringDeduplication -Xms4G -Xmx4G -XX:hashCode=5 -Dfile.encoding=UTF-8 -jar Thermos.jar nogui
Unrecognized VM option 'UseStringDeduplication'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

Thanks.

**Comment by Robotia** [comment]
You are using java 7, use java 8 instead

**Comment by MrsMeowys** [comment]
Won't that create issues with 1.7.10 mods and craftbukkit/bungeecord?

**Comment by Robotia** [comment]
It should not generally speaking. If you look at http://mcstats.org/plugin/Thermos you will see that the majority of Thermos users are on Java 8. :stuck_out_tongue_winking_eye:

**Comment by MrsMeowys** [comment]
I saw that, but still didn't get an answer to my question. 
I don't know what the other users are using.

**Comment by Robotia** [comment]
Oracle JDK 8
http://www.webupd8.org/2012/09/install-oracle-java-8-in-ubuntu-via-ppa.html
http://www.webupd8.org/2014/03/how-to-install-oracle-java-8-in-debian.html

**Comment by iKaneki-Ken** [comment]
I have never once had an issue where a plugin, mod or piece of server software had issues performing or even starting up due to using Java 8.

**Comment by TerdyTheTerd** [comment]
The issues with java 8 update 20 and forge versions has long since been fixed. There is no reason not to be using java 8 at this point in time

**Comment by spannerman79** [comment]
> saw that, but still didn't get an answer to my question. 
> I don't know what the other users are using.

@MrsMeowys Java 8 JDK is what I'm using

**Comment by iKaneki-Ken** [comment]
@MrsMeowys Here's the answer to your issue:

Want to launch with Java 7? Remove the Java GC argument "UseStringDeduplication". Fixed, you will now be able to launch Thermos using Java 7.

**Comment by Robotia** [comment]
G1GC and String Deduplication are java 8 features that are optimal for Minecraft server ram

**Comment by iKaneki-Ken** [comment]
As @Robotia Robotia said.
