### ISSUE TITLE
[Crash] Mystcraft - java.lang.NoSuchFieldError: field_73244_f

### ISSUE THREAD

**Issue by OxLemonxO** [TCPR/Thermos#134]
I am having a problem with Mystcraft and Thermos. Crash log: http://pastebin.com/uy2MpYYv

**Comment by spannerman79** [comment]
https://github.com/XCompWiz/Mystcraft-Issues/issues/44#issuecomment-85669046

**Comment by Robotia** [comment]
I'll try to reintroduce compat

**Comment by Robotia** [comment]
@OxLemonxO Can you share the Mystcraft jar? Seems to be closed source. T_T

**Comment by OxLemonxO** [comment]
@Robotia http://minecraft.curseforge.com/projects/mystcraft/files/2266245

**Comment by Robotia** [comment]
Try build 32 please

**Comment by Robotia** [comment]
Fixed in 36
