### ISSUE TITLE
[Proposal] Opis mapless fork

### ISSUE THREAD

**Issue by spannerman79** [TCPR/Thermos#137]
Due to the (current/past) fork maintainer you should consider forking https://github.com/Gamealition/Opis & https://github.com/Gamealition/MobiusCore

@RoyCurtis has since marked that fork as abandoned so something to consider.

Look at the fork readme at whats different between ProfMobius Opus and that fork (mapless)

**Comment by Yive** [comment]
This is planned, but not sure when it'll become a reality.

**Comment by spannerman79** [comment]
Well the fork really isn't a fix, just removes the old buggy commit spot that ProfMobius used from Mapwriter - makes it easier to choose what map you want to use (Voxel, updated Mapwriter 2, JourneyMap etc)

**Comment by Yive** [comment]
I know, it's just that the mapless version is still not supported oddly enough

**Comment by Robotia** [comment]
Not related to Thermos, should instead be posted on Gogs in Fixes. http://gogs.tcpr.ca/TCPR/Fixes

**Comment by Penrouk** [comment]
Can anyone send me the download to opis mapless that works. The github link says 404 not found.

**Comment by red-mist** [comment]
I, also, would like a working link to this if at all possible.

**Comment by spannerman79** [comment]
I think I might have a copy somewhere - I am just unsure at what version/build it was at.  I didn't get the chance to fork the original repos :disappointed: 

https://mega.nz/#!B8AClZqA!xtBTILAocVjbV8-jfdNT1lDlKjlDzoNhx1qjGu1ow3c

**Comment by Penrouk** [comment]
This works for single player. However not for the server. Any chance you got one

**Comment by LemADEC** [comment]
Opis works just fine on server with Build 57, just use the Thermos version of MobiusCore

**Comment by Penrouk** [comment]
Im using KCauldron. Every time I use /opis it kicks me out of game saying "Connection terrminated, a fatal error occured"

**Comment by LemADEC** [comment]
This repository is for Thermos. Issues with KCauldron goes on KCauldron tracker, not here

**Comment by Robotia** [comment]
KCauldron has a discord server, you could join that and ask there as well.
