### ISSUE TITLE
[Bug] Some chunks in nether generates against the main world seed

### ISSUE THREAD

**Issue by bumelul** [TCPR/Thermos#138]
![2016-02-21_15 30 16](https://cloud.githubusercontent.com/assets/17378579/13201923/081bffb2-d8b0-11e5-8702-986de99cf16e.png)
![2016-02-21_15 29 53](https://cloud.githubusercontent.com/assets/17378579/13201924/0b7820f0-d8b0-11e5-9339-016e3ed8cb73.png)

Clean Thermos-1.7.10-1614.28 server. Did not use any mods.

**Comment by Robotia** [comment]
What do you mean by "against"? O.o

**Comment by Cracks777** [comment]
its generating parts using another seed.

**Comment by Robotia** [comment]
O.o I did not modify that behavior. Did you check the world seed in F3?

**Comment by spannerman79** [comment]
If you have forced a world seed in `server.properties` or set in multiverse/multiworld config that differs from the seed in the ( *i think* )`level.dat` then you will get those issues that you see.

This is common if you do a `rm -rf world/` without clearing out your multiverse/multiworld configs fully.

**Comment by Cracks777** [comment]
ah ok then thats why i have seen this then.

**Comment by bumelul** [comment]
spannerman79, server.properties is too clean! Many times i tried re-create world but nether always generates with these buggy-chunks!

**Comment by iKaneki-Ken** [comment]
@bumelul Which plugins are you using? This is more than likely a plugin.

**Comment by bumelul** [comment]
Worldborder, permissionsex, essentials, essentialschat, dynmapcbbridge, dynmapworldguard, worldedit and worldguard...
Try fill map with wb fill - identical results...This occurs with 1/100 generated in nether chunks...

**Comment by Robotia** [comment]
Try it on a *completely* clean Thermos server (no plugins).

**Comment by Robotia** [comment]
@bumelul

**Comment by CovehiH** [comment]
I confirm presence of this problem  but i cant test without mods and plugins

**Comment by Robotia** [comment]
And it's only in the nether?

**Comment by CovehiH** [comment]
yup

**Comment by Robotia** [comment]
Check if this persists in 36?

**Comment by CovehiH** [comment]
May be closed! Never seen again the same glitched chunks!
