### ISSUE TITLE
[Crash] Thermos 1614.27, 28, 30 - java.lang.NullPointerException: Exception getting block type in world

### ISSUE THREAD

**Issue by Masonrf** [TCPR/Thermos#139]
This seem to be affecting my modpack server when trying to create the world.  Its a brand new install of Thermos. I followed the tutorial ( http://tcpr.github.io/Thermos/install ) for the linux script to install it.  I cant reproduce it on singleplayer, so I assume its Thermos related.  Anything to help fix this would be highly appreciated!

Thermos versions tested: 1614.27, 1614.28, 1614.30
 Crash log: http://pastebin.com/9e5r25LQ

**Comment by Robotia** [comment]
Another issue related to #129 , this is due to the custom block updates tracker T_T (sorry)
Should be fixed at the end of this week

**Comment by Masonrf** [comment]
Thanks for the info! I look forward to the update.

**Comment by Robotia** [comment]
@Masonrf try Bleeding 31

**Comment by Masonrf** [comment]
Both Bleeding 31 and release 32 fix this, but I have some more errors.  I will post a new issue soon.

**Comment by Robotia** [comment]
Fixed a while back, should be ok in B47.
