### ISSUE TITLE
[Crash] Thermos #25+ - java.awt.AWTError: Can't connect to X11 window server using...

### ISSUE THREAD

**Issue by juniorjunior** [TCPR/Thermos#140]
Crash Report: http://pastebin.com/caq6Nw05

All Thermos versions starting with #25 and beyond seem to be requiring access to a display. This can be worked around when running on a headless Linux system by using Xvfb, but removing the requirement would be preferable.

**Comment by Robotia** [comment]
Use the nogui server argument, it's expected that everyone use the Thermos Server startup script which includes this

**Comment by juniorjunior** [comment]
So, I have always used the nogui option. However, I also made a terribly newbie style mistake and had a client only mod in my server /mods/ folder. I've told players asking for assistance with their packs on the Technic forums literally hundreds of times to remove client only mods from their server builds. I'm so ashamed.
