### ISSUE TITLE
Soulbound not working on B28 of thermos.

### ISSUE THREAD

**Issue by alicheek** [TCPR/Thermos#142]
After a player dies with soulbound items it seems they loose the soulbound items was an issue with Kcauldron also : https://gitlab.prok.pw/KCauldron/KCauldron/issues/301

Using build 28 of thermos on Infinity 2.3.5

**Comment by Robotia** [comment]
Looks like this issue has re emerged after it was fixed, will be investigated ~ Friday

**Comment by Robotia** [comment]
Fixed in 36
