### ISSUE TITLE
[Proposal] - Good Installation Guide

### ISSUE THREAD

**Issue by Dokman** [TCPR/Thermos#144]
## Issues
**Thermos-specific Feature Proposal**

title: `[Proposal] Thermos Feature - <Good Installation Guide>`

description:
So yeah, a problem that all i think we know is how to get your own libraries if you compile it by yourself, and so on, there is no windows installation.

for windows users we have errors:
![image](https://cloud.githubusercontent.com/assets/2290904/13269571/c2f7b5a4-da88-11e5-9f40-30a28d6348ff.png)

**Comment by spannerman79** [comment]
That is because the large majority of cauldron based servers (cauldron -> kcauldron -> thermos) are actually run on linux - not windows.

Windows servers have an extra cost overhead for the licence fee to run it (be it VPS or dedicated).

Not to mention you can secure a linux server very quickly and easily (iptables + fail2ban + ssh keypairs)

*Source: 20+ years in the IT Industry as well as many Microsoft based certifications, Red Hat, Cisco and linux based certifications*

**Comment by Dokman** [comment]
@spannerman79 i know it but i am running it now on my localhost machine, and i don't want to install a dns and ftp to my virtual machine of linux, and of course is another kind of server, and i can do anything more in those machine

**Comment by Yive** [comment]
That error just means you're missing a library in your libraries folder. It's not a windows only error.

**Comment by Dokman** [comment]
@Yive i know it, but in the build guide, there isn't any kind of help with libraries, and if we can build we need the libraries too

**Comment by Yive** [comment]
```./gradlew clean setupCauldron jar packageBundle```

That's how you get the libraries to be bundled along side compiling the server. At least that's what I use to bundle up the libraries along side of compiling the server.

**Comment by Dokman** [comment]
thanks

**Comment by Robotia** [comment]
Since this is resolved, will be closing.

As a side note, this shouldn't have been titled installation guide. It would've been better to call it "self compiling guide"

**Comment by spannerman79** [comment]
Edit the title then @Robotia - as it will show up in searches if a user actually searches for past/current issues

**Comment by Robotia** [comment]
I'm on my phone :/

**Comment by spannerman79** [comment]
Switch to desktop view and you can do it @Robotia - I've done it before via my Note 4 :frowning:

**Comment by Robotia** [comment]
Ah woops, here we go. @spannerman79 thanks for making my life easier (again)
