### ISSUE TITLE
[Todo] Internationalization

### ISSUE THREAD

**Issue by Robotia** [TCPR/Thermos#145]
According to the MCStats (http://mcstats.org/plugin/Thermos), there are people from many different countries using Thermos.

We need to internationalize the gh-pages and README to support the following languages (in order of number of servers):
+ English (done I guess)
+ Chinese (Simplified, Mandarin)
+ French (I can do this)
+ German
+ Russian ( @linkinkov , @Bogdan-G ?)
+ Japanese (maybe)
+ Brazilian ( @Esctogrillo )
+ Polish ( @skmedix )
+ Dutch ( @Rubbertjuh )

**Comment by Esctogrillo** [comment]
Of course ^.^

**Comment by MixSt** [comment]
I can make some. RU lang.

**Comment by Rubbertjuh** [comment]
If you need Thermos in Dutch I would be happy to help :)

**Comment by Robotia** [comment]
Somewhat resolved with a bit of Google Translate power...inefficient to have to change every language when we update the installation guide.
