### ISSUE TITLE
[Proposal] Auto-download latest libraries 

### ISSUE THREAD

**Issue by Tencao** [TCPR/Thermos#147]
This is mostly for new installs or updates where libraries have been updated. Rather than throwing a class error, instead do a quick scan of libraries to make sure they're all valid and up to date, you can probably limit this to only go off when a new version has been installed.

**Comment by Robotia** [comment]
Not sure how this would be implemented, new code is not really my objective right now. Do you think you would be able to make a pull request for this or share some pseudo-code>

**Comment by Robotia** [comment]
Will take too long to implement, each release now also has the libraries and a note as to whether the libraries have changed.
