### ISSUE TITLE
[Typo] New version of Thermos avaiable

### ISSUE THREAD

**Issue by djoveryde** [TCPR/Thermos#149]
I noticed in the last stable release there's a minor typo when the server located an updated version of thermos.

New version of Thermos avaiable: 1.7.10-1614.30

**Comment by Robotia** [comment]
Yea sometimes the build version on Yive's server lags behind a bit, it usually updates pretty quickly

**Comment by djoveryde** [comment]
its the word Available, it has been spelt "avaiable"

**Comment by Robotia** [comment]
Oh >.< @Yive

**Comment by Yive** [comment]
I didn't write it like that :laughing:

**Comment by Robotia** [comment]
Meh
