### ISSUE TITLE
[Crash] Thermos #28 - java.lang.NullPointerException: Exception in server tick loop

### ISSUE THREAD

**Issue by linkinkov** [TCPR/Thermos#151]
How i understand crash with hats.
http://pastebin.com/Nga1JbZD

**Comment by Robotia** [comment]
This doesn't seem to be Thermos' fault o.o have you tried vanilla forge?

**Comment by Esctogrillo** [comment]
I'm getting Exception in server tick loop too:
http://pastebin.com/NfmZQYji

**Comment by Robotia** [comment]
@Esctogrillo ok that I can fix.

**Comment by Robotia** [comment]
@linkinkov are you still facing this issue?

**Comment by Robotia** [comment]
Likely not Thermos' fault and no response for 22 days, assuming resolved.
