### ISSUE TITLE
[Proposal] Put the proper version of Thermos in /version

### ISSUE THREAD

**Issue by Tencao** [TCPR/Thermos#152]
Right now it's extremely hard to determine exactly what version we're running once the file name is changed (something I and most likely many others do to prevent script changes). I recommend readding the version string similar to KCauldron, but obviously for Thermos instead.

**Comment by Robotia** [comment]
Where are you expecting the version string to be found? I'm not sure how that's incorporated with KCauldron.

**Comment by Yive** [comment]
It _Should_ be fixed now.
