### ISSUE TITLE
[Todo] Start from the begining of KCauldron

### ISSUE THREAD

**Issue by Robotia** [TCPR/Thermos#153]
@spannerman79 suggested that I restart Thermos production from KCauldron 152. I am considering instead going through all of KCauldron commits and stripping the faulty ones that have allowed for greater parallelism and may have created "strange dupe issues".

**Comment by spannerman79** [comment]
*awaiting hate mail* lol

**Comment by DraksterAU** [comment]
Not a bad idea @Robotia .... not the restart.. but stripping out the stuff that isn't necessary.
@spannerman79 your not hated :P

**Comment by MixSt** [comment]
I'm all for it. 152 is the most stable build of CKauldron with the minimum amount of bugs. All that after is hotfixes of fixes of bugfixes and questionable additions.

**Comment by spannerman79** [comment]
In fact awhile ago i released a build based off 152 with just forge updated and I never had this issue https://gitlab.prok.pw/KCauldron/KCauldron/issues/275

**Comment by iKaneki-Ken** [comment]
I'm all for this, I agree that B152 of (K)Cauldron was the most stable, hell, it might make it possible for you to revert some of the commits you've made that were "required" to fix brought on by builds of 153+.

**Comment by TerdyTheTerd** [comment]
Hmm, whatever gets the issues resolved with the least amount of stress to those who are trying to fix them, really wish I could help out in more ways than donating and reporting/testing a few bugs :/

**Comment by spannerman79** [comment]
Well @TerdyTheTerd once @Robotia (hint hint) gets the wiki type system that I suggested via discord sorted you can do docs

**Comment by bookerthegeek** [comment]
If you like, give me the docs and I'll clean them up nice like for the github wiki till we have a better place for them.

**Comment by Robotia** [comment]
Some of this has been fulfilled, likely the rest will not be possible in near future.
