### ISSUE TITLE
B31 - Random chunks stop doing anything with various mods

### ISSUE THREAD

**Issue by DraksterAU** [TCPR/Thermos#154]
Hi There

Testing out B31 for you @Robotia and I found that a lot of mod items would stop performing, such as cables (Mekanism), liquid/item transfer pipes (BC) and Stargates (SGCraft) whenever a chunk didn't have a player nearby. 

This is highly unusual... it causes stargates which normally chunk-load to fail to disconnect until an admin manually visits the area with /tp and cables/pipes to do nothing.

**Comment by iKaneki-Ken** [comment]
This isn't Thermos' doing. This is base Cauldron doing that. Check out tile-entities.yml.

**Comment by DraksterAU** [comment]
@ikaneki-ken this does not occur in build 28. Sorry mate your wrong.

**Comment by Robotia** [comment]
Probably due to is active caching

**Comment by Robotia** [comment]
Try raising the gc grace period to 3 in `cauldron.yml`?

**Comment by iKaneki-Ken** [comment]
I've tested many mods with Thermos 31 while allowing all tile entities to tick by setting `tick-no-players: true` for each Tile Entity tile, have never issues with Tile Entities ticking regardless though.

**Comment by DraksterAU** [comment]
I have no idea what you are taking about.

I shouldn't have to set tick no players to true and the problem is that tile entities are Not ticking when they are supposed to.

**Comment by DraksterAU** [comment]
Not only that, @tobotia released build 32 already to fix this ... No idea why your dragging conversation on
