### ISSUE TITLE
[Crash] Thermos 1614.31, 32/Mystcraft: Exception ticking world;  java.lang.NoSuchFieldError: field_73244_f

### ISSUE THREAD

**Issue by Masonrf** [TCPR/Thermos#155]
Well, After the previous crash I was having was fixed, Thermos now crashes on start with a different error seemingly related to Mystcraft.  I have attached a crash log and a startup log. 

Crash log:
[crash-2016-02-25_20.30.57-server.txt](https://github.com/TCPR/Thermos/files/147598/crash-2016-02-25_20.30.57-server.txt)

Startup log:
[latest.txt](https://github.com/TCPR/Thermos/files/147600/latest.txt)

**Comment by Masonrf** [comment]
Whoops, this is a duplicate of #134. Sorry!

**Comment by Robotia** [comment]
Don't sweat it :smile:
