### ISSUE TITLE
[Crash] Possible crash with AppleCore in b32

### ISSUE THREAD

**Issue by Dasfaust** [TCPR/Thermos#157]
Using `Thermos-1.7.10-1614.32-server-beta`, libraries downloaded from [release 31](https://github.com/TCPR/Thermos/releases/tag/31), [AppleCore 1.3.0](http://minecraft.curseforge.com/projects/applecore/files/2277393) (needed for SpiceOfLife, HungerOverhaul) the server launcher crashes with [this](http://puu.sh/nlP6N/2a0af7514f.log). Works in vanilla Forge 1614.

However AppleCore 1.1.0 seems to work just fine, but figured I'd submit the report anyways.

**Comment by Robotia** [comment]
Add `-noverify` to your server arguments
