### ISSUE TITLE
Hacked Clients List

### ISSUE THREAD

**Issue by SuperSandro2000** [TCPR/Thermos#158]
I hope this how you want to know hacked clients.

- Nodus
- Iridium
- Huznui
- Reflex
- Wolfram
- Metro
- Wurst
- WeepCraft
- Kryptonite

**Comment by xjboss** [comment]
Scenter

**Comment by Robotia** [comment]
Thanks guys!

**Comment by Cracks777** [comment]
AmbientOcclusion's XRay Mod

**Comment by Robotia** [comment]
Implementation will be done in ThermosAHC due to the limitations of server detection ability. Please post there instead.
