### ISSUE TITLE
-Noverify removal?

### ISSUE THREAD

**Issue by DraksterAU** [TCPR/Thermos#159]
Would be great for the noverify to be removed... just makes the whole thing seem buggy to users.

**Comment by Robotia** [comment]
Can't be in the near future, this requires an upgrade to special source which might not be possible

**Comment by DraksterAU** [comment]
Isnt it bad to do this though? 
noverify is literally telling java not to care about issues you introduced in B30 for "performance" increases...

**Comment by spannerman79** [comment]
No, I don't remember the exact details @DraksterAU but it has something to do with classes within java moving from 6 > 7 > 8.

And its a common issue for other java devs moving code from 6 > 7 > 8

**Comment by DraksterAU** [comment]
Why not just compile with 6 or 7 then, rather than have this happen? 
Seems like an unnecessary extra step is all.

**Comment by Robotia** [comment]
Read #141 . According to Oracle OpenJDK's past JSR proposals, there have been serious improvements in the source code from 6 to 8. There is a reason why this was done and it will not be reverted. `noverify` only chooses not to verify the class code, it does not hinder performance improvements
