### ISSUE TITLE
Error on load the server!

### ISSUE THREAD

**Issue by FabioZumbi12** [TCPR/Thermos#160]
## Issues

I having na error after load the plugin, because the system dont find a class.

This is the log: http://pastebin.com/phuV2Jq9

This is the version of Thermos: Thermos-1.7.10-1614.31-server-bleeding.jar
And the forge: forge-1.7.10-10.13.4.1614-1.7.10-universal.jar

Edit: This error is before load the dimensions!

**Comment by Robotia** [comment]
Use build 32, and I believe you are missing the kimagine library from your libraries folder
