### ISSUE TITLE
Reload command bug

### ISSUE THREAD

**Issue by xjboss** [TCPR/Thermos#162]
use** /cauldron reload** command later **thermos command** and **cauldron command** will not work

**Comment by Robotia** [comment]
@xjboss What build are you using?

**Comment by iKaneki-Ken** [comment]
Question, what exactly are you trying to achieve by using those commands?

**Comment by DraksterAU** [comment]
The reason why bloodmc stopped the reload command is the amount of work required to get forge mods to respect this.. prepare for your server to break.... unless Robo has really outdone him/herself.

**Comment by spannerman79** [comment]
Never reload and **never** use plugins like Plugman while using any Cauldron based server.  If you want to change a plugin - shutdown!

**Comment by Robotia** [comment]
Not an issue in 36.
