### ISSUE TITLE
[Crash] Thermos #28 then update to #32

### ISSUE THREAD

**Issue by linkinkov** [TCPR/Thermos#163]
http://pastebin.com/MtXi76yZ

**Comment by Robotia** [comment]
Read the 31 release notes, add -noverify to server arguments

**Comment by linkinkov** [comment]
Sorry for my mistake, dont see build before :)
Please close.

**Comment by Robotia** [comment]
Don't worry about it, I should've added it to the B32 release notes (which I have done now).
