### ISSUE TITLE
Chunkloaders do not work in b32.

### ISSUE THREAD

**Issue by DraksterAU** [TCPR/Thermos#164]
On a Thermos/KCauldron server, Launch controllers from galacticraft (when going between dimensions) do not chunkload anymore.
In addition to this, Admin Anchors from Railcraft fail to keep them active also... this makes me think thermos is not working with Chunk loaders at all... See the other post I mentioned before regarding stargates.

In addition to this, about 50% of the time the rocket vanishes and is never seen again..... even if you manually visit the destination.

**Lastly, this behaviour is also appearing in build 28 to some extent (a lot rarer)..... so it might have been a bug for a while but it is far worse now**

@radfast Something you might be interested in.
@Robotia Sorry to hound you mate ;)

**Comment by iKaneki-Ken** [comment]
This may not happen after the Thermos reboot. Robotia has managed to find the source code of base Cauldron, so he's working on revamping his dev environment.

**Comment by DraksterAU** [comment]
Cool.. it would be awesome to even just have Cauldron + Forge 1614 to be honest.

**Comment by radfast** [comment]
hi guys

The Galacticraft [LaunchController](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/planets/mars/tile/TileEntityLaunchController.java) uses [this code](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/world/ChunkLoadingCallback.java) to interface with ```ForgeChunkManager```.

We have not actually changed that code since Minecraft 1.6.4, but it works OK in plain Forge 1.7.10.

>  In addition to this, about 50% of the time the rocket vanishes and is never seen again..... even if you manually visit the destination.

@DraksterAU  this could just be a symptom of the chunk not being loaded.  I think most players / server owners do not realise how close to a chunk a player needs to be in order for it to be "fully" loaded, I mean with all entities and TileEntities active (loaded saved NBT data from the saved chunk in the world save file).  Generally you need to be standing within a 2 or 3 chunk radius.  You can test this with a vanilla furnace.

**Comment by radfast** [comment]
> Robotia has managed to find the source code of base Cauldron

Wow, that's major news.

**Comment by Robotia** [comment]
@DraksterAU Ensure that your `tileentities.yml` has the following values:

```
settings:
  skip-tileentity-ticks: false
  prevent-invalid-tileentity-updates: false
```

**Comment by DraksterAU** [comment]
@Robotia Ive done this, it changes nothing...

**Comment by DraksterAU** [comment]
@radfast I have coordinates set and teleport between launch pads.... I've even flown directly up but cant find the rockets.
Your right probably a side affect of the chunk not being loaded, _**but it shouldn't delete items....**_

**Comment by DraksterAU** [comment]
@Robotia This issue occurs for worlds that have no players on them.
Ive tested it with Railcraft carts that have a chunk loader as well as the furnace as @radfast suggested.

**For some reason worlds with chunkloaders do not chunk load unless there is a player present on the world somewhere.**

**Comment by Rubbertjuh** [comment]
@Robotia could you clarify why you have these settings in the Tile entities.yml ?

**Comment by DraksterAU** [comment]
I have tried them with and without those tile entity settings. No change.

**Comment by vadimyer** [comment]
Same issue here too =]

**Comment by iKaneki-Ken** [comment]
@Rubbertjuh Can you clarify what you mean by clarify? If you're asking why those settings even exist in tileentities.yml, it's because that's how BloodMC and his helpers coded it.

**Comment by DraksterAU** [comment]
I think he means why you want to set them the way robotia mentioned.

It lags the server ALOT

**Comment by iKaneki-Ken** [comment]
As well, I may have found out why chunk loaders aren't working for you.

> mods-railcraft-common-blocks-machine-alpha-TileAnchorPersonal:
>      tick-no-players: false
>      tick-interval: 1

Make sure to turn that to true, a commit Robotia made fixed a bug that made tileentities.yml ignore chunkloaders regardless to what you had this set to. I turned `tick-no-players` to `true` and it started working again.

**Comment by DraksterAU** [comment]
@iKaneki-Ken tile entities set to tick-no-players true always worked for me but only if there was *a* player in that dimension.

**Comment by Robotia** [comment]
You might want to try enabling load chunk on forge tick and load chunk on forge request
