### ISSUE TITLE
Items (such as StargateTech2's personal shield) no longer perform their functions

### ISSUE THREAD

**Issue by DraksterAU** [TCPR/Thermos#165]
Ive got several mods that are no longer able to intercept things like damage events after Build 28.

This also happened **after **KCauldron B185...

This is a real deal breaker for us, some of these items (such as the personal shield) are key for our stargate themed server.

**Comment by Robotia** [comment]
By cannot intercept damage events, do you mean that they bypass the armor?

**Comment by DraksterAU** [comment]
The armor is completely useless now... after b185 KCauldron.
An example is it drained its energy instead  of killing you when lava hurt you, and it doesn't do that anymore.

**Comment by DraksterAU** [comment]
@Robotia I believe this is related to this issue too https://gitlab.prok.pw/KCauldron/KCauldron/issues/388

**Comment by Robotia** [comment]
Can you give another example please, so I can better identify this? I believe it is related to #98 but not sure.

**Comment by Robotia** [comment]
Checked the code in ForgeHooks and the Personal Shield on the StargateTech2 GitHub myself, this should definitely be working in B45. ForgeHooks now knows how to cancel damage events properly. Closing.

**Comment by DraksterAU** [comment]
:dancer: If that's the case... back to Thermos I come!!! Thanks @Robotia :D
