### ISSUE TITLE
[Crash] OpenModularTurrets - java.lang.IndexOutOfBoundsException: Index: 5, Size: 0

### ISSUE THREAD

**Issue by Ksnz** [TCPR/Thermos#166]
I am having a problem with OpenModularTurrets and Thermos. Crash log: http://pastebin.com/hntYtn2m
What happens is https://github.com/OpenModularTurretsTeam/OpenModularTurrets/issues/197

Fix: https://github.com/TCPR/Thermos/commit/9b00e1f41070b199bd9a079945384e524ed2577a
didnt fix it

**Comment by DraksterAU** [comment]
Explain how to reproduce? I have no issues with the latest OpenModularTurrets and Thermos B32.

**Comment by Ksnz** [comment]
Press configure button in turretbase gui

**Comment by DraksterAU** [comment]
@ksnz Your not running thermos, or if you are its out of date. The server version still references KCauldron and doesn't mention thermos in your report.

Also I had this issue after using prism to rollback.... Breaking and re-placing the item fixed it.
It was only happening After a Bukkit plugin placed it. 

Please post a mod and plugin list, as well as what build of thermos you are using?

**Comment by Ksnz** [comment]
I found out that ProtocolLib causes crash. :C

**Comment by Robotia** [comment]
So this is an incompatibility with ProtocolLib?

**Comment by Ksnz** [comment]
Sorry, it's https://github.com/Shevchik/ModFixNG causes crash :D 
When update player armor slots
`NMSUtilsAccess.getNMSUtils().updateSlot(player, 5, player.getInventory().getHelmet());`

`@Override`
`public void updateSlot(org.bukkit.entity.Player p, int slot, org.bukkit.inventory.ItemStack item) {`
		`CraftPlayer cplayer = (CraftPlayer) p;`
		`EntityPlayer nmshuman = cplayer.getHandle();`
		`nmshuman.playerConnection.sendPacket(new PacketPlayOutSetSlot(0, slot,` `CraftItemStack.asNMSCopy(item)));`
	`}`

**Comment by Robotia** [comment]
Oh

**Comment by DraksterAU** [comment]
@Ksnz I run protocollib also. The latest versions don't work as they're for 1.8+

No hacks or workarounds needed.. Just use the one advertised for forge/cauldron
