### ISSUE TITLE
[Crash] Thermos #32 - cpw.mods.fml.common.LoaderException: java.lang.VerifyError: Inconsistent stackmap frames at branch target 20

### ISSUE THREAD

**Issue by lurquhar1221** [TCPR/Thermos#167]
I am having a problem with Thermos Build 32. Crash log: [http://pastebin.com/raw/FKk1bncx](http://pastebin.com/raw/FKk1bncx).

I have tested this with Vanilla. It worked perfectly fine.

**Comment by Robotia** [comment]
Read the release notes for BL31, add `-noverify` to the server arguments.
