### ISSUE TITLE
[Conversation] Thermos Server Lag Reduction

### ISSUE THREAD

**Issue by linkinkov** [TCPR/Thermos#169]
Its not a issues, just want to talk with server owners, that they use for optimizing their server.
For example i have server with online 100+ and restart server every 12 hours (rtoolkit), but anyway have low tps. 

I can post my config or mod list. Just want to find all information of optimizatons :)
Lets talk about it :3

**Comment by Robotia** [comment]
WarmRoast?

**Comment by iKaneki-Ken** [comment]
Firstly, never ever leave a server open for 12 hours. 6 hours tops, but that's pushing it.

**Comment by linkinkov** [comment]
@Robotia warmroast just say me about overloaded tick entities. EntityWatch or ClearLagg dont clear all propertly.

@iKaneki-Ken why not? GC so bad works?

**Comment by vadimyer** [comment]
Given that, I got 50-60 average people online, 70+ mods, Thermos 28 (going to upgrade to the latest soon), at peaks TPS is somewhere between 15-16. That's after 8+ hours online, restarting the server doesn't really help with TPS, but it **only seems** to help with some weird bugs like when a player is teleporting somewhere and then back, in result he gets either dupe or loss of blocks on ground/inventory items. Maybe anyone else experienced that?

**Comment by Robotia** [comment]
@vadimyer It's from the KCauldron teleportation code, sorry :cry: I am working on reverting it to the Cauldron style right now.

**Comment by vadimyer** [comment]
@Robotia Oh great to hear! If you could mention the fix in change log later, will be much appreciated.

**Comment by linkinkov** [comment]
@Robotia why Tick Dynamic does not work with Thermos?

**Comment by DraksterAU** [comment]
@Robotia Awesome man... The Cauldron teleportation code had no weird shit happen.... With KC plugins will teleport you 100 blocks away from where you want to go ... :/

**Comment by Robotia** [comment]
@nallar

**Comment by iKaneki-Ken** [comment]
That's because Cauldron was maintained by multiple highly skilled Java developers, whereas KCauldron is maintained by one and I don't know how knowledgable of Java Prototiks is.

**Comment by DraksterAU** [comment]
He seems very inadept at finding out why something was done before him and just undoes things that bloodmc did... for very good reason.
He might be good at java, but he doesn't understand how to pick up a project left by someone else.

**Comment by iKaneki-Ken** [comment]
@DraksterAU One of his good reasons also severely reduce performance of Cauldron.

**Comment by DraksterAU** [comment]
I'd rather a slower server that runs. Sorry, that's just me XD

**Comment by spannerman79** [comment]
I **never** exceed an uptime of 6 hours with *any* cauldron based server.  For vanilla forge i never got above 4 hours before a restart.

**Comment by DraksterAU** [comment]
I'm talking about the crashes and broken functionality @spannerman79 not the uptime. I agree.

**Comment by spannerman79** [comment]
> For example i have server with online 100+ and restart server every 12 hours (rtoolkit), but anyway have low tps.

For one, drop down to 64 slots.

Secondly change restart time to 6 hours **min**.

Thirdly - tweak your java exec switches.  There is no guide as each mod requires different java requirements and the permutations to go into tweaking for modded minecraft is endless.

In other words - get to work :stuck_out_tongue:

**Comment by linkinkov** [comment]
I cant drop down slots, today will change restart time.
http://f6.s.qip.ru/15RJco3Hx.png that i have now on magic server with 100+ online.
on this server i use your build of KC @spannerman79, but on industrial servers tps lower.

**Comment by Robotia** [comment]
No new posts for over 21 days.
