### ISSUE TITLE
Ars magica .007 will not save player levels when they leave

### ISSUE THREAD

**Issue by djoveryde** [TCPR/Thermos#170]
For some reason ever since switching to thermos whatever players do to their ars magica level it is lost as soon as they log off. I'm running the latest ars magica version and the recent stable release of thermos.

**Comment by iKaneki-Ken** [comment]
Are you using BungeeCord?

**Comment by djoveryde** [comment]
Nope thermos only no bungee at all. I do have multiverse installed though

**Comment by Robotia** [comment]
This is likely a problem with "ReverseCloner" for player teleportation/respawning.

**Comment by bookerthegeek** [comment]
Also update ars magica, you ate running a few versions behind.

**Comment by djoveryde** [comment]
Appologies got the wrong version of ars it's 1.7.10_AM2-1.4.0.008.
Couldn't find any newer version than that one for 1.7.10?

**Comment by NEXUS2345** [comment]
@djoveryde there has been a significant bug fixing update done by the AM2 community, and released by Mithion, here: http://minecraft.curseforge.com/projects/ars-magica-2/files/2280862

**Comment by djoveryde** [comment]
Brilliant its working. Thankyou @NEXUS2345 didnt see that update sneak in ;)
