### ISSUE TITLE
[Proposal] Add protection from Titanium Cheats / Nodus

### ISSUE THREAD

**Issue by vadimyer** [TCPR/Thermos#171]
I guess this is as it is.
By the way, how does the hacked client detection works right now?

**Comment by Robotia** [comment]
Right now it can only detect hacked client mods. https://github.com/TCPR/ThermosAHC is intended to advance this capability to another level. It would have to be a mod installed both on the client and the server

**Comment by vadimyer** [comment]
Great mod. Any ETA for this?

**Comment by DraksterAU** [comment]
Is there any reason you need this?

Both Towny and factions support custom chests... They just need to have the item ids In config

**Comment by vadimyer** [comment]
I'm not familiar with Java ._. But things like Titanium cheats seem to inject into the client and allow for certain cheats (x-ray, speedhack, wallhack, etc.). Seems like ThermosAHC would solve this problem?

**Comment by Robotia** [comment]
In theory yes, we would have to get the creators of the pack (lucky if you are the creator yourself) to add it for the client-side as well.

**Comment by vadimyer** [comment]
I would help to test this, for sure.

**Comment by DraksterAU** [comment]
Oh my bad I read that as you couldn't protect modded chests

**Comment by Robotia** [comment]
Implementation will be done in ThermosAHC due to the limitations of server detection ability. Please post there instead.
