### ISSUE TITLE
Warp Drive 1.7.10 mod frequency issue

### ISSUE THREAD

**Issue by djoveryde** [TCPR/Thermos#173]
I have an issue with the "warp drive" mod. In single player the cameras work fine on all frequencies.
Server side they fail to work. All you get is "invalid frequency".

**Comment by Robotia** [comment]
I can't really do anything about this without knowing how the frequencies work. :/

**Comment by djoveryde** [comment]
Cameras registry for dimension 0: 

Thats all console says, was hoping to see more :-/

**Comment by LemADEC** [comment]
What version of WarpDrive are you using?

**Comment by Robotia** [comment]
@LemADEC I remember you! Didn't you run that server for Pyrostasis?

**Comment by LemADEC** [comment]
and I also maintain the WarpDrive mod :)

**Comment by Robotia** [comment]
Je suis désolé, je n'aime pas quand les serveurs fait ça.

**Comment by LemADEC** [comment]
Not quite sure to get that one, lol

**Comment by Robotia** [comment]
@LemADEC ? Est-ce que tu n'est pas français?

**Comment by LemADEC** [comment]
Si je suis Français, mais ta phrase est ambigue

**Comment by Robotia** [comment]
Oh. Je n'aime pas quand les individuels comme <<Pyrostasis>> disent <<Ooh, je suis un operateur, je vais examiner le chez qui je vais faire de raid>>

**Comment by LemADEC** [comment]
Je n'ai pas souvenir qu'il est fait cela en stream ou video.
Enfin, je ne compte pas les bases tricheur, ça c'est une autre histoire ;).

**Comment by Robotia** [comment]
Je crois que vous n'etes pas comme lui, bien sur. J'espère que ca n'aura pas d'impact sur nos conversations. (Je suis desole j'ai un clavier americain et je sais seulement un peu de francais)

**Comment by LemADEC** [comment]
:)

**Comment by djoveryde** [comment]
WarpDrive-1.7.10-1.3.18.-

**Comment by LemADEC** [comment]
Frequencies are working on WarpDrive-1.7.10-1.3.17 with Highlands-1.7.2-v-2.2.3 + ATG-1.7.10-0.12.0 .
Are you able to reproduce without using ComputerCraft, just using the tuning rodes?

**Comment by LemADEC** [comment]
Frequencies are working on WarpDrive-1.7.10-1.3.17 with Thermos-1.7.10-1614.32. You probably have another mod interfering here, or have an older version of Thermos.

**Comment by djoveryde** [comment]
I'm using the stable 22 version of thermos. Other mods I use are advanced solar panels, applied energistics 2, build craft, computercraft, galacticraft, industrialcraft2, matter overdrive, Mekanism, nei, thermal expansion/dynamics, open modular turrets and waila.
Tuning forks don't work either :-/

**Comment by LemADEC** [comment]
Upgrade Thermos to 32, there's lots of outstanding issues fixed since 22.

**Comment by djoveryde** [comment]
Is 32 stable enough? As its not being deemed stable currently? I dont mind providing it dont break the world lol

**Comment by Robotia** [comment]
Read the release notes: `NOTE: This build is considered to be relatively stable, but is still beta due to the addition of hacked client detection.`

**Comment by djoveryde** [comment]
Ok loaded in 32. Still not working, works fine in single player but fails in multiplayer :-/

**Comment by LemADEC** [comment]
ok, start removing mods, you've a conflict somewhere.

**Comment by djoveryde** [comment]
As a question wouldn't it affect single player also if it was a mod?

**Comment by LemADEC** [comment]
I wish it was that simple :)

**Comment by djoveryde** [comment]
Ok Tested with the following:

Thermos-1.7.10-1614.32-server-beta.jar

Mods:

ComputerCraft1.75
Industrialcraft-2-2.2.815-experimental
WarpDrive-1.7.10-1.3.18

Plugins: NONE

Same issue "Laser + Camera: Beam Frequency -1 in invalid! Video Channel 100 is invalid (using tuning fork)

**Comment by djoveryde** [comment]
Ok, retried on the multiplayer side. Got the Beam working fine (was a mistake) however video still says invalid. Yet it does work via the monitor so something isnt working correctly somewhere in the code as its effectively giving a false negative

![0f728246d4fc18929369d7f33a008dad6f4fc3451c9635db0b pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/8558407/13401345/aad6dd18-df03-11e5-817c-c918e00da703.jpg)

**Comment by LemADEC** [comment]
The Laser + Camera will always report 'invalid' for its Video channel in SMP. It's a bug in the WarpDrive mod. Thermos has no issue here.

**Comment by djoveryde** [comment]
Ok will this be fixed warp drive mod end?

**Comment by LemADEC** [comment]
It's already fixed in dev :)
