### ISSUE TITLE
Timeout too short for "Decoration took too long!"

### ISSUE THREAD

**Issue by LemADEC** [TCPR/Thermos#174]
A new exception "Decoration took too long!" was added recently here: https://github.com/TCPR/Thermos/blob/master/patches/net/minecraft/world/biome/BiomeDecorator.java.patch#L41

The actual timeout trigger can't be configured and appears to be a bit too low (our server triggers it every ~10k chunks generated as of Thermos-1.7.10-1614.32).

**Comment by Robotia** [comment]
Decoration should never take that long, but I can add a configuration setting

**Comment by LemADEC** [comment]
Decoration takes longer because it frequently create new chunks in cascade, typically with structure placement, neighborhood checking, early mob spawning (pathfinder AI), etc.
It would be interesting to detect such cascading chunk generation and stop them past a certain distance from original chunk. It would be closer to the actual issue and allow for a nicer handling than server crash, hopefully.

**Comment by spannerman79** [comment]
Personally, I've noticed if mods hook into village gen it does cause cascade chunk gen.  The more mods that hook into village gen the greater the cascade and higher the chance the server stalls.

This is why I wished **all** mods had the option of disabling village gen integration unlike a certain other mod (don't know about yours @LemADEC - never used it - so not directed at you)

**Comment by Robotia** [comment]
Fulfilled by raising the timeout time to 10 seconds. A custom setting would create pointless clutter IMO.
