### ISSUE TITLE
Caused by: java.lang.VerifyError: Inconsistent stackmap frames at branch target 10

### ISSUE THREAD

**Issue by cuddylier** [TCPR/Thermos#176]
Hi

My server with Thermos-1.7.10-1558.32 is crashing on startup with this error: http://pastebin.com/raw/g20iBtT8

I'm using these files: http://sh.st/st/40260a458161ce19c15c6bc46ebe3bd6/http://tcpr.ca/files/thermos/Thermos-1.7.10-1558.32.zip

**Comment by Robotia** [comment]
`-noverify` must be added to your server startup arguments
