### ISSUE TITLE
Build 32 worldguard error

### ISSUE THREAD

**Issue by djoveryde** [TCPR/Thermos#178]
When the server is loading this error comes up. Not sure if it is significant?
ERROR Plugin WorldGuard v6.1 has failed to register events for class com.sk89q.worldguard.bukkit.listener.EventAbstractionListener$SpigotCompatListener because org/bukkit/event/player/PlayerInteractAtEntityEvent does not exist.

**Comment by Robotia** [comment]
That's a Bukkit 1.8 event I believe, so no it's not important.

**Comment by iKaneki-Ken** [comment]
Downgrade to WorldGuard 6, otherwise you'll get that error spamming your console, because as Robotia said, it's a 1.8.* event and can cause WorldGuard to perform badly.
