### ISSUE TITLE
[Crash] Horizontal Glass Panes mod crash on thermos build 32

### ISSUE THREAD

**Issue by vrackfall** [TCPR/Thermos#179]
I'm getting a problem with [Horizontal Glass Panes](http://www.curse.com/mc-mods/minecraft/227706) and Thermos build 32 (Not in the older builds, not tested in build 31). Crash log: http://pastebin.com/s7bsRqEd. 
What happens is the game is crashing.
Please fix it.
Thanks

**Comment by LemADEC** [comment]
Your logs are incomplete. You're probably missing a library or use an older version of Java.

**Comment by vrackfall** [comment]
I know my log is incomplete, I just removed the mods list because I don't wan't to show it, that's it

**Comment by LemADEC** [comment]
We can't help you with missing logs.
If you don't want to show the mods, you'll have to reproduce with a simpler setup of just a couple mods.

**Comment by vrackfall** [comment]
Ok

**Comment by iKaneki-Ken** [comment]
You're not missing a library file, you're using an outdated set of libraries. Download the libraries from B32 of Thermos.

**Comment by Robotia** [comment]
Use https://github.com/TCPR/ThermosServer/archive/master.zip for the latest libraries from the setup.

**Comment by vrackfall** [comment]
Ok, thanks

**Comment by vrackfall** [comment]
Is it these two folders : "lib" and "libraries" ?

**Comment by Robotia** [comment]
yup

**Comment by vrackfall** [comment]
So it's again crashed (I'm now using the good libraries).
Please re-open that. My new crash-log : http://pastebin.com/Ef0Bx3Vm

**Comment by vrackfall** [comment]
^^

**Comment by Robotia** [comment]
Try using these libraries. https://github.com/TCPR/Thermos/releases/download/31/Thermos-1.7.10-1614.31-libraries.zip

**Comment by vrackfall** [comment]
Are you sure that's an library problem ?

**Comment by Robotia** [comment]
It is definitely a library problem, that's why it says `ClassNotFound`

**Comment by Robotia** [comment]
And you're on version Thermos Version: ca.tcpr:Thermos:1.7.10-1614.27

**Comment by vrackfall** [comment]
Ok thanks, I think that's a prolem mwith the choosen version in multicraft (I'm using multicraft).
The build 27 is the first build I put in it.

**Comment by spannerman79** [comment]
> I know my log is incomplete, I just removed the mods list because I don't wan't to show it, that's it.

Personally - who cares what mods you are running.  You ask for help yet for all you know it could be a specific mod issue.

**Comment by vrackfall** [comment]
Now it's working
