### ISSUE TITLE
Ruins mod compatibility: EntityEvent.EnteringChunk?

### ISSUE THREAD

**Issue by LemADEC** [TCPR/Thermos#180]
As per https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/issues/42#issuecomment-189935006 , Ruins command blocks aren't working.
According to AtomicStryker, they are dependent on the EntityEvent.EnteringChunk.

From what I've tested so far, this issue is reproduced on both KCauldron (build 200) and Thermos (build 32).

**Comment by Bogdan-G** [comment]
also and FFoKC?

**Comment by NEXUS2345** [comment]
Have you tried build 32?

**Comment by LemADEC** [comment]
Update original post, issue is reproduced on Thermos build 32.

**Comment by LemADEC** [comment]
What's special about FFoKC?

**Comment by Bogdan-G** [comment]
@LemADEC it also reproduces your problem?

**Comment by LemADEC** [comment]
No idea if it works, my servers are all taken for the next couple days.
I wanted to understand what's different between FFoKC that makes it 'better' than KCauldron on Thermos.

**Comment by Bogdan-G** [comment]
@LemADEC no better or worse versions of the core, they are just different with different problems.

**Comment by LemADEC** [comment]
Thanks!

**Comment by Robotia** [comment]
:smiley:
