### ISSUE TITLE
[Fail to start] A problem occurred running the Server Launcher

### ISSUE THREAD

**Issue by Cuppycake** [TCPR/Thermos#181]
Server fails to start - Thermos build 1614.32

To me this looked like the same error you get when running Kcauldron with standard mobiuscore.jar

http://pastebin.com/GwZuixfH

**Comment by Cracks777** [comment]
yes opis is totaly broken with the new builds, if you remove it it will start.

**Comment by iKaneki-Ken** [comment]
Opis isn't the problem, MobiusCore is the one that is causing the issue. It should be fixed when Cauldron gets started from scratch without KCauldrons commits added.

**Comment by Cuppycake** [comment]
Yeah but I'm not using Opis on the server, other ProfMobius mods though. Didn't know if there was some sort of patched mobius core floating around for thermos. 

I'll keep an eye out for update.

**Comment by Razorskills** [comment]
I thought Opis was the only mod that has a dependency on MobiusCore. His other mods should run fine by themselves.. Try taking it out and see what happens when you launch?

**Comment by Cuppycake** [comment]
Same outcome even without mobiuscore. thanks for that reminder though. MC has been in my pack so long I completely forgot that only opis depends on it.

**Comment by Cuppycake** [comment]
This was simply me rushing things. Sorry about that. Forgot
`-noverify`

in my arguments >.>
