### ISSUE TITLE
[Not Thermos' Fault] [Thread Sleep?] Server gets stuck on loading dimensions

### ISSUE THREAD

**Issue by Mickimoo2** [TCPR/Thermos#183]
Basically your template doesn't help with this issue xD

It happens on both KC and Thermos, and I am hoping that you could help.

Log: https://gist.github.com/Mickimoo2/ec6d2175975a0bae4da9

Warmroast: http://i.imgur.com/FGFjy3o.png

The server eventually started and I have no idea when since when I went to do the warmroast it was up.

If you need anything else, let me know :+1:

**Comment by NEXUS2345** [comment]
Download Sampler from sfPlayer here: http://files.player.to/sampler-1.59.jar and install it in your mods folder.
It will generate something called a stall report when the server freezes for a certain amount of time. Once one is produced, please post the contents here so we can assist you.

**Comment by Mickimoo2** [comment]
It seems that it isn't stalling the way you think it is.

I put sampler in and started the server at about 7am this morning, it is now 1:45pm and it has in that time only loaded a few dimensions.

Log: https://gist.github.com/Mickimoo2/4bcbbb0d135734b3a1bb

**Comment by Robotia** [comment]
Try removing all server arguments and seeing if it runs

**Comment by Mickimoo2** [comment]
I need to allocate ram still, right? Otherwise it will run out of memory

**Comment by Robotia** [comment]
No it should automatically resize, you can still allocate though

**Comment by Bogdan-G** [comment]
vanilla feature?

**Comment by Mickimoo2** [comment]
Stall report:
https://gist.github.com/Mickimoo2/fcaef8469bc4e2f3210a

@Robotia Removed all tweaks and it still had the same issue.

**Comment by Robotia** [comment]
`at org.wyldmods.simpleachievements.common.data.DataManager.loadMap(DataManager.java:180)`
SimplyAchievements mod is at fault, not Thermos.

**Comment by Mickimoo2** [comment]
what is the best route to fix it?

**Comment by Robotia** [comment]
```java
    @SuppressWarnings("serial")
    private static Map<String, DataHandler> loadMap(File file) throws FileNotFoundException
    {
        String json = "";

        Scanner scan = new Scanner(file);
        while (scan.hasNextLine())
        {
            json += scan.nextLine() + "\n";
        }
        scan.close();

        Map<String, DataHandler> ret = dataReader.fromJson(json, new TypeToken<Map<String, DataHandler>>(){}.getType());
        return ret == null ? new HashMap<String, DataHandler>() : ret;
    }
```

The mod creator has implemented inefficient code, you will need to contact him. @wyldmods

**Comment by Robotia** [comment]
Not a Thermos-related issue, no new information for 2 weeks.
