### ISSUE TITLE
[Crash] HxC-Core - Crash when modifying chat message.

### ISSUE THREAD

**Issue by karelmikie3** [TCPR/Thermos#188]
Hello I am one of the developers of the HxCKDMS team. We recently had a crash reported, the user was using your server-version. I tested and it seems like us using ServerChatEvent to change the event.component to a new ChatComponentTranslation disconnects the player from the server.

To test the bug I used version: 1614.33 of Thermos.
Used this jar of my mod: http://puu.sh/nrg6d.jar
And here's the fml-server-latest.log: https://gist.github.com/karelmikie3/ea4904703c88c08381ab
I don't think the fml log is of use though since I don't see any errors in it related to the crash.

Here is the issue report we received: https://github.com/HxCKDMS/HxCEnchants/issues/48

**Comment by Robotia** [comment]
Fixed in BL34

**Comment by DrZed** [comment]
Thank you sir!

**Comment by Robotia** [comment]
:sunglasses: no problem
