### ISSUE TITLE
Chunk Gen is broken badly

### ISSUE THREAD

**Issue by Cracks777** [TCPR/Thermos#189]
Using version 34 fresh install of all files chunks generate all messed up.

https://youtu.be/asPZwvbR_UI

**Comment by Cracks777** [comment]
h

**Comment by Robotia** [comment]
Hmm...I don't think I missed anything in the reversion but I will see

**Comment by ajthemacboy** [comment]
You didn't have a pre-existing world folder did you? Just making sure.

**Comment by Cracks777** [comment]
nope

**Comment by ajthemacboy** [comment]
Perhaps the seed isn't being persisent?

**Comment by Cracks777** [comment]
idk,every world i make is the same way

**Comment by Robotia** [comment]
Try replacing the server jar with an earlier one like 31, see if it is the same?

**Comment by Cracks777** [comment]
ok testing

**Comment by Cracks777** [comment]
no problems in build 31, just tested

**Comment by Robotia** [comment]
Check B35 @Cracks777 ?

**Comment by Cracks777** [comment]
Yes this is fixed in build 35, Thank you so much for your hard work.

**Comment by NoOneNo** [comment]
i am seeing this in build 55-and 56 again, to reproduce make a new world, chunks are all messed up.
