### ISSUE TITLE
[Bug] Rails dupe

### ISSUE THREAD

**Issue by TheAndrey** [TCPR/Thermos#191]
Rails dupe with the help of pistons works on both KCauldron and Thermos.

![2016-03-02_00 39 21](https://cloud.githubusercontent.com/assets/6772452/13444667/2ec0327a-e010-11e5-9107-68069d067bf8.png)
![2016-03-02_00 39 07](https://cloud.githubusercontent.com/assets/6772452/13444666/2e978780-e010-11e5-9098-2a7063d95fac.png)

Or video: https://www.youtube.com/watch?v=ZtoE6GGgGPQ

**Comment by spannerman79** [comment]
This happens on a vanilla forge server.

So no, not a fault of Cauldron or any Cauldron based builds

**Comment by TheAndrey** [comment]
@spannerman79, dupe fix still more important than the detectors cheat clients that can be bypassed.

**Comment by spannerman79** [comment]
NoCheatPlus, Craft book etc have options to stop this dupe.

So again - this is an actual minecraft issue. Not the fault of Cauldron or any Cauldron based builds

**Comment by Robotia** [comment]
0.o

**Comment by Robotia** [comment]
@TheAndrey You know Java yes? Make pull request for idea?

**Comment by Robotia** [comment]
@TheAndrey fixed in BL35

**Comment by TheAndrey** [comment]
@Robotia It is a crutch to solve the problem. :-1:

**Comment by Robotia** [comment]
@TheAndrey that's why I ask you to make PR for what you think problem is. I do not know why it happens

**Comment by TheAndrey** [comment]
@Robotia workaround, anti-pattern I mean.

**Comment by Robotia** [comment]
I know that, I am asking you to help fix the problem
