### ISSUE TITLE
Which version of Opis and MobiusCore should I use ?

### ISSUE THREAD

**Issue by vrackfall** [TCPR/Thermos#193]
Hi,
Just for know, wich version of MobiusCore and Opis should I use to it's work with the last Thermos version ?
Thanks

**Comment by DraksterAU** [comment]
https://github.com/TCPR/Fixes has a few jars you can try...

**Comment by vrackfall** [comment]
I tried the MobiusCore-1.2.5-KC3.jar but it's crash so  I think it will do the sme thing for the other version

**Comment by iKaneki-Ken** [comment]
MobiusCore doesn't work at all on Thermos right now.

**Comment by Robotia** [comment]
Opis should work, but I will need a crash log from MobiusCore to investigate compatibility issues, please share one. :smile:

**Comment by vrackfall** [comment]
I think I cannot, the last time it's crashed for me, no crash reports was sent

**Comment by Robotia** [comment]
@vrackfall Ok, thanks. If there is no crash log, there should be either an hs_error.... or you can just give the latest server log with the mobius crash.

**Comment by tyler2k15** [comment]
On Build 35, the following work for Opis/Mobius Core

https://github.com/TCPR/Fixes/raw/master/MobiusCore/MobiusCore-1.2.5-KC.jar

http://minecraft.curseforge.com/projects/opis/files/2232520/download

**Comment by vrackfall** [comment]
Ok thanks

**Comment by vrackfall** [comment]
It's work, you can close this issue now
