### ISSUE TITLE
Crash during chunkgen with some seeds

### ISSUE THREAD

**Issue by ajthemacboy** [TCPR/Thermos#195]
I have a pretty strange problem here. I've experienced it on my Infinity server and my previous custom modpack server. Sometimes, when using a specific seed, the server will crash while preparing the spawn area.

Crash: https://gist.github.com/ajthemacboy/99f59e4e88aa2827b4c7

This can occur with the random seed created when there's no seed set in `server.properties`, and it can occur when a seed is specified. 

This crash **only** occurs when first generating the spawn chunks. After the spawn chunks are created, you can login and fly for hours without a crash.

This crash does not occur with vanilla Forge, and I've only tested it on Thermos. It occurs with the latest version, `1.7.10-1614.34`, and also on my custom modpack server which is now closed, an earlier version I don't remember.

Edit: I'm going out of town for a few days so I probably won't provide any input into this.

**Comment by Robotia** [comment]
I looked at this..it seems to be that the biome generator is null. This shouldn't happen, investigating

**Comment by Cracks777** [comment]
ive had lots of these errors on some seeds as the world first starts.

[06:20:27] [PaperSpigot - Lighting Thread/WARN]: Biome ID is out of bounds: 151372, defaulting to 0 (Ocean)

**Comment by Robotia** [comment]
Oh..disable async lighting in `spigot.yml`
