### ISSUE TITLE
[Bug] Server crashing on start

### ISSUE THREAD

**Issue by DigitalSniperz** [TCPR/Thermos#199]
**CRASH-REPORT:** http://pastebin.com/0v8CPRKK

**Server Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))* http://pastebin.com/Zx6UpRwr

**Explanation of issue:** Server crashes on start, see crash report at the bottom. 

**How to recreate this issue:** Download crundeecraft server zip, download latest thermos zip. Unzip both, launch the Thermos.jar using a bat or sh.

**Modpack Name:** *(Only if public)* CrundeeCraft

**Mods Installed:** 

**Plugins Installed:** None

**Warmroast Report:** *(Optional)*

**Thermos Version:** 1.7.10-1614.34

**Forge Version:** forge-1.7.10-10.13.4.1448-1.7.10

**Comment by Yive** [comment]
add -noverify to your startup script.

**Comment by Robotia** [comment]
Alternatively, use Beta 39.
