### ISSUE TITLE
[CRASH]server crashing ramdomly no pattern again

### ISSUE THREAD

**Issue by gafunbird007** [TCPR/Thermos#200]
Here is crashing report
 www.mc-baby.in.th/crash.txt

**Comment by Robotia** [comment]
Seems to be an issue with Entity Datawatcher values, investigating

**Comment by gafunbird007** [comment]
@robotia it happen with KC too I guess It might because of spigot.yml setting

**Comment by Robotia** [comment]
@gafunbird007 it is error that has easy fix

**Comment by Robotia** [comment]
Fixed in B40
