### ISSUE TITLE
[Bug] B42 - Permissions breaks after player death and chunks not loads sometimes.

### ISSUE THREAD

**Issue by Ghostlyr** [TCPR/Thermos#204]
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
Only one error:
```
[Server] WARN No Permissible injector found for your server implementation (while uninjecting for Ghostly!
```

**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
None errors.

**Explanation of issue:**
After player death he cant use any command and do anything what need bukkit permissions.
And sometimes nearest chunks unwilling to load, but sounds can be heard. TPS holding steady on 20.
All works fine with 32 thermos build or KCauldron B200.

**How to recreate this issue:**
Die.
Try use any command with permissions.

Regarding the the second bug - cases  randomly.

**Modpack Name:** *(Only if public)*
Not public.

**Mods Installed:**
Not matter.

**Plugins Installed:**
Any PermissionsEX version.

**Warmroast Report:** *(Optional)*

**Thermos Version:**
Build 42

**Comment by Robotia** [comment]
39 is fine, it seems 40 and up are half-broken. 43 will fix these problems hopefully

**Comment by Robotia** [comment]
39, once you die you need to relog

**Comment by Bogdan-G** [comment]
this bug has already been?

**Comment by Robotia** [comment]
Fixed in B44 once released.

**Comment by Ghostlyr** [comment]
:+1:
