### ISSUE TITLE
[Critical] Players complain about disappearance of blocks.

### ISSUE THREAD

**Issue by Ghostlyr** [TCPR/Thermos#205]
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
No errors in log.

**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
No errors too.

**Explanation of issue:**
These chunk-saving optimizations cause problems.. On my 4 servers players at a high online sometimes players complain about disappearance of some blocks in their regions. Occurs randomly, it may be disappear, may be replace to other block. Not matter vanilla block or modded.
Everything fine with KCauldron B200.
Have a plugin for logging item and block interaction but there are no have data. This is not greief, becouse happens with completely different mods. Similar mods only - bprskCore, CodeChickenCore, Treecapitator and IronChests.

**How to recreate this issue:**
I dont know.

**Modpack Name:** *(Only if public)*
Private.

**Mods Installed:**
Not matter.

**Plugins Installed:**
Use last autosaveworld for saving , but this not matter too.

**Warmroast Report:** *(Optional)*

**Thermos Version:**
Build 32. I cant use newer versions because are too buggy.

**Forge Version:**
1614...

**Comment by Robotia** [comment]
I don't know how to help you with this, it could be any number of things, such as the possibility that you have remove erroring tile entities enabled in forge.cfg :confused: 
Please try to find a root cause

**Comment by Ghostlyr** [comment]
Yes, removing erroring tileentities is enabled, but in logs i have not found any error reported on the removal. 

Dont know ho to find it alone... And dont want to check on production server and torture players...
I'm use KC the second day : none problems did not arise, when with Thermos get complains almost every few hours...

**Comment by Robotia** [comment]
Which blocks are disappearing?

**Comment by Ghostlyr** [comment]
Vanilla chests, chests from iron chests, chest for bees from forestry, safes from carpenters blocks, one of skeleton spawner has been replaced for pig spawner.

**Comment by Robotia** [comment]
So they just don't seem to be saved properly?

**Comment by Robotia** [comment]
@Ghostlyr please try to use B44.

**Comment by Isolonice** [comment]
@Ghostlyr I can confirm that B44 fix it
