### ISSUE TITLE
Scala update breaks mods

### ISSUE THREAD

**Issue by SuperSandro2000** [TCPR/Thermos#206]
The scala update breaks mods that are using scala/collection/Seq. Forge Microblocks and Ars Magica 2 are two examples.
Log: https://gist.github.com/SuperSandro2000/02d5d6a8d4c4545d0833

**Comment by Robotia** [comment]
http://www.scala-lang.org/api/current/#package
The scala API is the same, the Seq class is still included

**Comment by Robotia** [comment]
Did you use the latest libraries from the Thermos Server repository?

**Comment by SuperSandro2000** [comment]
Still the same after grabing the latest libraries.

**Comment by Robotia** [comment]
That is strange...I am using forge multipart as well...

**Comment by Robotia** [comment]
Micro blocks*

**Comment by SuperSandro2000** [comment]
It is crashing with only the latest versions of ForgeMultipart and CodeChickenLib, too.
It works in version 28 and is brocken in all version since build 30.

Multipart and microblock are pretty much the same.

**Comment by Time6628** [comment]
Redownload and reupload the latest libraries. That is what I had to :smile_cat:

**Comment by SuperSandro2000** [comment]
already redownlaoded them and still not working

**Comment by Robotia** [comment]
Do you have Discord? Please join so we can investigate this further.

**Comment by Robotia** [comment]
Where are you saving the libraries, there should be a folder called `libraries` in the directory of your server.

**Comment by Bogdan-G** [comment]
new library versions do not affect the crash, they are working on both the client and the server for more than six months.

**Comment by Robotia** [comment]
@SuperSandro2000 if you PM me on Discord I would be happy to personally take a look at your server and identify the problem.

**Comment by SuperSandro2000** [comment]
@Robotia I wrote you on discord.
@Bogdan-G I have no idea how to fo that and it wouldn't fix the problem

**Comment by Robotia** [comment]
Worked with @SuperSandro2000, turns out libraries were indeed outddated. Problem resolved.

**Comment by SuperSandro2000** [comment]
Could someone update these libraries https://github.com/TCPR/Fixes/raw/master/Thermos-Libraries/libraries.zip?

**Comment by Robotia** [comment]
Done
