### ISSUE TITLE
Slow world generation

### ISSUE THREAD

**Issue by cuddylier** [TCPR/Thermos#207]
Hi

World generation seems incredlbly slow for at least ATL Resonant Rise 3.3.0.1 (it took 10+ minutes on an older Thermos version, seems faster on the below version but still much slower than normal Forge).

I'm using Thermos-1.7.10-1614.34

**Comment by Robotia** [comment]
What kind of world generation? Do you have a WarmRoast profile?

This does not provide any information as to how I can solve this problem. The issue template is there for a reason, do not clear it out and put your own content. :confused:

**Comment by cuddylier** [comment]
I'm just using the recommended mods on the Resonant Rise installation, nothing custom, completely clean install. Not too sure whether I'd have a WarmRoast profile in that case.

level-type=DEFAULT

Not too sure if Resonant Rise has any world generator it sticks on top of that.

**Comment by Robotia** [comment]
It probably does, I really need a WarmRoast profile for this though.

**Comment by cuddylier** [comment]
Ah okay, you don't have the resources to do one I assume? I can look into trying to get one but haven't ever used warmroast before.

**Comment by Robotia** [comment]
It's not that I don't have the resources...I don't use the pack. I am primarily focused on fixing Thermos issues, not going through every pack and testing it myself. 

I understand that you are having a problem with world gen being slow, but I cannot help you without a WarmRoast profile log.

**Comment by Bogdan-G** [comment]
thermos slower than forge? What is it like? what a joke with modpack?

**Comment by DraksterAU** [comment]
Slow world generation doesn't cut it... I have a set of 80 mods which is (pretty standard for modded servers).... and I'm finding that If I move 200 blocks from spawn , it takes the server about 5 minutes to catch up.

That's a *fresh* server with no other players or worlds.

KCauldron Build 185 would be about 3 seconds of wait time.. same with Thermos 28.

**Comment by Robotia** [comment]
I need a WarmRoast profile, not an explanation of how it is a problem.

**Comment by djoveryde** [comment]
I had a similar issue and changed   timeout-time: 90 to   timeout-time: 900 in spigot.yml and it fixed the issue. 
Running Hexx Reloaded, new chunk generation working fine now. Make sure to use build 45+ of Thermos.

**Comment by Robotia** [comment]
Ok, so then the spigot thread is indeed problematic, will look into this

**Comment by Robotia** [comment]
No log was ever provided, I cannot help you with this without one. Closing.
