### ISSUE TITLE
Thermos not saving lighting

### ISSUE THREAD

**Issue by ajthemacboy** [TCPR/Thermos#208]
On my Infinity Evolved server (latest version) lighting isn't being saved. I have disabled async-lighting in spigot.yml and the error still occurs.

When you originally light up an area with torches, for example, it's fine, but when you leave and come back, lighting only goes a few blocks from the torches and cuts off in straight lines.

I cannot post a picture right now, but I can post one tomorrow if need be.

**Comment by Robotia** [comment]
Which build are you using? You need to use the issue template, don't get rid of it and put your own content.

**Comment by ajthemacboy** [comment]
Much of the template was not applicable, but here:

**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))* Not relevant, nothing mentioned

**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))* Not relevant, nothing mentioned

**Explanation of issue:** See first post

**How to recreate this issue:** Use Infinity 2.4.1 on `1.7.10-1614.34`

**Modpack Name:** *(Only if public)* FTB Infinity Evolved

**Mods Installed:** Modlist [here](http://ftbwiki.org/Feed_The_Beast_Infinity_Evolved)

**Plugins Installed:** `PermissionsEx, PlugMan, ConsoleScheduler, WorldBorder, OpenInv, Essentials, Prism, EssentialsChat`

**Warmroast Report:** *(Optional)*

**Thermos Version:** `1.7.10-1614.34`

**Forge Version:** 1614

**Comment by Robotia** [comment]
Please turn off `async-lighting` in `spigot.yml`, that should fix your issue.

Also, as a side note, let Player know that the Factorization packet skipping made sense if he had read the issue.

**Comment by ajthemacboy** [comment]
@Robotia As I already said, I have disabled async-lighting in spigot.yml and the issue persists.

**Comment by Robotia** [comment]
Are random light updates enabled?

**Comment by ajthemacboy** [comment]
No, should they be enabled?

**Comment by Robotia** [comment]
Normally no. I'm not sure why you are having lighting issues though, have you tried using 44?

You might want to try enabling it to see if it helps, however it does raise lag a bit.

**Comment by ajthemacboy** [comment]
Build 44 seems to have fixed things. I'll let you know if it happens again.

Thanks for your help!
