### ISSUE TITLE
[Suggestion] : Include libraries in server.jar that auto extract with new releases

### ISSUE THREAD

**Issue by DraksterAU** [TCPR/Thermos#209]
An idea... feel free to use your java wisdom to shoot me down I don't know if its a good one..

If you were to occasionally update libraries, would it be better to include these in the jar, then have Thermos itself extract them on startup if the files do not exist on the filesystem. If theyre already there, thermos would verify theyre the same file and move on.

Might increase startup times a little, but be worth it no?

That way you know that people will always have the appropriate libraries... it would become impossible not to.

**Comment by DraksterAU** [comment]
Eh this is a pointless  request.

**Comment by iKaneki-Ken** [comment]
I agree with you on this suggestion. It would decrease a lot, if not all tickets in regards to "My server is crashing", "Update your libraries".

**Comment by Robotia** [comment]
I know this is a problem, but it is not easy to auto-download the jars, they are fetched from maven repositories and catching a `ClassNotFoundException` is not that easy.
