### ISSUE TITLE
[Suggestion]: Two streams of thermos...

### ISSUE THREAD

**Issue by DraksterAU** [TCPR/Thermos#210]
Just an idea, but if you had two streams of Thermos it would be pretty awesome...

**Beta**
The Beta stream would contain up to the minute fixes and improvements that may very well be broken at the time of release. This is purely for people to test with.

**Stable** 
The Stable stream would be only fixes that have been thoroughly tested.... otherwise it would be pure cauldron code almost. Beta fixes could be migrated to this after a few weeks of being in the wild with no issues?

I'm finding (not sure about others) that its really hit and miss as to what version of KCauldron or Thermos works with any given plugin or mod.... mods that worked 20 versions ago (same level of forge) no longer work... and new ones do.

Just a suggestion.. but one that would be much appreciated.

- DraksterAU

**Comment by Robotia** [comment]
This would be great, but Yive and I are only two guys and only I know Java :/

If we had more developers, knowledge about github, and time it would be very possible.

**Comment by Robotia** [comment]
Not possible without more help, sorry.
