### ISSUE TITLE
[BUG] Fall damage

### ISSUE THREAD

**Issue by skushnarev** [TCPR/Thermos#212]
How to adjust damage on the server? Now damage from burning, floodings, falling, etc. as in vanilla. Or it is a bug?
 
Problem only on the server, in single everything is normal.

TFC 0.79.28.908
Forge client 10.13.4.1558-1.7.10
Thermos-1.7.10-1614.34-server OR Thermos-1.7.10-1614.44-beta-server

**Comment by Robotia** [comment]
I do not understand this question

**Comment by bookerthegeek** [comment]
I believe he ment to say "no" instead of "now".

**Comment by Robotia** [comment]
OH that actually explains everything. I think this is a bug on your end... 0.o

**Comment by skushnarev** [comment]
The problem of incorrect damage after a fall appears only on the server. In a single game everything is working correctly. The TFC on much more damage than vanilla.

Tested on different servers:
(V) Forge - damage correct.
(X) KCauldron - damage is not correct, as in the vanilla.
(X) Thermos - damage is not correct, as in the vanilla.

Sorry for the auto translation.

**Comment by Robotia** [comment]
Is TFC the pack name or armor?

Does the bug happen when your health is full after the fall?

**Comment by skushnarev** [comment]
TFC - Mod terrafirmacraft
http://terrafirmacraft.com/index.html

After a fall without any errors, or the server or the client.

**Comment by djoveryde** [comment]
Thermos-1.7.10-1614.45-beta-server, Hexx Reloaded Modpack.

Tested both Fall Damage and fire damage. Died from both with full health.
Cannot reproduce myself.

**Comment by Robotia** [comment]
I think it's due to incompatibility with some mod in the pack. :/

**Comment by djoveryde** [comment]
Ok checking with what he has set up it seems you do get fall damage and fire damage however the damage is so small and your regen is so fast that you heal it back pretty quickly.
Terrafirmacraft by default gives you 1000 health and regen to damage ratio in fire is 4 damage to 3 regen almost. Falling from a huge height only gives you around 80 damage. 

100% not Thermos, this is an OP issue within Terrafirmacraft in my honestly opinion.

But yes you do get damage, just not enough to die from thanks to TFC.

**Comment by skushnarev** [comment]
As I wrote above, this problem does not exist in a single game and the server with the original Forge. Only KCauldron and Thermos.

And on one of formuma wrote that a long time reported on this error Cauldron authors.

**Comment by Robotia** [comment]
@skushnarev it is only when you are wear armor? or also when wear nothing?

**Comment by djoveryde** [comment]
Ok Singleplayer Damage dealt in fire is 100 per tick.

Perhaps something within KCauldron is overwriting the vanilla damage?

This was with no armor at all

**Comment by skushnarev** [comment]
Without armor. It is easy to verify independently. But I will try to do for you a video that would be clear what the problem is.

**Comment by Robotia** [comment]
@skushnarev ok thank you :smile:

**Comment by djoveryde** [comment]
Forge (Fire Damage per Tick): 100
Thermos (Fire Damage per Tick): 5 (in lava), 1 (on fire)

**Comment by Robotia** [comment]
@djoveryde this happens before or after death?

**Comment by djoveryde** [comment]
@Robotia this is before death (walking into lava). After death and you come back your health is back to 1000.

Same issue for Fall damage, seems thats not using TFC's values of damage either.

**Comment by Robotia** [comment]
@djoveryde So the problem is due to the overriding of default health/damage behavior by TFC?

**Comment by djoveryde** [comment]
@Robotia Thats the only thing I can think of. Not sure how TFC fires its damage values but the way it outputs I would guess KCauldron had something in there that effectively overrides those values

**Comment by Robotia** [comment]
@djoveryde Ok, so correct me if I am wrong, the problem is this: the modpack TFC has its own custom damage values for things and Thermos does not obey them and instead inserts its own.

**Comment by djoveryde** [comment]
By the look of it yes. I've pulled the code for the EntityDamageHandler in TFC if that helps.
Unfortunately my understanding of java code is limited so im hoping it will help you :)

http://pastebin.com/DyyAj8g8

**Comment by Robotia** [comment]
Is TFC not open source?

**Comment by djoveryde** [comment]
Found it https://github.com/Deadrik/TFCraft

**Comment by skushnarev** [comment]
@Robotia That I do not know. But the author Bloxx, usually goes to the contact. And he answered me, if I find an error.

**Comment by skushnarev** [comment]
"In Cauldron was a problem.
The bottom line is that AttackEntityEvent event is not invoked. And the problem only on servers cauldron.
When the older versions Cauldron had a similar problem, then writer dashed hotfix.
The change was indicated as follows:
Fixed damageEntity not using onLivingHurt Forge hook result. Fixes TFC damage bug."


"У калдрона была такая проблема.
Суть в том, что событие AttackEntityEvent не вызывается. Причем проблема проявляется только на серверах cauldron.
Когда то в старых версиях колдрона была аналогичная проблема, тогда автор накатал hotfix.
В изменениях было указано следующее:
Fixed damageEntity not using onLivingHurt Forge hook result. Fixes TFC damage bug."

**Comment by Robotia** [comment]
@skushnarev ok that is helpful, will see what I can do

**Comment by Robotia** [comment]
@skushnarev Does the problem still persist in B54?

**Comment by skushnarev** [comment]
@Robotia I have not found a 54B, but try 51, 52, 53 and everything is working. It seemed to me that the damage is slightly smaller than the original, but it is necessary to check in detail what would be confident in their own words. But in general, I am very happy. Many thanks for the correction.
I found another problemmu, but it is not connected with this. I will create a separate topic later.

**Comment by Robotia** [comment]
So is this fixed?

**Comment by skushnarev** [comment]
@Robotia Yes. If I see that something is not working, I will inform you.
