### ISSUE TITLE
[BUG] Thermos, Kcauldron, Cauldron

### ISSUE THREAD

**Issue by linkinkov** [TCPR/Thermos#213]
**Explanation of issue:**
Video: https://www.youtube.com/watch?v=Yiis3pcpsAo (disable sound)
Player on video just add last part of wither, but its not own region.
Its also works with iron golem and cane (with cane need stand door)

**Plugins Installed:**
WG, WE but works with another plugins of privating land.

**Comment by linkinkov** [comment]
https://www.youtube.com/watch?v=0dYv7GsC0jU video of dupe cane

**Comment by linkinkov** [comment]
On russian forum some people say:
Its because onItemUse using early than events

**Comment by Robotia** [comment]
I have figured out the problem, it is very interesting. Block replacement does not revert drops that have occurred. Will fix soon.

**Comment by Utochk** [comment]
Fix doesn't work.
Thermos-1.7.10-1614.45
WG version: 6.1.1
Screenshots:
http://imgur.com/3QT6xsO
http://imgur.com/jxS9VPs
http://imgur.com/5HieLel

**Comment by Robotia** [comment]
@Utochk it fixes issues with sugar cane, not sure about the wither problem.

**Comment by linkinkov** [comment]
@robotia possible fix wither, golem dupe?

**Comment by Robotia** [comment]
Those are next on list

**Comment by Robotia** [comment]
Problem with Wither + Golem identified: Cauldron uses custom BlockStateListPopulator which fails to notify spawning mechanism if it has failed to set a block to air.

**Comment by TheAndrey** [comment]
@Robotia The problem arises from the fact that the BlockPlaceEvent is called too late. The call needs to be moved so that the event is called before the corresponding game mechanics.
If you block the action of using the PlayerInteractEvent, the game mechanics does not work.

**Comment by Robotia** [comment]
@TheAndrey From what I can tell, the Forge code is set up so that the Entity *must spawn first* before the block changes occur. In the interest of maintaining this format, the entity still spawns. 

However, I implemented a secondary check to see if the blocks from which it spawned were still present. If they are, the entity is instantly despawned.
