### ISSUE TITLE
Server Stalls

### ISSUE THREAD

**Issue by Time6628** [TCPR/Thermos#214]
**Server Log:** https://gist.github.com/Time6628/98816ee0821fe037c2f8

**Explanation of issue:** Server randomly stalls.

**Modpack Name:** *(Only if public)*

**Mods Installed:** atlauncher.com/pack/skyfactory

**Thermos Version:** 44

**Comment by Robotia** [comment]
`	at net.minecraft.world.World.func_72939_s(World.java:50532)`
50,532 is not a line in the source code, did you modify the stall log?

**Comment by Time6628** [comment]
Nope.

**Comment by linkinkov** [comment]
http://pastebin.com/cmfS8r2w - my stall report mean that have lose mysql connection?

**Comment by Robotia** [comment]
MySQL error with tekhode

**Comment by LemADEC** [comment]
Pex doesn't implement SQL properly, that's all there's to it.

**Comment by linkinkov** [comment]
@LemADEC use PEX all time, does not have a problem

**Comment by Time6628** [comment]
I do not have PEX linked to mySQL. Only thing I have linked to mysql is Prism.

**Comment by LemADEC** [comment]
@Time6628 looks like you're having a different issue then. Do you have other stall reports to share? Have you tried running warmroast during the stall? can you share the logs just before and after the stall?

**Comment by Time6628** [comment]
Stall from 3/13: http://hastebin.com/okarumemut.avrasm
Logs from before the stall(none after): http://hastebin.com/ugehuziluk.pas

**Comment by LemADEC** [comment]
This invalid line number is seen in https://github.com/aidancbrady/Mekanism/issues/2426 and https://github.com/CoFH/Feedback/issues/638
=> this means you'll need to narrow down your mods list, starting with CoFH dependant ones.
=> try to reproduce on a fresh world and check your world for corruption

**Comment by Time6628** [comment]
@LemADEC What kind of CoFH things could cause this? TileActivators?

**Comment by LemADEC** [comment]
CoFH is changing a lot of things in the world class. You need to narrow your scope before we can move further.

**Comment by Time6628** [comment]
I currently have CoFH Core, Redstone Arsenal, Thermal Dynamics, Thermal Expansion, and Thermal Foundation.

**Comment by Robotia** [comment]
If this crash log appears again, please share it. There is no line number 50,532 in the World source code so I cannot fix it if it's caused by Thermos.

**Comment by Robotia** [comment]
Still cannot fix this without the appropriate crash log, no response for almost a week now assuming this crash log is incorrect, closing.

**Comment by Time6628** [comment]
There is no crash log, just a stall.
