### ISSUE TITLE
encoded string too long

### ISSUE THREAD

**Issue by enterprise12nx** [TCPR/Thermos#215]
**Server Log: 
[latest.txt](https://github.com/TCPR/Thermos/files/160612/latest.txt)

**FML Log(s):
[fml-server-latest.txt](https://github.com/TCPR/Thermos/files/160611/fml-server-latest.txt)

**Explanation of issue: Server went down, and when it rebooted it started giving this error, i believe its causing low tps, the console is lagging its happening so fast.

**How to recreate this issue:N/A

**Modpack Name:** *(Only if public) Industrial Age The Turning

**Mods Installed:Too many to list, but most are on the technic page of my modpack

**Plugins Installed: ClearLagg, Essentials, EnjinMCPlugin, Groupmanager, ForgeRestrictor, GriefPreventionPlus, Jobs Reborn, Minebackup, Simple Broadcast, SimpleClans, Vault, Worldborder, Worldgaurd, worldedit, prism, votifier

**Warmroast Report:** *(Optional)*

**Thermos Version:B23

**Forge Version:1614

**EDIT** I notice everything is fine until the world saves, it then produces this error

**Comment by Robotia** [comment]
You will need to use B44 to get support, that was hundreds of changes ago. :confused: 
I looked at the crash log, this is likely the fault of one of the mods.

**Comment by enterprise12nx** [comment]
yeah i follow the updates, but they dont seem very stable yet, and B23 gives me nearly no problems, is there someway for me to identify whats causing this?

**Comment by Robotia** [comment]
44 is fairly stable, I am using it right now

**Comment by enterprise12nx** [comment]
alright i'll give it a try, guess im hesitant after finding a version working so well xD

**Comment by enterprise12nx** [comment]
still the same problem with B44

**Comment by enterprise12nx** [comment]
this is the error when the player tries to log in
http://pastebin.com/QWAQisWn

**Comment by Robotia** [comment]
@enterprise12nx Did you see this appear in your log at any point?
`[Thermos] Watchable object type is incorrect! Appying correct type!`

**Comment by Robotia** [comment]
And this is a corruption of some part of your chunks, don't believe this is Thermos' fault.

**Comment by iKaneki-Ken** [comment]
He has a corrupted entity in his base. The crash won't go away until it's cleared. There is no plugin that can fix this, you'll have to either edit the region file yourself to delete the entity or delete the region.

**Comment by enterprise12nx** [comment]
I deleted his player data again, he joins fine but i still get the "string too long" error it dont csuse a crash but lags

How can i fix tht if its a chunk idk which region file it is

**Comment by iKaneki-Ken** [comment]
@enterprise12nx Does he have any chunk loaders in his base?

**Comment by Robotia** [comment]
@enterprise12nx https://github.com/TCPR/Thermos/commit/61e02789f0f0a6b2fb16c034f1555238bc173bdc
Will prevent illegal packet sizing in the future, so he should be able to join the game.

It has something to do with a massive string on the order of 43 kilobytes.

**Comment by enterprise12nx** [comment]
No, he was literally exploring the nether and this happened, his base is with me on the moon

**Comment by enterprise12nx** [comment]
I have all chunkloaders set to only load when the players online, the error happens even with nobody on after like 3 minutes, so he can join but the encoded string too long is spamming console causing lag, he crashed in the nether exploring and rejoining crashed him and server until his playerdata was deleted

**Comment by enterprise12nx** [comment]
@Robotia i have determined Mars DIM-29 is causing a lot of lag, there is only 1 base there as far as i know.
There are many machines, etc but nothing out of the ordinary, i've seen far bigger bases and all, so i dont know what is making such low tps.

Ever since the java.io.UTFDataFormatException: encoded string too long: 65537 bytes started happening, our tps has been low, which is still occuring

**Comment by enterprise12nx** [comment]
@Robotia i fixed it by removing all world anchors in the world, perhaps there is a corrupted chunk somewhere, but its fixed now so whatevs.

Does opis work in the latest build yet?

**Comment by Robotia** [comment]
@enterprise12nx I was told it does, but I'm not sure because I don't use it myself :confused:

**Comment by Robotia** [comment]
Not Thermos' fault and no response for 13 days, assuming issue has been resolved.
