### ISSUE TITLE
[Crash] Thermos 1614.28 - java.lang.NoClassDefFoundError: scala/Function1

### ISSUE THREAD

**Issue by Yanniclord** [TCPR/Thermos#217]
Server Log:
http://pastebin.com/9YruGrbP

FML Log:
https://gist.github.com/Yanniclord/4d3883454b22575f4186

Explanation of issue:
Happens at once when i want to start my Thermos Server. I installed the recommended, non mod breaking version of Thermos, downloaded the libraries folder from the install page and then tried to start the server. The result, is in the crash log. Something about scala/Function1 class definition not found.

How to recreate this issue:
For me its just to try booting the server. It could have something with the files i have on my server to do. Here a picture of my main server directory.
![unbenannt](https://cloud.githubusercontent.com/assets/5807595/13572981/74521224-e47d-11e5-8d17-3f356dbcf11a.PNG)

Modpack Name:
STARGATE GALAXY 256XR (Technic Launcher).

Mods Installed:
![unbenannt](https://cloud.githubusercontent.com/assets/5807595/13573061/01b9de6c-e47e-11e5-9ebe-c8847b913589.PNG)

Plugins Installed:
![2](https://cloud.githubusercontent.com/assets/5807595/13573078/19def11c-e47e-11e5-9a6f-ee5d407b80fd.PNG)

Warmroast Report:
None

Thermos Version:
Thermos-1.7.10-1614.28-server-beta.jar

Forge Version:
forge-1.7.10-10.13.4.1614-1.7.10-universal.jar

**Comment by Robotia** [comment]
You have the wrong version of the libraries and are using an outdated version of thermos. The latest build is 44.

**Comment by Yanniclord** [comment]
Well i know that, but the problem is @DraksterAU recommended me NOT to go any higher due to mod breaking code.

**Comment by Yanniclord** [comment]
Would you be able to give me the libraries for Thermos 1614.28?

**Comment by Yanniclord** [comment]
Refernce: https://github.com/micdoodle8/Galacticraft/issues/2130

**Comment by DraksterAU** [comment]
Browse the list of releases til you find the download link.

I think the libraries were released with build 25.

**Comment by Yanniclord** [comment]
Ok thanks.

**Comment by Yanniclord** [comment]
Yep they were. Thanks, will try.

**Comment by DraksterAU** [comment]
@yanniclord
Close this issue.

Also, your creating a mod pack for Stargate? 

Check out mine, StargateMC.com... If your interested.

**Comment by Yanniclord** [comment]
Ye i already did, i know about yours :) But yes i have for long been building my own, but particularly without any magic or such, keeping the pack balanced and always performing at its best.

**Comment by Yanniclord** [comment]
Hey @DraksterAU, would it be possible to talk to you over something else? I have a very good idea.

**Comment by DraksterAU** [comment]
teamspeak 3 or our packs discord?

**Comment by Yanniclord** [comment]
Teamspeak sure.

**Comment by DraksterAU** [comment]
StargateMC.com is the ts3 server

**Comment by Yanniclord** [comment]
My name is LokeYourLord

**Comment by DraksterAU** [comment]
Ps.. A large chunk of your mods will misbehave under cauldron.
