### ISSUE TITLE
Thermos Build 44 Server instant apparently lag errors?

### ISSUE THREAD

**Issue by djoveryde** [TCPR/Thermos#218]
I've just updated the server to version 44 of thermos and i am suddenly having console spam about the server not responding.,
This is what I am getting 

http://pastebin.com/wPXmEXS0

EDIT: Seems the Patched version of Factions is no longer working since the update, even seems to affect coreprotect plugin

http://pastebin.com/NL6m6E2n

**Comment by Robotia** [comment]
Look at the watchdog log, atomicstryker's ruins mod is slowing down world generation.

Concerning the factions not working, I'm using it right now.

**Comment by djoveryde** [comment]
The server itself is completely timing out. Issue never occurred with Build 22

**Comment by Robotia** [comment]
The timeout for world gen was bumped to 10 seconds, that's probably part of the problem

**Comment by djoveryde** [comment]
The ruins mod generates buildings which is probably why it takes time to load the chunk.
Can the timeout be expanded to accomodate this style of mod?

**Comment by Robotia** [comment]
If I expand the timeout your server will hang indefinitely

**Comment by djoveryde** [comment]
How Can the issue be corrected? Thermos Version 22 world render takes around 12 seconds to load a new chunk. Updating to 45 causes the chunk to never load and the server to effectively hang, players then time out.
Serverside after around 10 minutes it then starts saying its responding slowly and will literally ignore any commands for well over 30 minutes until I force kill it.
If its a thermos config that needs changing please let me know as i've had to roll back to 22 for now as its the only version thats stable enough

**Comment by Robotia** [comment]
`
07.03 17:10:18 [Server] ERROR java.lang.String.toLowerCase(String.java:2590)
07.03 17:10:18 [Server] ERROR java.lang.String.toLowerCase(String.java:2670)
07.03 17:10:18 [Server] ERROR atomicstryker.ruins.common.FileHandler.addRuins(FileHandler.java:424)
07.03 17:10:18 [Server] ERROR atomicstryker.ruins.common.FileHandler.loadSpecificTemplates(FileHandler.java:260)
07.03 17:10:18 [Server] ERROR atomicstryker.ruins.common.FileHandler.access$500(FileHandler.java:21)
07.03 17:10:18 [Server] ERROR atomicstryker.ruins.common.FileHandler$LoaderThread.run(FileHandler.java:137)
`

Thermos is likely not at fault, I looked at atomicstryker's code. The thread hangs because of world loading. Look at the above log, the FileHandler thread is making the server wait.

**Comment by Robotia** [comment]
@atomicstryker This operation is very wasteful
```java
                                candidate = bgb.biomeName.toLowerCase();
                                if (candidate.equals(biomeName))
```
It should instead be
```java
                                if (bgb.biomeName.equalsIgnoreCase(biomeName))
```

**Comment by djoveryde** [comment]
^ is this why the whole servers giving up?

**Comment by Robotia** [comment]
Not sure, it is definitely a problem though

**Comment by AtomicStryker** [comment]
No. Even in a conceivable worst case, say 100 ruins in the generic folder, 400 biomes in the setup, this would lead to 100x400x400 executions, once, on load time. It really does not matter how wasteful it is. If your server times out because a mod takes too long to load, i suggest making the timeout configurable to deal with the situation.

**Comment by Robotia** [comment]
@AtomicStryker you are unnecessarily raising the size of the String intern pool in the JVM by forcing lowerCase() instead of simply checking equalsIgnoreCase

**Comment by Robotia** [comment]
@djoveryde what is your netty thread count?

**Comment by djoveryde** [comment]
What is that, and how do I check it sorry

**Comment by Robotia** [comment]
@djoveryde 
In `spigot.yml`, look for the `netty-threads` setting. Also, raise your timeout time in `spigot.yml` from 90 to 900 seconds. This should prevent the messages from showing up.

**Comment by djoveryde** [comment]
netty-threads: -1

**Comment by Robotia** [comment]
Ok, then only changing the time out time to 900 should prevent the messages from showing up.

**Comment by djoveryde** [comment]
Could that prevent the whole server timing out all together? I also got an OutOfMemory Java Heap error after leaving the server on yesterday with the errors (had to go out and just completely forgot)

**Comment by Robotia** [comment]
@djoveryde If you are out of heap space then you need to raise the memory allocated to your server by -Xmx and -Xms. That could be part of the problem if the .

**Comment by djoveryde** [comment]
The odd thing is I have never changed the RAM allocation at all even when I had over 60 players on the server. This was caused by only one player being on (server gets restarted every 12hrs)

**Comment by AtomicStryker** [comment]
@Robotia I believe it is better. My question is, would the difference even be measurable at all in live execution? I sincerely doubt it.

**Comment by Robotia** [comment]
@AtomicStryker there would probably be no difference, I believe his timeout is caused by something else. But still, it creates unnecessary Strings in the intern pool.

**Comment by djoveryde** [comment]
@Robotia Thanks, changing the timeout to 900 seems to have fixed it. Thanks again :+1:

**Comment by Robotia** [comment]
If that is the case then there might be something wrong with the watchdog o.o

**Comment by djoveryde** [comment]
Should I have not closed it? Not sure? 
I'll let you know if the server starts playing up again but so far so good :)
