### ISSUE TITLE
[Bug] Silktouch enchantment on shears drop double drop from leaves

### ISSUE THREAD

**Issue by CovehiH** [TCPR/Thermos#220]
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
N/A

**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
N/A

**Explanation of issue:**
The shears enchanted for silk touch can double-drop from leaves. Can be reproduced on vanilla forge mc.

**How to recreate this issue:**
It should be clear without details =\

**Modpack Name:** *(Only if public)*
Vanilla forge mc

**Mods Installed:**
Vanilla forge mc

**Plugins Installed:**
Vanilla forge mc

**Thermos Version:**
45

**Forge Version:**
1614

**Comment by Robotia** [comment]
Did this occur in 44?

**Comment by CovehiH** [comment]
yup

**Comment by Robotia** [comment]
This only happens with leaves and no other block?

**Comment by Robotia** [comment]
Problem identified: ItemShear gets the "sheared" results of an IShearable block. It then drops these items. In the same block break click, ItemInWorldManager calls harvestBlock which also drops a sheared item if silk harvest is available.

If this problem is unique to leaves, then leaves should not check if they are silk harvestable.

**Comment by CovehiH** [comment]
Hmmm! I can not reproduce it without forge!
It might be worth report issue to forge developers?

**Comment by Robotia** [comment]
Can you tag them?

**Comment by Robotia** [comment]
Also, did you figure out if the issue is unique to leaves?

**Comment by CovehiH** [comment]
Yes! Is unique for all leaves. And modded too.
But fix work only with vanilla leaves :(

**Comment by Robotia** [comment]
Ok I will see what to do then
