### ISSUE TITLE
[Bug] Build 46 - "Silently" catching entity tracking error

### ISSUE THREAD

**Issue by Ghostlyr** [TCPR/Thermos#224]
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
http://pastebin.com/5Uz7UuNh

**Explanation of issue:**
After updating for 46 thermos build i get this error. Error never happens with older (34) build of thermos or KCauldron 200. Errors spam my log every 10-15 sec.

**How to recreate this issue:**
I dont know.

**Modpack Name:** *(Only if public)*
Private.

**Mods Installed:**
ComboArmors 14.5.05, Buildcraft-7.1.14, ProjectRed 4.7.0, forestry 4.2.9.57, industrialcraft-2-2.2.814, Railcraft 9.8.0.0.

**Plugins Installed:**
I think is not matter.

**Warmroast Report:** *(Optional)*

**Thermos Version:**
46

**Forge Version:**
1614

**Comment by Robotia** [comment]
Should be fixed, slated for B47.

**Comment by aBizzaro** [comment]
ты админ grand main ?

**Comment by Robotia** [comment]
@aBizzaro Da, правильный :sunglasses:
