### ISSUE TITLE
Dupe bugs

### ISSUE THREAD

**Issue by ajthemacboy** [TCPR/Thermos#226]
There are multiple dupe bugs that were never fixed in Forge/KCauldron/Cauldron. They are fairly well known but not much has been done about them.

I'm not sure you can or will do anything about them either, but with recent duping issues on my server they have become quite a problem.

**Server Log:** Not relevant

**FML Log(s):** Not relevant

**Explanation of issue:** This video explains one of the glitchs: https://www.youtube.com/watch?v=jemDwT8WFEk

This video may explain another relevant current dupe bug but I haven't tested it: https://www.youtube.com/watch?v=_xsnZTiK70E

This is a video a player made showing another one, very easy to do: https://www.youtube.com/watch?v=ZlaJMfsa6hE

**How to recreate this issue:** See the videos

**Modpack Name:** Infinity Evolved

**Mods Installed:** Default mods + Sampler

**Plugins Installed:** Not relevant

**Thermos Version:** All versions

**Forge Version:** 1614

I know there are several other dupe bugs. I've asked my players to report any they know and I'll reply to this issue if I find any more.

Edit: I'm an idiot, just realized this guy's entire channel contains dupes: https://www.youtube.com/user/MrCandmann/videos

**Comment by TerdyTheTerd** [comment]
If any of these dupes work in SP then they aren't a result of any Thermos, Kcauldron, Cauldron, MCPC+ or whatever you may have. I know dupes have always existed in regular forge servers, so it's kinda pointless to post them here, it would be better to try with the mod authors for whatever mod is letting you dupe. Unless there is somehow some magical code that can prevent ALL dupes from happening, that would be awesome, but unlikely.

**Comment by LemADEC** [comment]
First and Third one are bugs in their respecitve mods, Forge/Cauldron have nothing to do with it.
Second one is a vanilla bug, there's a bunch of plugins to prevent it around here.

**Comment by ajthemacboy** [comment]
I am aware that they are mostly Forge or Mod bugs, but as Cauldron, KCauldron, and Thermos were created to cater to server owners with multiple players, I thought something might be done to fix them. 

These bugs are widely known but none of the mod authors care about them, but as they are a serious problem on large servers, again, I thought a dev might be interested in fixing them.

**Comment by Robotia** [comment]
Dupe glitches that are due to mods themselves cannot be solved here...I'm sorry but because one mod has a dupe glitch does not mean that the server code itself should be changed to fix it. The mod itself must be fixed.

**Comment by ajthemacboy** [comment]
Ok, didn't realize that. If the mod authors refuse to fix it explicitly in a forum post or something, would this be something that could be done in the "Fixes" section?

**Comment by Robotia** [comment]
Yes definitely
