### ISSUE TITLE
[Non-Thermos] The jar file has a security seal for path net.java.games.input, but that path is defined and not secure

### ISSUE THREAD

**Issue by enterprise12nx** [TCPR/Thermos#227]
**Server Log:

**FML Log(s): http://pastebin.com/LRQ1k2Kw
**Explanation of issue: My minecraft randomely stopped working, giving the issue in the log.
I have reinstalled Java JRE 32 and 64 bit.
Deleted the .technic folder, and redownloaded the technic launcher, made it run as admin.

**How to recreate this issue: No idea

**Modpack Name: Industrial Age The Turning

**Mods Installed:

**Plugins Installed: 

**Warmroast Report:** *(Optional)*

**Thermos Version:46

**Forge Version: 1.7.10.1614

I know its not a Thermos issue, but i have no idea where togo for this, technic never helps people anymore

**Comment by Robotia** [comment]
Uninstall Java 32bit, you do not need it.

**Comment by enterprise12nx** [comment]
i uninstalled 32 bit and it still happens
i have had 32 and 64 bit for years, this just started happening randomely

**Comment by Robotia** [comment]
Delete `C:\Users\Jacob\AppData\Roaming\.technic\cache\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar` specifically and replace it with this (rename to .jar, GitHub didn't let me upload with JAR extension).

**Comment by Robotia** [comment]
Woops that didn't upload...here's a DropBox link instead https://www.dropbox.com/s/32tq8jqz4jiqk79/jinput-2.0.5.jar?dl=0

**Comment by enterprise12nx** [comment]
did that, same problem.
Idk if technic may be overwriting with its own file or not, either way it didnt work /=

**Comment by djoveryde** [comment]
Remove Liteloader temporarily and try loading

**Comment by NEXUS2345** [comment]
LiteLoader does not need any special editing. All you have to do is drop it in the mods folder...

**Comment by Robotia** [comment]
No response for 13 days, assuming resolved.

**Comment by DoulosChristou** [comment]
I am having a similar problem how ever I am just trying to install Lite loader onto minecraft 1.7.10. the only things i have installed in my minecraft folder are Forge and lite Loader. when I try to run minecraft I get this error in my crash report  several times

[01:57:09] [Client thread/ERROR]: The jar file C:\Users\Codyf\AppData\Roaming\.minecraft\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar has a security seal for path net.java.games.input, but that path is defined and not secure

I have uninstalled java 32, only have 64. and I tried to replace the jinput file with the one from your drop box but it did not change anything. any other suggestions?

**Comment by enterprise12nx** [comment]
Mine just randomely began working again after i updated mods in my modpack, no idea

**Comment by Bogdan-G** [comment]
ignore error, MCForge dont use files

**Comment by DoulosChristou** [comment]
I mean I can't really just ignore it if it crashes Minecraft every time. But I guess it somehow resolved itself after a few days becuse it's working and I didn't change anything.

**Comment by Bogdan-G** [comment]
@DoulosChristou likely crash was for another reason
