### ISSUE TITLE
[Server Freezing] Freezing Again No error occurs :(

### ISSUE THREAD

**Issue by gafunbird007** [TCPR/Thermos#228]
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
https://gist.github.com/gafunbird007/c74d612178c6e5b3d15b
**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
https://gist.github.com/gafunbird007/156a77392af07cb44cb3
**Explanation of issue:**

it just freezing and no pattern no log no error occurs and it happen after i  uninstall aether and Mine&blade mod from my server already. (Please help me I really need help about this i can't let it happen in my server again :(  )

**How to recreate this issue:**
no pattern
**Modpack Name:** *(Only if public)*

**Mods Installed:**

Netherrock,simaplecore api,simpleore 2 , Animalbike, AnimationAPI,backpack,CustomNPC,extrabiomexl,fairylight,FamilarAPI,Familar Default-Extend MobPack,GibysVC,grim3123-Core,Hats,ichunutl,More-Enchantments,MutantCreature,sampler,SuplerSlope,

**Plugins Installed:**
Authme,AutoMessage,Chestshop,Clearlag,ContainerDedicaton,CreativeGates,Essentials - everything,faction,iconomy,lockette,lordlib,massivecore,noitem,pex,playervip,preciousstone,randombox,scavenger,serversign,vault,worldboarder,worldedit,wg

**Warmroast Report:** *(Optional)*
NO i
**Thermos Version:**
b 46
**Forge Version:**
1448
**Timings Report:**
http://www.spigotmc.org/go/timings?url=15340387
**Stall Report:**
No Stall Report It not appear
**Spigot.yml:**
https://gist.github.com/gafunbird007/7cf98ba93d1cde922448
**Bukkit.yml:**
https://gist.github.com/gafunbird007/752c64584083d1a30207
**cauldron.yml:**
https://gist.github.com/gafunbird007/bd644e16333738783f77

**Comment by djoveryde** [comment]
Try allocating More RAM to the server, sounds similar to my issue where the whole server would just start hanging up. Although mine was related to the timeout which you already have set to 900.

Also not sure why but when your hang begins the [Server thread/INFO] before each chat changes to [Netty IO #1/INFO]. Could be a sign of whats wrong?

**Comment by Robotia** [comment]
Please provide a WarmRoast log or other form of profiling log, this is not enough information to go on. :confused:
