### ISSUE TITLE
[Spigot WatchDOG]Error Server keep Freezing

### ISSUE THREAD

**Issue by gafunbird007** [TCPR/Thermos#229]
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
https://gist.github.com/gafunbird007/1ed9262426474d0d05ac
**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
---
**Explanation of issue:**
Happen randomly (different issues which the old i add in few hours ago)
**How to recreate this issue:**
I don't Know
**Modpack Name:** *(Only if public)*

**Mods Installed:**

Netherrock,simaplecore api,simpleore 2 , Animalbike, AnimationAPI,backpack,CustomNPC,extrabiomexl,fairylight,FamilarAPI,Familar Default-Extend MobPack,GibysVC,grim3123-Core,Hats,ichunutl,More-Enchantments,MutantCreature,sampler,SuplerSlope,
**Plugins Installed:**

Authme,AutoMessage,Chestshop,Clearlag,ContainerDedicaton,CreativeGates,Essentials - everything,faction,iconomy,lockette,lordlib,massivecore,noitem,pex,playervip,preciousstone,randombox,scavenger,serversign,vault,worldboarder,worldedit,wg
**Warmroast Report:** *(Optional)*

**Thermos Version:**
b46
**Forge Version:**
1448
***Stall Report:****
**https://gist.github.com/gafunbird007/c899fdba86a415820ece**
--------------------------------------------------------------------
Spigot.yml:
https://gist.github.com/gafunbird007/7cf98ba93d1cde922448
Bukkit.yml:
https://gist.github.com/gafunbird007/752c64584083d1a30207
cauldron.yml:
https://gist.github.com/gafunbird007/bd644e16333738783f77

**Comment by djoveryde** [comment]
Try increasing the RAM to the server

**Comment by gafunbird007** [comment]
My time-out is already 1500 my server ram is 25GB and it run on SSD I don't think it because of server quality I will try change it to 900

**Comment by Time6628** [comment]
How much ram is dedicated to the server though?

**Comment by gafunbird007** [comment]
@time6628 xms 18 xmx 25

**Comment by djoveryde** [comment]
Is it set like this? 

-Xms18G -Xmx25G

Without the G it wont allocate in GB

**Comment by gafunbird007** [comment]
Is with G

**Comment by djoveryde** [comment]
Make sure you are forcing the 64 bit java to be used and not the 32 bit version otherwise anything above 1GB will be ignored.

**Comment by gafunbird007** [comment]
@Nexus2345 Can you please help me to setup a warmroast in window server?

**Comment by gafunbird007** [comment]
@Nexus2345 @Robotia Hi from what he say is after player dragonmoters logged in the server start freezing now it happen again in last few minutes !! after player dragonmoters join a server again i think there is something wrong with this user but everything he did is just join the game!

**Comment by Time6628** [comment]
Then move him to spawn and see if that fixes it...

**Comment by gafunbird007** [comment]
@time6648 that might fix but I other way mean it can still happen we have to fix it from cause too

**Comment by Time6628** [comment]
Try fixin the chunk he is in with a world editing tool.

**Comment by Robotia** [comment]
@gafunbird007 if you want I can personally take a look and investigate.

**Comment by gafunbird007** [comment]
@Robotia  Yes , please Now i have 2 problem first is the chunk problem that  cause by user : dragonmoters . Second is server randomly kick player out sometime

**Comment by Robotia** [comment]
@gafunbird007 Private message me on Discord.

**Comment by Yorkforce** [comment]
This is also occurred on our recent Thermos servers too.

**Comment by Robotia** [comment]
A timeout like this is *not* due to the watchdog thread, it is likely due to an incompatibility between your mods

**Comment by gafunbird007** [comment]
Thank you seem not to be appen again after get aether out
