### ISSUE TITLE
Thank you.

### ISSUE THREAD

**Issue by iKaneki-Ken** [TCPR/Thermos#23]
After testing your version of KCauldron performance did increase a lot.

On startup with Prototiks version, the ms/t would be 6-8ms.

On startup with your version, the ms/t is 2-4ms/t.

---

Sorry if this seems like a waste of time, just wanted to thank you for the time you spent working on this. Especially given the fact that you didn't have to share this with anyone at all.

**Comment by Robotia** [comment]
@iKaneki-Ken I'm glad that someone appreciates my work! :smile: 
That made my day (well my night but still).

**Comment by Cracks777** [comment]
Yes i also Agree, i have found this version and its all i use now, i love it. Thank you so much.

**Comment by Robotia** [comment]
@Cracks777 :smile:

**Comment by iKaneki-Ken** [comment]
Oh as well, if you're up for it, put a donation link in the README.md. I'm sure a lot of people will be willing to help out financially.

**Comment by Robotia** [comment]
@Yive would it be ok if I did this?

**Comment by TerdyTheTerd** [comment]
I would expect any server owner who uses this to donate, as that would be common courtesy. I just pledged $15/month on your patreon, might want to add some more info on that page

**Comment by Robotia** [comment]
@TerdyTheTerd Thank you and will do.
