### ISSUE TITLE
Periodically freezing check the video.

### ISSUE THREAD

**Issue by Bormandesign** [TCPR/Thermos#231]
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
Log is clear
**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
Log is clear
**Explanation of issue:**
The server periodically weird lag, see details in the video.
**How to recreate this issue:**
Dunno. 
**Thermos Version:**
 1.7.10-1614.46 
**Forge Version:**
Forge 1614

https://youtu.be/C03b-FNkPUA
Here is the video, what is it? On KCauldron all clear, Thermos periodically lag.
Maybe its anticheat protection? How can i disable it?
Best regards.

**Comment by kristi71111** [comment]
If you are using towny then this is probably towny safemode [Explained here](https://code.google.com/archive/a/eclipselabs.org/p/towny/wikis/Troubleshooting.wiki)

**Comment by djoveryde** [comment]
@Bormandesign Restart the Server, then paste the whole log into pastebin. As @kristi71111 mentioned it could be Towny causing this if you have towny. When it enters Safe mode literally everybody is locked in place until the issue is fixed. Generally a plugin causes this type of issue.

**Comment by Bormandesign** [comment]
Nope, this is not towny.

**Comment by kristi71111** [comment]
@Bormandesign any chance we could still get the actual server startup log?

**Comment by Robotia** [comment]
That happens when a teleportation is done incorrectly by a mod in my experience. Do not get hostile, you never even put a log in the first place.

**Comment by Bormandesign** [comment]
@Robotia sorry, here ya go. 
Start up log http://pastebin.com/LqJT1gi1
Fml-latest log http://pastebin.com/Dh1EAmXq

I mean its Hacked Client Detection, because i have many self made plugins.

**Comment by Robotia** [comment]
@Bormandesign this is not a bug caused by Thermos as far as I can tell - I never implemented any feature that prevents players from moving. What did you do to cause this? What happened right before you were locked in place?

**Comment by Time6628** [comment]
Can you list what blocks are around you? I had this happen to me when I was breeding ender bees from forestry bees. Ender bees teleport you around the area unless you have apiarist armor. This is most likely the cause, a mod trying to move you too fast.

**Comment by Robotia** [comment]
Individual who created the issue never responded to the question, assuming the issue has been resolved.
