### ISSUE TITLE
[Question] Weird Picaso images in Multiplayer?

### ISSUE THREAD

**Issue by djoveryde** [TCPR/Thermos#232]
I've been meaning to ask this question because i'm very confused about what it is and how to remove it or change it, but it seems for a few weeks now every time I go to the multiplayer section of a modpack next to the server is a little picaso drawing of weird lines.

Anyone know what this is and how to change/remove it?

**Comment by Robotia** [comment]
Sorry about that, the default icon generator is a bit messed up. Change `server-icon.png` to something of your choice and it will go away.

**Comment by Yive** [comment]
@Robotia Not exactly sure if you added this, but I think the default icon should be configurable , mainly since I know some servers prefer to have no icon.

**Comment by Robotia** [comment]
@Yive yeah I did add it but I didn't realize it would be that bad...I'll remove it at some point, just remind me

**Comment by djoveryde** [comment]
if you could add a toggle for it in the thermos.yml file that would help the servers that don't want an icon.
I just worried i did something wrong lol
