### ISSUE TITLE
"Silently" catching entity tracking error.

### ISSUE THREAD

**Issue by cubespace** [TCPR/Thermos#234]
Very often it shows in the console: 1.7.10-1614.47
http://pastebin.com/WVdP1W9j

**Comment by Robotia** [comment]
It's still showing up? Argh

**Comment by cubespace** [comment]
Yes

**Comment by cubespace** [comment]
http://pastebin.com/r2P9JxWH

**Comment by Robotia** [comment]
Fix has been basically implemented and will be released in 47

**Comment by Robotia** [comment]
Argh 48*

**Comment by cubespace** [comment]
No(
http://pastebin.com/UfrxmjZz

**Comment by Bormandesign** [comment]
Still here, B49
http://pastebin.com/dAcgtnTa

**Comment by Robotia** [comment]
Fixed in 51.
