### ISSUE TITLE
Experience levels disappear after change dimenson with bukkit plugins.

### ISSUE THREAD

**Issue by Ghostlyr** [TCPR/Thermos#235]
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
No any errors.

**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
No any errors.

**Explanation of issue:**
After player enter to other dimension and go back with bukkit teleportation, his wxperience levels disappears. After reconnecting levels comes back. With older build of thermos (32) and kcauldron 200 all be fine on this instance.

**How to recreate this issue:**
1. Enter to any dimension with portal
2. Go back with plugin (such as spawn from essentials)
3. See your 0 exp level and cry :)
4. Reconnect to server and be of good cheer.

**Modpack Name:** *(Only if public)*
Private

**Mods Installed:**
Mot matter

**Plugins Installed:**
Essentials

**Warmroast Report:** *(Optional)*

**Thermos Version:**
46

**Forge Version:**
1614

**Comment by djoveryde** [comment]
Confirmed Also affects the /spawn command on Build .48
Have XP, go through Nether Portal. Use spawn command from the nether and you suddenly have null XP, not even a level 0 appears.
 Log out and back in and your XP has returned.

**Comment by Robotia** [comment]
synchronization packet is probably needed then

**Comment by djoveryde** [comment]
@Robotia is there any tools I can use that could help me to help you locate where the issues are? 
Like a plugin/mod that shows whats being fired at the time in console to pinpoint which area is causing the issue?

**Comment by Robotia** [comment]
Not really :confused: most of this stuff requires Java coding.

**Comment by Robotia** [comment]
Fixed in B54.

**Comment by Ghostlyr** [comment]
Excellent work and huge thanks, but as it turned out, experience lost also when teleporting from End Portal (which falls from Ender Dragon),

**Comment by Robotia** [comment]
Does it reappear on relog?

**Comment by Ghostlyr** [comment]
No :(
