### ISSUE TITLE
Projectiles with null damage can hurt players. Again.

### ISSUE THREAD

**Issue by Ghostlyr** [TCPR/Thermos#237]
**Explanation of issue:**
https://github.com/TCPR/Thermos/commit/9d476d0358147d69d0f84c84547fd8f4914541cc This commit break fix from 106 kcauldron issue.
Perhaps it fix #172 , but this bug is important too.. :(

**How to recreate this issue:**
Throw snowball/egg/enderpearl/fishing rod to player where he protected for damage via bukkit plugins.

**Thermos Version:**
46

**Forge Version:**
1614

**Comment by Robotia** [comment]
@Ghostlyr what was issue 106?

**Comment by Ghostlyr** [comment]
https://gitlab.prok.pw/KCauldron/KCauldron/issues/106

**Comment by Robotia** [comment]
Ok yes you are right, seems will need to `return false` if Bukkit event cancels but Bukkit event doesn't call if damage is 0. So now need to check for that possibility..

**Comment by TheAndrey** [comment]
@Robotia the problem here
EntityLivingBase.damageEntity_CB()
`    // CraftBukkit start
    protected boolean damageEntity_CB(final DamageSource damagesource, float f)
    { // void -> boolean, add final
        if (!this.isEntityInvulnerable())
        {
            final boolean human = this instanceof EntityPlayer;
            float originalDamage = f;
            // Cauldron start - apply forge damage hook
            f = ForgeHooks.onLivingHurt(this, damagesource, f);
            if (f < 0) return true;
            // Cauldron end
`
You need to remove this line. I did and the problem was solved. `if (f < 0) return true;`

**Comment by Robotia** [comment]
@TheAndrey It should always be `<= 0` that is the **Forge default**. It should not have been changed in the first place. I would rather send an event of 0 damage to Bukkit by which the damage could be canceled.

**Comment by Robotia** [comment]
Fixed now by 2e0222dd38faa697f5a05a9f0137e79a15ab2078
