### ISSUE TITLE
[Crash] Thermos #46

### ISSUE THREAD

**Issue by linkinkov** [TCPR/Thermos#238]
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
http://pastebin.com/vKuFDAE7

**Comment by linkinkov** [comment]
Close, because its problem by DivineRPG update checker

**Comment by Robotia** [comment]
@linkinkov Disable it in config or I can make fix in TCPR repo for you
