### ISSUE TITLE
DO NOT USE MULTIVERSE-CORE-2.5, VERY BUGGY! USE MULTIVERSE-CORE-2.4!

### ISSUE THREAD

**Issue by djoveryde** [TCPR/Thermos#241]
It appears something in Thermos has now bugged Vampirism in Witchery completely.

Originally Players could kill a vampire with either steaking them, Death Scythe, kikoku Sword, Garlic, Werewolf bite.
However now nothing a player does seems to damage vampires at all. They can at times damage them to 1 hp but then they wont die at all no matter how much you hit them.
The player themselves can burn in lava and die in the sun though, so not sure if its something in the way witchery fires damage code to the player thats bugged out.
Nothing in console at all.
Sadly its hard to reproduce in singleplayer as you need 2 people to test it

Modpack -Hexx Reloaded-

**Comment by Robotia** [comment]
When did you notice this change in behavior? Is there a specific build after which this started happening?

**Comment by djoveryde** [comment]
Sadly the players have only bought this to my attention today. It worked fine when it was cauldron I know that much. I could try and run an early Thermos build and test it. Any suggesting which thermos build to use?

**Comment by Robotia** [comment]
I would recommend 28.

**Comment by Robotia** [comment]
(Be careful please)

**Comment by djoveryde** [comment]
Further testing this is not just Witchery, it seems most modded weapons no longer work at all. Vanilla damage fine.

Testing it was actually multiverse-Core-2.5.jar which seemed to have physically messed all damage and inventory controls up.
Switched back to Multiverse-core-2.4.jar and everything is working normally.

**Comment by Brycey92** [comment]
If the issue did not exist in cauldron, but is present in thermos, why was the issue closed?

**Comment by Yive** [comment]
[11:46:04 AM] TWSSYesterday: Not an issue our side, we're just using the same methods as we were
[11:46:12 AM] TWSSYesterday: Only thing we've done is cleanup

So it seems to be an issue with Thermos & not Multiverse

**Comment by Brycey92** [comment]
I tested latest Multiverse (b719) + Multiverse Portals (b739) with Thermos 55, and no vanilla or modded weapons are having damage issues on players or mobs, and no inventory issues are readily apparent, even upon death. It could be related to Witchery or the interaction between Thermos, MV, and Witchery.
