### ISSUE TITLE
[Question] Are they having Bad Login?

### ISSUE THREAD

**Issue by Eufranio** [TCPR/Thermos#244]
**Explanation of issue:**
Most players on my server recently tell me about problems with Bad Login (invalid session), when i updated to Thermos. I want know if someone is having the same problem, or its with my server.
EDIT: I have online-mode=false on my server.propeties, but still giving me invalid session.

**Thermos Version:**
Build 49

**Forge Version:**
1614

**Comment by Robotia** [comment]
I don't believe this is Thermos' fault, as I myself have never had this issue. What country is your server located in?

**Comment by Eufranio** [comment]
Montreal, Canada.

**Comment by Robotia** [comment]
Well it can't be long distance connection then...and bad login occurs when someone else logs in with your email and password or you login elsewhere.

**Comment by Yive** [comment]
This is a client side issue, not related to the server at all.

**Comment by Eufranio** [comment]
Yep, but peoples can't connect ONLY with my server. And isn't only one people, are various. I saw that put online-mode=false fix the problem, but even so the players can't connect...

**Comment by Robotia** [comment]
If your server is already in online mode, turning it to false is a horrible idea, **you will break UUIDs**. 
I believe this is another issue caused by one of your mods....I do not know anyone else facing this issue.

**Comment by Eufranio** [comment]
Okay :/
