### ISSUE TITLE
Move to self hosted Git

### ISSUE THREAD

**Issue by Yive** [TCPR/Thermos#245]
Recently I have gotten into using Gogs & was wondering if this git repo should be moved over to http://gogs.tcpr.ca/TCPR. Personally I think it's much more sexy looking compared to github + wont have to worry about DMCA takedowns.

**Comment by KasperFranz** [comment]
I'm not sure what the end goal with this is.

about the DMCA takedowns, It would be the same problem on a self hosted solution.

And in the end I personally think GitHub is a much better and widely used platform, and more people are going to post feedback/issues when it's here on GitHub than on yet another self hosted solution (sorry).

**Comment by Robotia** [comment]
The DMCA takedown can't be done if the server is in Russia or some other place where DMCA is not effective

**Comment by Yive** [comment]
Issues will still most likely be on github, at least for a while until people decided to register on the Gogs site. Will probably try to get people to use the gogs for issues more once most of the issues have been resolved here.

**Comment by Rubbertjuh** [comment]
Are the DMCA Takedowns still a thread for us? If they are, then it might be a good idea to switch over. I really like the looks of the Gogs. 
I do think that a lot of people will stop reporting issues, because they are too lazy to actually create a new account. I guess if they are too lazy to create an account, they don't deserve their issue to be fixed though ^^

**Comment by Robotia** [comment]
I personally would be against moving Thermos to a self hosted Gît. I feel like that would unnecessarily restrict the number of contributors. Also, the DMCA is unlikely to ever be an issue. If it does, then I would happily switch to Gogs.

**Comment by Razorskills** [comment]
could you not just mirror it to gogs? then if a dmca went on git which i doubt it. then its a good backup plan. I personally like checking my github notifications for updates etc. and didn't enjoy the kcauldron gogs, then gitlab

**Comment by Robotia** [comment]
We will not be moving to Gogs unless DMCA or other copyright issues arise.
