### ISSUE TITLE
[Crash] Forestry? java.lang.StackOverflowError: Exception in server tick loop

### ISSUE THREAD

**Issue by vadimyer** [TCPR/Thermos#246]
Server log:
http://pastebin.com/ZHC5W9zH

FML log: nothing interesting there.

Explanation of issue:
Well, I don't know. It is happening for the second day, and crashing every hour or so! The crash-report is huge, I guess it's something with forestry's worktable, but I can't really find out what exactly. Maybe someone is cheating or something, cause this is really strange.

How to recreate this issue:
I don't know ._.

Mods Installed: ...

Plugins Installed: ...

Warmroast Report: not installed.

Thermos Version: 32 yesterday, 49 today.

Forge Version: 1614.

**Comment by vadimyer** [comment]
Those crash-reports are almost the same, but they are a little different every time, like so:
http://pastebin.com/fKeX3cwv

**Comment by djoveryde** [comment]
I had a similar issue A LOT with Cauldron & Kcauldron
For me it was a Forestry item that was bugging out a vanilla chest and corrupting the chunk. You can at times manage to get to that chunk and find the offending chest and delete it (you have to remove the chest. Even removing the items from the chest doesnt stop it bugging out).
My guess is your issue is very similar if not the same, although my crash report told me which chest it was and how to find it.

**Comment by vadimyer** [comment]
If only I could, these crash reports are not telling me where the bugged item is...

**Comment by djoveryde** [comment]
Have you got RemoveErroringEntities and RemoveErroringTileEntities set to true in the Forge.cfg file in the config folder?
Might help.
Seems the issue is relating to a WorkTable I believe.

**Comment by vadimyer** [comment]
Nope, I can try though, this seems very dangerous.

**Comment by djoveryde** [comment]
What those do is instead of crashing the server it will just remove the tile/entity. Much easier :)

**Comment by Rubbertjuh** [comment]
I'm using the RemoveErroringEntities and RemoveErroringTileEntities as well and have yet to find a problem with it, it has saved my server from crashing multiple times!

**Comment by vadimyer** [comment]
I've turned those options on since yesterday, so far no crashes of that kind.

**Comment by vadimyer** [comment]
This does not help! I got around 7 crashes today!

**Comment by vadimyer** [comment]
Just 4 of them:
http://pastebin.com/xPMprRsB
http://pastebin.com/Pq9HGv5N
http://pastebin.com/4yzKTmnC
http://pastebin.com/9viAdhwj

They all start with:
```
java.lang.StackOverflowError: Exception in server tick loop
    at java.util.HashMap.putVal(HashMap.java:628)
    at java.util.HashMap.put(HashMap.java:611)
    at java.util.HashSet.add(HashSet.java:219)
```

I think I'm getting hacked. Please help @Robotia !

**Comment by Robotia** [comment]
@vadimyer https://discord.gg/0VmBoNh2sE3fuR81

**Comment by vadimyer** [comment]
Fixed by upgrading Forestry ._.
