### ISSUE TITLE
[Sugestion] Auto Updater

### ISSUE THREAD

**Issue by Eufranio** [TCPR/Thermos#247]
Like a older KCauldron, Thermos could have an auto updater, and maybe an auto update for builds too. This is much more easier for update, principally from the console (because i can't stay on server 24/7)

**Comment by djoveryde** [comment]
Rather not have an "Auto Updater" but instead the option to upgrade if its finds an update using /thupdate command which could update and then auto restart the server perhaps?

**Comment by Time6628** [comment]
Already exisits...?

**Comment by iKaneki-Ken** [comment]
This already exists, check thermos.yml to turn it on.

**Comment by Robotia** [comment]
I'm not sure if that actually works...
If it does not, I would be against implementing one for the following reasons:
+ People will not read the release notes 
+ Servers in countries like Thailand might take a long time to download the JARs (in theory)
+ Server could crash during update download, thus creating a corrupt JAR (and leaving people confused as to why the server isn't starting)
 
I will not be implementing this (if it doesn't already exist).

**Comment by Yive** [comment]
It was purposely removed long ago.

https://github.com/TCPR/Thermos/commit/cfae2ed9bdf1b060e8ae608d7d6555dde274ef1f
