### ISSUE TITLE
[Not the Thermos] PixelMon

### ISSUE THREAD

**Issue by linkinkov** [TCPR/Thermos#250]
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
Sometimes stall report:
http://pastebin.com/hiDRCd20
Its problem by pixelmon i mean?

**Comment by djoveryde** [comment]
That actually is the same error I am getting when the server is trying to render new areas with structures. As pixemon does the same with rendering pokecentres everywhere and other things.
@Robotia it seems this issue only occurs on servers that have mods that generate structures when generating new chunks.

**Comment by Robotia** [comment]
I have looked through the code and found the following:
moveEntityWithHeading() -> moveEntity() -> getCollidingBoundingBoxes() 
                                                                                ^ (hangs here)
As this is not caused by Thermos and should instead be reported to the mod's author, this issue will be closed.
