### ISSUE TITLE
crash agrarian skies

### ISSUE THREAD

**Issue by Snackro** [TCPR/Thermos#251]
**Crash report:** http://pastebin.com/vwB1NVEf

**FML Log(s):** http://pastebin.com/hW6VYBnq

**Modpack Name:** Agrarian skies 2

**Thermos Version:**  Thermos-1.7.10-1614-46-server.jar

server crash during the server launch.

**Comment by Robotia** [comment]
Some mod is modifying bytecode...is Dragon API or any Reika mod in the pack?

**Comment by Andrey-007** [comment]
tcnodetracker???
client mods

**Comment by Snackro** [comment]
Hi,

i removed  TcNodeTraker but the server always crash,
  i haven't reika mod in the pack.

new Crash report: http://pastebin.com/TQUK24mW

new FML Log(s): http://pastebin.com/wLGwyq3F

ModList ==>   http://pastebin.com/pyA129N5

**Comment by Robotia** [comment]
Try removing recall stones

**Comment by Snackro** [comment]
Thx it's work

**Comment by Andrey-007** [comment]
1 Use a thermos Forge 1588
2 Remove mods (TiCTooltips, Ding)
