### ISSUE TITLE
LookingGlass compatibility issues

### ISSUE THREAD

**Issue by leszczu8023** [TCPR/Thermos#256]
**Server Log:** 
http://pastebin.com/mYzMZRAw

**FML Log(s):**
http://pastebin.com/ym4r3JDQ

**Explanation of issue:**
When I bound a _Camera monitor_ with _Camera_ it cause a errors in server log and it's not working.
Here's also LookingGlass author's comment about this issue: http://www.xcompwiz.com/forum/viewtopic.php?f=35&t=3280

(Sorry for my English) 

**Mods Installed:**
LookingGlass, SecurityCraft

**Thermos Version:**
 1.7.10-1614.50

**Forge Version:**
 1.7.10-1614

**Comment by Robotia** [comment]
I looked at his comment...I don't think he looked at the Cauldron code when he said that. Problem seems to be inherent in modifications to Nibble Array storage...not removal of entire variables. Will look into this.

**Comment by Robotia** [comment]
@leszczu8023 does this happen if the camera and camera monitor are within the same chunk?

**Comment by Robotia** [comment]
@leszczu8023 ?

**Comment by leszczu8023** [comment]
@Robotia yes.

BTW: I found some differences in NibbleArray class.
In clean Forge for getting byte array from this class author used:
**nibbleArray.data**
but, in Thermos this method works:
**nibbleArray.getValueArray()**

My temporary fix for this:
`public static byte[] getValArray(NibbleArray a) {
      if (LookingGlass.IS_CAULDRON) {
         try {
            Method method = NibbleArray.class.getMethod("getValueArray");
            byte[] b = (byte[]) method.invoke(a);
            return b;
         } catch (Exception e) {
            e.printStackTrace();
            return null;
         }
      } else {
         return a.data;
      }
   }`

I'm also replaced arrays with ArrayLists.

**Original:**
https://github.com/XCompWiz/LookingGlass/blob/master/src/main/java/com/xcompwiz/lookingglass/network/packet/PacketChunkInfo.java
**My modified code:**
https://gist.github.com/leszczu8023/a1b832c4cee4f1c09774

**Comment by Robotia** [comment]
@leszczu8023 this worked for you? If so, I will try to revert the change to re-align with Forge.

**Comment by leszczu8023** [comment]
@Robotia Yes. I tested this on my own server.

**Comment by Robotia** [comment]
Should be fixed in B52.
