### ISSUE TITLE
Open Blocks Graves Request

### ISSUE THREAD

**Issue by enterprise12nx** [TCPR/Thermos#257]
Request:
I heard you work on other mods if requested (if you have time of course)
the old open blocks graves use to have a toggle to be explodable...now they dont

with griefprevention raiding server, people who die in claims cannot retrieve their things by exploding their graves, i was hoping this could be re-implemented, or maybe a working version for 1.7 is still around with it?

**Comment by Robotia** [comment]
This request should be directed at http://gogs.tcpr.ca/TCPR/Fixes

**Comment by Eufranio** [comment]
When right click with an shovel on a gravestone, it will drop your itens without break.
