### ISSUE TITLE
Compatibility with reika's mods

### ISSUE THREAD

**Issue by wormzjl** [TCPR/Thermos#258]
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
http://pastebin.com/Ljygwqp0
**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*

**Explanation of issue:**
Crash on start with an ASM conflict

**How to recreate this issue:**

**Modpack Name:** *(Only if public)*

**Mods Installed:**

**Plugins Installed:**

**Warmroast Report:** *(Optional)*

**Thermos Version:**
build 50

**Forge Version:**

**Comment by wormzjl** [comment]
I remember that reika had some sort of fix for kcauldron,,,

**Comment by Time6628** [comment]
https://github.com/KookykraftMC/DragonAPI

**Comment by wormzjl** [comment]
I guess that there is no release for that version?
It's extremely difficult to build reika's mods due to the number of dependencies

**Comment by Time6628** [comment]
Not atm but that has the fix for thermos.

**Comment by Time6628** [comment]
Actually this is implemented in the latest version of DragonAPI. :)

**Comment by Robotia** [comment]
Fixed, see below:
https://github.com/ReikaKalseki/DragonAPI/commit/82a500a1befc7033e3d834b488900a9fb6858848
https://github.com/ReikaKalseki/DragonAPI/pull/18
