### ISSUE TITLE
Crash | Thermos 50 - java.lang.NoClassDefFoundError: appeng/core/WorldSettings

### ISSUE THREAD

**Issue by Esctogrillo** [TCPR/Thermos#262]
**Crash Report** *http://pastebin.com/s4x7ta82*

**Explanation of issue:** *I don't know*

**How to recreate this issue:** *I don't know*

**Modpack Name:** *[Jordann Pack] (http://technicpack.net/modpack/jodann.726573)*

**Mods Installed:** *[Here] (https://github.com/TheKingdomServer/JordannPack/tree/master/mods)*

**Plugins Installed:** *On crash report*

**Thermos Version:** *b50*

**Forge Version:** *1614*

**Comment by Robotia** [comment]
Applied energistics mod is missing, not Thermos' fault. Ban the grower

**Comment by Esctogrillo** [comment]
Sorry, ae2stuff is not compatible with applied energistics rv3.
