### ISSUE TITLE
Chunk loaders doesn't work in other dimensions if the isn't a player on it

### ISSUE THREAD

**Issue by checkplys** [TCPR/Thermos#267]
Any chunk loader don't work in other dimensions, only if there's a player on it, it don't work in all the dimensions (DeepDark, The Last Millenium, or MultiVerse created dimensions).

**Comment by Robotia** [comment]
What type of chunk loader have you tried? Did you try a Rail Craft `World Anchor`?

**Comment by vadimyer** [comment]
Confirm the same, with Railcraft's `World Anchor`.

**Comment by Robotia** [comment]
You're right, it is a duplicate. Closing.
