### ISSUE TITLE
Missing library org/apache/commons/lang/Validate

### ISSUE THREAD

**Issue by ChrisLane** [TCPR/Thermos#269]
**Server Log:**
http://pastebin.com/PD7J4vrw

**FML Log(s):**
http://pastebin.com/RLZXfcVt

**Explanation of issue:**
Attempting to load a server on Ubuntu server with Thermos release [53 BETA](https://github.com/TCPR/Thermos/releases/tag/53) and startup fails with missing libraries.
I have the minecraft_server.1.7.10.jar file as well as the libraries from release 53 BETA.

The issue did not occur when running the system locally on my windows machine.

**Mods Installed:**
Mod Control
JourneyMap
InventoryTweaks
Flan's Mod

**Thermos Version:**
https://github.com/TCPR/Thermos/releases/tag/53

**Forge Version:**
1.7.10-1614

**Comment by Robotia** [comment]
There is no release 59 ( I believe you meant 53).

The libraries are in a "libraries" folder in your server directory, correct?

**Comment by ChrisLane** [comment]
Sorry yes, release 53 BETA.

The libraries folder is in my server's root directory along with the Thermos.jar and minecraft_server.1.7.10.jar

**Comment by ChrisLane** [comment]
Couldn't reproduce on a separate server on the same machine for some reason. Closing the issue for now.
