### ISSUE TITLE
[Warning] NPCs are still broken

### ISSUE THREAD

**Issue by Robotia** [TCPR/Thermos#27]
Warning to all server owners using KCauldron, NPCs are still somewhat broken. 

If you have an NPC with the same name as one of your players, remove it **now**. 

*A player in survival mode can do a creative "middle-click" to get free items if there is an NPC that has the same name.*

This should have been fixed by Protik [here](https://gitlab.prok.pw/KCauldron/KCauldron/commit/1817b56ba3dc54f9c7d6e3250f1139576854d3b4) but it is *not*.

**Comment by djoveryde** [comment]
As the soulbound bug was fixed should this now be closed or is this still an active issue?

**Comment by Robotia** [comment]
I do not know whether this is sill a problem, it needs further investigation

**Comment by Robotia** [comment]
Should be fixed in 36.
