### ISSUE TITLE
Protect server from mods like ProjectE

### ISSUE THREAD

**Issue by Zilacon** [TCPR/Thermos#270]
**Explanation of issue:**
So i saw you were working on making mods work with bukkit plugins so i tested to see if projecte still bypasses protections, and it does. Any chance this could be added to thermos? This is the #1 problem for every Tekkit Legends server.

**How to recreate this issue:**
Use half of the items from ProjectE on a protected region like worldguard, griefprevention, towny, factions, etc. And watch stuff either blow up or disappear.

**Modpack Name:** *(Only if public)*
Tekkit Legends from Technic

**Mods Installed:**
Mod list on technic's website.

**Plugins Installed:**
 WorldEdit, EmptyWorldGenerator, Essentials, LoginSecurity, GroupManager, DeletePlayerData, ConsoleScheduler, WorldBorder, SpawnJoin, Votifier, WorldGuard, MultiWorld, AlwaysDay, AsyncWorldEdit, KaisRandomTP, StopProxy, Vault, TekkitCustomizer, Prism, EssentialsSpawn, MassiveCore, LegendaryMessages, EnjinMinecraftPlugin, Smelter, ChestShop, MCBans, Resurrection, GriefPreventionPlus, RegionForSale, APOCPayday2, SilkSpawners, Legendchat, Factions

**Thermos Version:**
This server is running Thermos | https://github.com/TCPR/Thermos | 1.7.10-R0.1-SNAPSHOT | 1.7.10-1614.53 (MC: 1.7.10)

**Forge Version:**
1614 - 1.7.10

**Testing**
We are testing a bunch of stuff and it seems like some things are blocked but others are not. So far the Nova Catalyst and Nova Cataclysm bypass protections. Will update this as we test more stuff.

**Comment by Robotia** [comment]
This is because they are explosions. Thermos already custom sends an explosion prime event for Bukkit which these plugins do not check but should.

Look at the TCPR fixes repository, the fixed version of factions checking these is available. Alternatively, you could cancel all explosion events.
