### ISSUE TITLE
Falling blocks not falling.

### ISSUE THREAD

**Issue by Zilacon** [TCPR/Thermos#271]
**Explanation of issue:**
Place sand. Sand turns into "Falling Block" and does not fall.

**Modpack Name:** *(Only if public)*
Tekkit Legends

**Mods Installed:**
Mod list on technic website.

**Plugins Installed:**
WorldEdit, EmptyWorldGenerator, Essentials, LoginSecurity, GroupManager, DeletePlayerData, ConsoleScheduler, WorldBorder, SpawnJoin, Votifier, WorldGuard, MultiWorld, AlwaysDay, AsyncWorldEdit, KaisRandomTP, StopProxy, Vault, TekkitCustomizer, Prism, EssentialsSpawn, MassiveCore, LegendaryMessages, EnjinMinecraftPlugin, Smelter, ChestShop, MCBans, Resurrection, GriefPreventionPlus, RegionForSale, APOCPayday2, SilkSpawners, Legendchat, Factions

**Thermos Version:**
This server is running Thermos | https://github.com/TCPR/Thermos | 1.7.10-R0.1-SNAPSHOT | 1.7.10-1614.53 (MC: 1.7.10)

**Forge Version:**
1614 - 1.7.10

**Comment by Robotia** [comment]
Running Tekkit Legends as well, have never had this problem. Likely a configuration issue

**Comment by Zilacon** [comment]
I believe this is the same issue as #272 so I will just close this.
