### ISSUE TITLE
Entities or Deleted Entities not disappearing.

### ISSUE THREAD

**Issue by Zilacon** [TCPR/Thermos#272]
**Explanation of issue:**
Throw something on the ground, watch it bounce around like a yoyo for eternity. Removing the items using a plugin like world edit or essentials says it removes the entities but it does not remove it from the server. You cannot pick anything up but it still is going up and down left and right basically all over the place acting like a yoyo.

It seems like this also affects any type of flying entity such as arrows, or projectiles from mods. I see projectiles shot from the player going back and forth like a yoyo from the origin to destination over and over.

**Modpack Name:** *(Only if public)*
Tekkit Legends

**Mods Installed:**
Mod list on technic website.

**Plugins Installed:**
WorldEdit, EmptyWorldGenerator, Essentials, LoginSecurity, GroupManager, DeletePlayerData, ConsoleScheduler, WorldBorder, SpawnJoin, Votifier, WorldGuard, MultiWorld, AlwaysDay, AsyncWorldEdit, KaisRandomTP, StopProxy, Vault, TekkitCustomizer, Prism, EssentialsSpawn, MassiveCore, LegendaryMessages, EnjinMinecraftPlugin, Smelter, ChestShop, MCBans, Resurrection, GriefPreventionPlus, RegionForSale, APOCPayday2, SilkSpawners, Legendchat, Factions

**Thermos Version:**
This server is running Thermos | https://github.com/TCPR/Thermos | 1.7.10-R0.1-SNAPSHOT | 1.7.10-1614.53 (MC: 1.7.10)

**Forge Version:**
1614 - 1.7.10

**Comment by Robotia** [comment]
I also run Tekkit Legends and have not had this issue, perhaps it is a configuration issue?

**Comment by Zilacon** [comment]
My config is pretty default from thermos. Only things ive changed are the spigot world settings and enabling bungeecord support.

**Comment by Zilacon** [comment]
Your free to pop on my server to check it out: tleg.apocgaming.org.
I got it whitelisted right now because testing so let me know what your username is and ill add you to the whitelist.

**Comment by Robotia** [comment]
Is this still occurring?

**Comment by Zilacon** [comment]
@Robotia Sorry man been hella busy lately. Ill toss the latest release on my tleg server tomorrow and test it.

**Comment by Zilacon** [comment]
Just tested it, yes this is fixed.
Also looks like the banned item list is fixed too.

But could you add one that removes it from inventory too? Cause i can still craft/drop items on ground/and have items in inventory that are banned.

Thanks for fixing this!

**Comment by Bogdan-G** [comment]
`Cause i can still craft/drop items on ground/and have items in inventory that are banned` client side de-sync -.-

**Comment by Zilacon** [comment]
If that's the case the server never syncs to the client ever with your logic.

**Comment by Bogdan-G** [comment]
synchronizes but with a pause, pause, size standard + server is busy.

**Comment by Zilacon** [comment]
So again with your logic my server has never synced with my client once within 30 minutes.
My servers dont lag bro, get off your creeperhost. XD

**Comment by Robotia** [comment]
@Zilacon he runs very good servers, his English is just not very strong so it is difficult for him to explain 

He means that when the server lags, the client does not receive network updates -- hence why items might appear to still be around. I have had similar networking problems when I was on 1.5.2, my commands worked when sent but my client never updated visually. It randomly fixed itself after several days and only affected me.

@Bogdan-G игнорируй его :stuck_out_tongue:

**Comment by Zilacon** [comment]
@Robotia But you yourself told me to use a plugin to delete banned items on the ground or in the inventory completely voiding this entire conversation.

De-syncing has nothing to do with it. The coding for it doesn't exist. Hence why i asked for it to be included within thermos.

And it is psychically impossible for a client to be De-synced for 30 mins and throwing items on the ground and picking them up and tossing them back out of the inventory over and over for 30 minutes. If the server was De-synced from the client i wouldn't be able to pickup the item on the ground at all or even throw it out of my inventory.

**Also telling him to ignore me is as rude as both of you misunderstanding what i requested in this issue.**

**Comment by Robotia** [comment]
You do not understand the meaning of the words when you use Google translate, it is a lightly used connotation....not intended to offend... 

You were offensive, you told him to `get off your creeperhost`... не простил.

And no it is not impossible, strange things can happen with networking in NettyIO. If you had experience with the library in Java, you would understand that

I do not know what you mean by voiding this conversation, but if it is void, I am done replying. Have a good day.

**Comment by Yive** [comment]
#### Deleting previous comments.

The old comments are view-able from email to participants so don't get your panties in a bunch when you don't know what the person replied with.

### Please think before pressing the comment button next time.
