### ISSUE TITLE
ItemStack Error

### ISSUE THREAD

**Issue by LordHalo1157** [TCPR/Thermos#274]
Hey! I have two questions for you, I have looked in to this problem a bit and cannot seem to find a fix for it. I am running Direwofl20, the recommended pack version. When the world trys to save it gives me an error of saving Dim7, which I cannot get due to the console being spammed by a new error since I updated to the new Thermos build. 

The error is:
"28.03 13:17:22 [Server] WARN WARNING: unlocalizedName is deprecated; please use registryName or itemStackName instead!"

Know what mod is causing this? Is it Thermos? Any answers would be appreciated!

**Comment by Robotia** [comment]
This is caused by a mod improperly saving data, not Thermos.
