### ISSUE TITLE
[Crash] Thermos #53 - the server going slow

### ISSUE THREAD

**Issue by linkinkov** [TCPR/Thermos#275]
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
http://pastebin.com/dytjsQLr

**Thermos Version:**
53
**Forge Version:**
1614

**Comment by Robotia** [comment]
Ok, looks like a Thermos' issue, will look into this.

**Comment by linkinkov** [comment]
Thank you :3
Then planning stable release or that build you recommend to use?

**Comment by Harjas2102** [comment]
I have the exact same issue with the same errors coming up in the logs on thermos version 46, not sure if I should have opened a new issue so I'm commenting here first.

**Comment by Robotia** [comment]
@Harjas2102 fix planned for next release

**Comment by vadimyer** [comment]
Strange, B53 everything's fine here.

**Comment by DraksterAU** [comment]
B53 - Everything is lagging like hell, but not all the time.

**Comment by Robotia** [comment]
@vadimyer When the tile entity count is > 20,000,  there are serious performance drops because of the data structure used to contain them. :confused: 
You wouldn't notice it normally unless a bunch of tile entities were unloading at once.

**Comment by vadimyer** [comment]
But but but... I got 150k+ TEs on average ._.

**Comment by Robotia** [comment]
Yup :sunglasses: 
https://github.com/TCPR/Thermos/commit/cf2e582f7de3b0f54923d2dde2bd36607084e8d3 will need testing though

**Comment by linkinkov** [comment]
@Robotia cant compile, can you give test build with last commit to test?

**Comment by Robotia** [comment]
It is broken right now I will need to investigate what's wrong, don't worry I will also test.

**Comment by linkinkov** [comment]
@Robotia thank you!

**Comment by DraksterAU** [comment]
Getting this with less than 5k TE's loaded.
Server is fine for about a minute, with no players, then it just slows to a grinding halt.
Downgrading for now.

**Comment by iKaneki-Ken** [comment]
@DraksterAU What modpack are you hosting? As I have anywhere between 12k-20k ticking tile entities at once along with anywhere between 3k-8k entities at once and never get this issue.

**Comment by DraksterAU** [comment]
@iKaneki-Ken Custom. 90 mods that have been running fine since Cauldron.... with minor updates to provide 1614 compatibility.

**Comment by Robotia** [comment]
Fixed in B54. And @DraksterAU you are likely experiencing a placebo effect. I cannot help you if you are just going to say it is slow without a profile log...

**Comment by DraksterAU** [comment]
@robotia How do I set one of these up on a Linux server ?

If someone would be kind enough to explain what to do I will happily.

**Comment by Robotia** [comment]
https://youtu.be/c0ffjooX7Jw
