### ISSUE TITLE
Is world saving fixed? (KCauldron old issue)

### ISSUE THREAD

**Issue by Zilacon** [TCPR/Thermos#277]
First of all i apologize for making so many issues with questions. I was told by numerous devs to make a issue for each question or problem, not sure if thats the same case with you.

Anyways KCauldron had a HUGE problem with world saving. So much that the server load would go into multi-hundreds to even thousand percentages. I found a solution was to make a 5 minute timer do a /save-all command via console to reduce the amount of load the server does when saving worlds. I did this using ConsoleScheduler.

My question is has this been fixed? I reported this to Prototik on his repo like a year ago but they just ignored the problem and it was never fixed.

I just want to know if i can remove the scheduled save i setup and turn on the save settings in the bukkit.yml again.

**Comment by iKaneki-Ken** [comment]
No it doesn't.

**Comment by Zilacon** [comment]
No it doesn't what?
http://timings.aikar.co/?url=11732928
http://timings.aikar.co/?url=11732932
http://timings.aikar.co/?url=11732934
http://timings.aikar.co/?url=11733075
http://timings.aikar.co/?url=11733084
http://timings.aikar.co/?url=11733089

**Comment by iKaneki-Ken** [comment]
Question for you, how many players do you usually have on a single server instance?

**Comment by Zilacon** [comment]
Most on a single server is around 10-15 players. Maybe 20=25 on a weekend.
And the view radius is set to 4 on all worlds/servers.
And all servers have bordered worlds.

**Comment by iKaneki-Ken** [comment]
Are those timings from a KCauldron server?

**Comment by Zilacon** [comment]
Yes.

**Comment by iKaneki-Ken** [comment]
Yes, the save issues have all been fixed on Thermos, not only that, but the performance is immeasurably better. I used to have an issue where random AE2 blocks would randomly disappear while using KCauldron, that doesn't happen on Thermos at all.

**Comment by Zilacon** [comment]
So it is safe to use the world saving located in the bukkit.yml?
Because i do not want to repeat those timings from KCauldron XD

Also really hope the instant-removal is fixed soon so i can get rid of TekkitCustomizer another lag issue.

**Comment by iKaneki-Ken** [comment]
Yes, I've been using it for the last 2 months now and legitimately no issues whilst using Thermos.

**Comment by Zilacon** [comment]
Alright good to know, thank you.
