### ISSUE TITLE
Forge Worldedit // commands dont work

### ISSUE THREAD

**Issue by Cracks777** [TCPR/Thermos#278]
When using the Forge version of worldedit the // commands say they dont exist. the single / commands do work tho. tested this in forge and they work fine.

Edit: Tested on a normal forge server and everything works, i think this may have something to do with the fix to keep forge from bypassing bukkit? not sure tho but it does register permission nodes in the log for the commands but in game when the commands are used it tells that they dont exist.

Removed all plugins and no change. 

Using Build 53.

**Comment by Time6628** [comment]
Are you opped? Do you have bukkit WE and Forge WE?

**Comment by Cracks777** [comment]
yes im an op, its my server, if you read what i posted, i removed all plugins, and it is telling me that the commands do not exist.

**Comment by Time6628** [comment]
Add bukkit WE and see how that goes.

**Comment by Time6628** [comment]
Add bukkit WE and see how that goes.

**Comment by Cracks777** [comment]
even with the the bukkit version installed it tells me the commands do not exist. if i remove the forge version the commands work fine again, the reason i want the forge version is so that i can copy carpenters blocks, when i copy and paste them with the forge version they are all faced the wrong way and blank, im using the correct version of world edit for bukkit but the blocks still paste wrong.

**Comment by Cracks777** [comment]
Fixed it.

**Comment by Robotia** [comment]
What was the issue?

**Comment by Cracks777** [comment]
i had to have the forge version and the bukkit version both installed, with it setup like that the forge version does all the heavy work and bukkit does the permissions.

**Comment by Cracks777** [comment]
but it copys all blocks correctly now.
