### ISSUE TITLE
[Suggestion]Server with Multi-Core CPU

### ISSUE THREAD

**Issue by ccxufo** [TCPR/Thermos#280]
I've been using this server for a long time,though Thermos have done lots of  performance optimizationss,I still feel lag when players up to 80~100. The fundamental reason is the server does not support concurrent computing.
A Taiwanese has build a multi-core-supported server which based on spigot. It's can bring superfast loading speed,the entity and redstone have a hug improve as well.          
I thought Thermos should have a need for developers to improve it.I wish this could help you. 
The link about multicore server:  
www.reddit.com/r/admincraft/comments/49tvti/hose_a_spigot_patch_to_more_effectively_utilize/

Guihub : 
https://github.com/softpak/HOSE

**Comment by Robotia** [comment]
@ccxufo that is part of the problem, but that is not the main issue....the main problem is poorly written mods. Thermos can only do so much to prevent lag created by poor mod code.

This is interesting, but we need more developers, so right now bug fixes take higher priority. I am sorry. :confused:

**Comment by LemADEC** [comment]
https://github.com/nallar/TickThreading already covers this, but it's skipping 1.7.10.

**Comment by iKaneki-Ken** [comment]
First mistake is trying to cram 80 to 100+ players into a single server instance, especially on 1.7.10, you may be able to pull it off on 1.6.4, but certainly not 1.7.10.

**Comment by wormzjl** [comment]
try to use bungeecord

**Comment by bookerthegeek** [comment]
On vanilla maybe you can pull 100 players, but not modded. Although we are running 40+ on INF Skyblock right now. But bungee cord sure does help.

**Comment by Robotia** [comment]
This is irrelevant discussion at this time, bug fixes take priority. Sorry, but I am one guy and this cannot be done.

**Comment by Bogdan-G** [comment]
minecraft one-theread, JVm use all CPU core.
