### ISSUE TITLE
World Save Error?

### ISSUE THREAD

**Issue by LordHalo1157** [TCPR/Thermos#282]
Whenever a player on my server goes into another world that isn't the End or Nether they crash along with the server crashing. At times they are able to get in the world refuses to save. I've checked every possible thing it could be, I even changed the dim ids of dimension 7 and all other dimensions, that seemed to not work. Also tried reloading the dimensions with their default ids, still didn't work.  

The pack played:
Direwolf20: 1.0.10 - Recommended Version, 14gb of Ram allocated

When my server saves it gives me the following error:
01.04 10:38:40 [Server] WARN net.minecraft.world.MinecraftException: The save folder for world ./world/DIM-7 is being accessed from another location, aborting
01.04 10:38:40 [Server] WARN at net.minecraft.world.storage.SaveHandler.func_75762_c(SaveHandler.java:99)
01.04 10:38:40 [Server] WARN at net.minecraft.world.World.func_72906_B(World.java:4303)
01.04 10:38:40 [Server] WARN at net.minecraft.world.WorldServer.func_73042_a(WorldServer.java:1118)
01.04 10:38:40 [Server] WARN at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1084)
01.04 10:38:40 [Server] WARN at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:532)
01.04 10:38:40 [Server] WARN at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:856)
01.04 10:38:40 [Server] WARN at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:683)
01.04 10:38:40 [Server] WARN at java.lang.Thread.run(Thread.java:745)

I've looked for a fix in many different locations even in the mod claimed to be causing the issue. In many of the sites I've looked at to find a fix, claim it's an error with Factorization version 0.8.88.8.8888, and Cauldron.  

Now please don't say "It's not our problem its a mod problem get out." I thought the point of this was to actually help improve the performance of modded servers and help find bugs. The next step after this is contacting the mod dev, but like many mods devs they're going to say "We don't support Cauldron or any fork of forge/bukkit." 

- Hope you'd all give me tips or help in finding help on the issues as i'm sure i'm not the only one having it.

LordHalo

**Comment by DraksterAU** [comment]
@LordHalo1157 

`Whenever a player on my server goes into another world that isn't the End or Nether 
`
Are you running any mods or plugins specifically that add extra dims? What are they? What is running as DIM-7? Twilight Forest?

`01.04 10:38:40 [Server] WARN net.minecraft.world.MinecraftException: The save folder for world ./world/DIM-7 is being accessed from another location, aborting`

This is usually caused by backups running, or some other process writing to the folder in the background, not minecraft, mods... and *usually* not the server itself. Are you sure there is nothing running?

`Now please don't say "It's not our problem its a mod problem get out." `
You wont get that here. @robotia rocks.

What is your Thermos Version?

Does this occur without Factorization installed? Can you clone your server and run a copy without that mod and have no errors like the one mentioned above?

I'm not a dev, but just asking questions that will probably be asked for troubleshooting.

**Comment by Cracks777** [comment]
i get this too but with a different dim, i even changed the dim number in the config and it still did it. i had to disable that dim all together to get it to stop.

**Comment by DraksterAU** [comment]
@Cracks777 What Mod was loading the DIM? Did recreating the DIM work?

**Comment by Cracks777** [comment]
galaxyspace was the mod that was adding the dim on mine, and no nothing i could do fixed it, changing dim numbers, deleting that dim and recreating it, so i just turned it off in the config.

**Comment by LordHalo1157** [comment]
Yes, nothing is running when it trys to save. It won't save on server restart either.  I will try running it without the mod later tonight. But this happened on other packs running that factorization version, stated by someone on a different git. He said the only fix he found so far was downgrading factorization. His dim7 was erroring just like mine. Also @robotia didn't tell me that someone named Sam did clamong it's not our problem and closed my last thread. 

Thanks for the help I really appreciate it!
- LordHalo

**Comment by DraksterAU** [comment]
@LordHalo1157 Sam is @Robotia. He'd only say that if it was genuinely not a Thermos issue.
Dim-7 is loaded and managed by Twilight Forest by default (To my knowledge factorization has nothing to do with dimensions).

**Comment by LordHalo1157** [comment]
This is where I found the link to factorization, https://github.com/mechaet/ModderationConfigs/issues/8 It has something to do with the new Hammer API in factorization.

**Comment by DraksterAU** [comment]
What Version of Factorization do you use?

**Comment by LordHalo1157** [comment]
The Version thats in Dw20, 0.8.88.8.8888. It hasn't changed for a year if those dates are correct.

**Comment by DraksterAU** [comment]
Try updating to 0.8.92?

**Comment by LordHalo1157** [comment]
FtB runs the pack, and If i update the mod then all my players on the server have to update as well, I run an FTB community.

**Comment by DraksterAU** [comment]
@LordHalo1157 

Way I see it you have 5 options;

1. Try and compile a custom (server side only) build the mod, that includes the fix in 0.8.92 and/or disables.
2. See if you can disable hammer in configs. 
3. Create a Custom Modpack that includes the updated version
4. Ask FTB to update the modpack (http://www.feed-the-beast.com/support)

Finally..

You could always ask robotia (Sam) to support an out of date version of a specific mod (which has a fix in a later version), but I wouldn't hold your breath :)

[ I've had my 2 cents now ! :P ]

**Comment by iKaneki-Ken** [comment]
Dim -7 which is Factorizations own custom world is what Factorization uses to simulate fake player actions and handle custom packet data. Don't know why the dev decides to do it this way, he just does.

As for Direwolf receiving an update, it's highly unlikely as Direwolf for 1.7.10 is being left in the same state that Monster 1.6.4 was left in. This is personally why I don't like FtB modpacks and will be steering clear of them in 1.8/9.

**Comment by LordHalo1157** [comment]
Well the pack is ran by Direwolf and FTB and since FTB doesn't support Cauldron/Thermos because they're derps.. they would laugh and say no move along lol, and I think all 1.7.10 packs are locked from updates due to the production of 1.8+ packs.

**Comment by DraksterAU** [comment]
@LordHalo1157 I just submitted a request, because you never know (They might update it).
http://forum.feed-the-beast.com/threads/1-5-0-factorization-is-1-year-out-of-date-and-doesnt-include-crashbug-fixes-for-mp.150171/

Use TechnicLauncher. Zip up your own modpack and host it on Dropbox somewhere.

**Comment by LordHalo1157** [comment]
Cool, thanks for your help guys! Its really appreciated.

**Comment by Time6628** [comment]
FTB ModPacks for 1.7.10 have all stopped updating. As for the world error, you are most likely missing the level.dat.
