### ISSUE TITLE
Inconsistencies between Thermos 1558 and Forge 1558

### ISSUE THREAD

**Issue by morphesus** [TCPR/Thermos#283]
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
https://gist.github.com/morphesus/adb960d910e6834e99e1bf96c62a8c73

**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
Junk: https://gist.github.com/morphesus/483c60dc4455ed6f7bbd341f9cbb13e2 (All fine here)
Server: https://gist.github.com/morphesus/d7e2206877a4195f3b96e702556a63a5

**Explanation of issue:**
I'm using the TerraFirmaCraft modpack from ATLauncher ([See here](https://www.atlauncher.com/pack/TerrafirmaPack)). It's run by forge-1.7.10-10.13.4.1558-1.7.10-universal.jar and I tried to migrate to Thermos (Release 54 (Beta), Thermos-1.7.10-1558-server.jar)

The libraries are up2date. With Release 53 (Beta) I got a different output: For this version it seems that Railcraft breaks the functionality. I also tried to generate a completly new world - same issue.

I can share my whole installation, if needed. Please just tell me, I'll upload it and share the link here.

**How to recreate this issue:**
Just create a TerraFirmaCraft Server with the ATLauncher (Pack Code: Terrafirmacraft) and let it run with Thermos.

**Modpack Name:** *(Only if public)*
[Terrafirmapack](https://www.atlauncher.com/pack/TerrafirmaPack)

**Mods Installed:**
Please see the list on the bottom of the page here: https://www.atlauncher.com/pack/TerrafirmaPack

**Plugins Installed:**
None

**Warmroast Report:** *(Optional)*
N/A

**Thermos Version:**
Release 54, Thermos-1.7.10-1558-server.jar

**Forge Version:**
forge-1.7.10-10.13.4.1558-1.7.10-universal.jar

Thank you in advance! :)

Kind regards
Morph

**Comment by Time6628** [comment]
There is no thermos 60. Do you mean thermos 56? Also, I believe back ports are known to be buggy and mostly unstable.

**Comment by morphesus** [comment]
@Time6628 
Oops, sorry I mean 54 (Beta). This one: https://github.com/TCPR/Thermos/releases/tag/54

**Comment by Time6628** [comment]
Try using Build 54, 1614.

**Comment by morphesus** [comment]
Hi @Time6628 

No luck so far, same issue :/

**Comment by Time6628** [comment]
Oh, my bad. Remove mobiuscore and opis from your server.

**Comment by morphesus** [comment]
@Time6628 YOU GOD DAMN LIFE SAVER!! :D It's working! Didn't saw that these mods are installed.
Thank you VERY MUCH! :)
