### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by Beshelmek** [TCPR/Thermos#285]
**Server Log:** *[Crash](http://pastebin.com/zRHQWGZS)*

**Explanation of issue:** I'am creating some mods, but him can't write string to nbt

**How to recreate this issue:** I dont know

**Modpack Name:** *(Only if public)*

**Mods Installed:** Buildcraft and etc.

**Plugins Installed:** no

**Warmroast Report:** *(Optional)* no

**Thermos Version:** ca.tcpr:Thermos:1.7.10-1614.46

**Forge Version:** 1614

**Comment by Robotia** [comment]
This is not Thermos' fault.

setString is a deobfuscated function, use the reobfuscated jar (the one that isn't marked as -dev) when you are making your mod

In `forge/fml/conf/methods.csv`: `func_74778_a,setString,2,Stores a new NBTTagString with the given string value into the map with the given string key.`
It should be that func, not setString.

**Comment by Bogdan-G** [comment]
`DreamUtils-2.0-dev.jar` <-
