### ISSUE TITLE
Flood figures

### ISSUE THREAD

**Issue by evgeny3121** [TCPR/Thermos#286]
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
http://pastebin.com/qjCR7tD0

**Thermos Version:**
54

**Forge Version:**
1614

After installation 54 thermos in the console flood has begun figures. On the 53 thermos it wasn't.

**Comment by Time6628** [comment]
Could you post your the fml-server-latest.log with the numbers?

**Comment by evgeny3121** [comment]
http://pastebin.com/hx67B8y1

**Comment by Time6628** [comment]
The numbers are coming from ThaumicTinker, I don't think this is a thermos issue.

**Comment by Robotia** [comment]
Determined to be caused by a mod, not Thermos, closing.
