### ISSUE TITLE
Floppy disks resetting on server reboot?

### ISSUE THREAD

**Issue by astrophylite** [TCPR/Thermos#287]
**Server Log:** can't find it ??

**FML Log(s):** http://pastebin.com/KbjUDRwK

**Explanation of issue:** I can create floppy drives but when I reboot the server - all them floppy disks change black and all code gets removed from them.

**How to recreate this issue:** Load the latest version of Thermos 1.7.10 with ComputerCraft and try to create floppy disks then restart the server.

**Modpack Name:** *(Only if public)* -none-

**Mods Installed:** The Hunt, BiblioCraft, ComputerCraft, CustomMobSpawner, Mo' Creatures, Microblocks, MalisisDoors, Mr Crayfish's Furniture Mod, No Ice Melt (doesn't work), Wireless Redstone (CB Edition).

**Plugins Installed:** BlockAnvilRename (custom plugin), Essentials (and all addons), FastAsyncWorldEdit, floAuction, ItemCase, LWC, Multiverse-Core, PermissionsEx, PlayerVaults, PlotSquared, ShowCaseStandalone, Vault, WhatIsIt and WorldEdit.

**Warmroast Report:** *??*

**Thermos Version:** 1.7.10-1614.46

**Forge Version:** 10.13.4.1614

**Comment by ArcasCZ** [comment]
Is it still actual?

**Comment by Robotia** [comment]
Did you try this on a MinecraftForge Vanilla server?

**Comment by ArcasCZ** [comment]
Actually on latest KCauldron this is not happening...

**Comment by Robotia** [comment]
Is it happening on Thermos?

**Comment by astrophylite** [comment]
It's not happening anymore after updating to the latest version of Thermos.

**Comment by Robotia** [comment]
Awesome, glad it is fixed!
