### ISSUE TITLE
Random item disappearing from the inventory

### ISSUE THREAD

**Issue by vadimyer** [TCPR/Thermos#291]
**Explanation of issue:**
Some time ago the weird chunk saving issue was successfully resolved, but I guess since the first build of Thermos I used (B30+) the problem with weird inventories still exists (the problem is in random item disappearing. And probably dupe - that is not confirmed). Today one player dropped the item to another player - and that other picked up the item, but didn't actually get it in the inventory, so it just disappeared.

I also heard reports that items just randomly disappear from the inventory under uncertain conditions.

**How to recreate this issue:**
Don't really know because as I've said, people can't explain, items just disappear =^_^=

**Mods Installed:**
https://s.vadimyer.com/11152045-26be-4e33-840a-0493accb5df0.png
https://s.vadimyer.com/adcfcc96-566d-485e-a03c-844ba2101a62.png

P.S. And InvTweaks installed on client only.

**Plugins Installed:**
https://s.vadimyer.com/70dca662-435e-478f-abc7-5d98138274f3.png

**Thermos Version:**
B54

**Forge Version:**
1614

**Comment by Robotia** [comment]
If this was happening before B5X, it is not the stack size 0 thing, that was only implemented recently.

Could you please provide a GIF/video reproducing the issue so I can understand it better? Thanks!

**Comment by linkinkov** [comment]
Its because you use DupeFixer with InventoryTweaks. Inventory Tweaks change some packets that send from client to server, DupeFixer check inventory every tick and thats why you lose something in inventory. With ModFix same problem. Just remove Inventory Tweaks.

**Comment by vadimyer** [comment]
Ah thanks, makes sense now. Is there at least an alternative for Inventory Tweaks? Because it's such a crucial mod players would really become mad it I remove it.

**Comment by bookerthegeek** [comment]
Pick whichever one is least important to your server, and remove it. :)

That being said, should problem be reported to both devs so a fox can be made,  if possible.

Also, link to duper fix?

**Comment by Robotia** [comment]
You mean the fix I made or dupe fix?

**Comment by Robotia** [comment]
(And issue resolved)

**Comment by bookerthegeek** [comment]
;) I'll see your fix in code. I was looking for the plugin.
