### ISSUE TITLE
Can't Shear Leaves

### ISSUE THREAD

**Issue by DiggyWig** [TCPR/Thermos#295]
**Explanation of issue:**

Using shears on leaves just breaks the leaves, they don't drop as they should. 

**How to recreate this issue:**

Try and shear some leaves (any tree type).

**Mods Installed:**  & **Plugins Installed:**

Various but none that change shear behaviour, tested without any plugins and still occurs.

**Thermos Version:**

53

**Forge Version:**

1614

**Comment by Robotia** [comment]
Confirmed by multiple people on Discord

**Comment by alicheek** [comment]
Can confirm also :)

**Comment by Kadell** [comment]
Can confirm, on a brand new install of infinity skyblock thermos 1614.53 no plugins, all shears except botania and gravisuite chainsaw do not harvest leaves.
