### ISSUE TITLE
The server is going slow

### ISSUE THREAD

**Issue by Harjas2102** [TCPR/Thermos#299]
**Server Log (Pastebin) :** http://pastebin.com/v5dVHiaG

**Explanation of issue:** Server would kick players and stop responding. This was a issue in previous versions, and Thermos Version 54 stated that it was fixed. But it still occurred multiple times, after upgrading to Version 54.

**Thermos Version:** 54

**Forge Version:** 1614

**Comment by Robotia** [comment]
Talked with at @Harjas2102 on Discord and noted the following:
+ Problem is likely because of poor mod saving code
+ Server hangs on file closing, could be file permission issues
+ Private server on Windows 10 desktop computer so HDD may not be optimal

**Comment by Time6628** [comment]
timeout-time: 900 or more in spigot.yml

**Comment by Harjas2102** [comment]
Fixed this by removing certain mods mentioned by @Robotia .
