### ISSUE TITLE
[1.7.10] Packet was larger than I expected, found 40229 bytes extra whilst reading packet 53

### ISSUE THREAD

**Issue by lightning02** [TCPR/Thermos#302]
Forge: 1614 
Thermos: 1614-build 54 (i didn't go for build 55 because it was a really early beta, but i can switch if this could solve the problem)

On the client side the problem look like this: after copied some massive buildings on an area of 15x15 chunks and after modifing or adding some more thing the problem doesn't occurr, but when you disconnect from that area and try to reconnect the ammount of data of the streams is maybe to big to be sent all in once.
But also people that teleport or run to does chunks fall in that disconnection problem and they can't join again. 

http://pastebin.com/QwGfVzMM  [this is kinda what happens on client side, the logs on server console seems to be not so detailed]

I noticed, looking around that this error happened in 2014 and was related to forge. unfortunately they claims to have fixed that or at least LexManos in December 2015 was still asking if someone was still having the problem but then he locked the github thread; and as we know he is not glad to offer support for 1.7.10 anymore. 

Is there something that can be done on the Thermos side in order to handle the big ammount of datas from great modpacks? 

EDIT: I've tryed also Thermos build 55 without success, the issue persist. 
![415bfecbe5273bc0bf23670db764ff3e0ffb84a45db57d3f23 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/11884147/14579747/cc97d6b0-03b5-11e6-9bbb-2a9162ddf42b.png)

**Comment by Robotia** [comment]
The problem with this is that Minecraft places a 32kB limit on packet size. Try reducing the maximum bulk chunks in spigot to 1

**Comment by lightning02** [comment]
I've tryed just now and i may gain 1/2 more second when I log in but then i'm being kicked. Now with 41486 bytes extra (but it depends sometimes are 41360 [depends where i look at/move])

**Comment by lightning02** [comment]
Ok, after digging more into the problem i discover some interesting things. the problem occur in an area of about 290 blocks within the "corrupted" chunk.
The very interesting things are that: 
1) Only happen on server giving that error
2) Chunk render distance does not affect or infuence/avoid the issue
3) Only the coordinates of the player matter (for example if any player approc the corrupted location and reach a chunk within 300 blocks from the corrupted one it get kicked from the server with that error, no matter the render distance they have in video settings)
![ale 1](https://cloud.githubusercontent.com/assets/11884147/14581309/da547cf2-03e9-11e6-8c5b-360972987f7d.png)
Anyway i've also loaded the server world in single player and i've located what corrupted the chunk.
It is some blocks from Chisel 2 (in particular factory block) that now appear to be invisible.
![andre 2](https://cloud.githubusercontent.com/assets/11884147/14581302/b7d0ff70-03e9-11e6-8482-d075e3256e23.png)
I don't know how and when it happened, I only know that does blocks were made using the set command of worldedit, but they were fine for a while in fact they didn't get corrupted immediately.
I than manage to edit and remove the corrupted part with MCEdit and actually the world work again on server  and people don't get disconnect.
![8ahmjuy](https://cloud.githubusercontent.com/assets/11884147/14581336/7a750788-03ea-11e6-8db3-a30c8e6dd559.png)
I guess i should move this issue to Chisel 2 developer, shouldn't i?

**Comment by Time6628** [comment]
Try installing worldedit forge for 1.7.10. It works along side Bukkit WorldEdit but WE Forge does all the block editing and bukkit does all the command/permission handling. And since WE Forge is handling all the block stuff, currupted/buggy blocks are less likely to happen(in my experience).

**Comment by lightning02** [comment]
I've tryed WorldEdit-Forge 6.0 beta for 1.7.10 but i guess i did something wrong in the installation because it crash the modpack if I put it in mods folder and it does not take any effect if throwed in the plugin folder.

**Comment by Time6628** [comment]
WorldEdit-Forge is a FORGE mod... it should go in the mods folder... it won't do anything in the plugins folder because its not a plugin.

**Comment by lightning02** [comment]
As i thought, i did it right, then it just crash for me. 
![d40a61c8e9ef5851209be1430f4ff3bd34a98e98e39631753b pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/11884147/14582206/e475705a-03fe-11e6-995d-b3a2ec99abe5.png)

**Comment by Time6628** [comment]
Could you show the actual crash-log instead of the console?

**Comment by lightning02** [comment]
It does not generate a crash report. I'll give you the latest log instead http://pastebin.com/Z4sudaex

**Comment by Time6628** [comment]
http://builds.enginehub.org/job/worldedit/8752/download/worldedit-forge-mc1.7.10-6.1.1-SNAPSHOT-dev.jar
Try that one.

**Comment by lightning02** [comment]
This time at least it generate a crash report. http://pastebin.com/JV9r3xHe

**Comment by Time6628** [comment]
My bad, I believe this is the correct one http://builds.enginehub.org/job/worldedit/8752/download/worldedit-forge-mc1.7.10-6.1.1-SNAPSHOT-dist.jar

**Comment by lightning02** [comment]
Even with the version you sent me and even deleting the old WorldEdit config file, it crash and this time again does not generate a crash report.
http://pastebin.com/GYxppBXi

**Comment by Robotia** [comment]
What mods do you have installed? Are there modded blocks in those chunks?

**Comment by lightning02** [comment]
More or less the list of mods is this: http://pastebin.com/pjhUM7g6 
Anyway i figured out wich block got corrupted, it was one from chisel 2 (v2.5.1.44)
![8f330b44508278aedabf2745bec7b40fecc22a1b63d9057691 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/11884147/14584105/45920d16-0437-11e6-82fe-6858e1edb045.png)

**Comment by Time6628** [comment]
Glad you got it fixed! :cat:

**Comment by linkinkov** [comment]
Update: **http://minecraft.curseforge.com/projects/chisel/files/2287442**

**Comment by lightning02** [comment]
There is a weird spam in the console 
![fc00b2dfa99413efde224cb594cd868682cad81a6e33d35394 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/11884147/14586260/d2d91c54-0492-11e6-981f-37db7cbbc90b.png)

**Comment by Robotia** [comment]
:confused: Thermos could limit the packet size to 32kB but then you would never know if data is lost in transit.

**Comment by iKaneki-Ken** [comment]
I'm noticing a lot of weird crashes occur while using Mac with Minecraft.

**Comment by lightning02** [comment]
Anyway in effect a possible data loss would be worse...
We are in windows :) and the server is on linux!

**Comment by Bogdan-G** [comment]
I'm sorry, what? obviously with mods of data it becomes many times more! Including the size and number of packages.

**Comment by Time6628** [comment]
Going to close this issue as it appears to be resolved.
