### ISSUE TITLE
Right click dupe bug (since vanilla 1.2)

### ISSUE THREAD

**Issue by djoveryde** [TCPR/Thermos#305]
Thermos version 1614.52

There is a major bug which has been around since vanilla 1.2 which causes your inventory to dupe.
From what I can gather you hold down shift or the drop key then leave the server or restart it. It causes the server to think you are always holding that key down and then you end up with both The item in your inventory and on the floor.
This happens more commonly with server plugins like say a market plugin that has its own inventory.

I noticed that #62 is the exact same issue. However will this have fixed that issue relating to plugins that store inventory serverside as well?

**Comment by Robotia** [comment]
It was fixed, please read the release notes for versions newer than your current installed one in the future. Thanks!
