### ISSUE TITLE
Thermos 1614.55 bags will dupe items

### ISSUE THREAD

**Issue by djoveryde** [TCPR/Thermos#306]
Not sure if this is fixable or not but if a mod has something that stores inventories like say the backpacks mod then if a player is given another backpack it will stack and duplicate the original backpack into the second backpack.
Happens with thaumcrafts bags also.
Is it possible wether thermos could do a check to see if an item has the ability to store inventory then it will force it to be an unstackable item?

**Comment by Time6628** [comment]
I cannot reproduce this with golden bags of holding. Could you show your plugins?

**Comment by Robotia** [comment]
The mod author would need to do this, thought it is indeed a generally occurring type of duplication glitch, different authors use different bag implementations and I would not want to mess with that behavior.

**Comment by djoveryde** [comment]
It's part of the donation kits so when a player does /kit soandso it gives them a backpack which seems to be placed over to top of their existing bag, this in turn duplicates it. I'll send the mod author an issue report on it :)

**Comment by bookerthegeek** [comment]
Use a bag that does not stack when empty. Also what are you using for your kits?

**Comment by Time6628** [comment]
Essentials will automatically stack items that are similar. For example, /i <bag> 1 and then do /i <bag> 1, because the two items are similar, essentials will put them together. This is the same way for kits. 
Try to setup your kit items like this:
```
items: 
  - bag 1
  - bag 1 lore:&1
  <whatever else is in the kit>
```
This will cause the bags to not stack because one of them has the lore of &1, which does is a color code, but there is no text to apply the color code to so it will be blank.

**Comment by bookerthegeek** [comment]
Also, chests work great for kits instead of bags.

**Comment by djoveryde** [comment]
As the kits are daily if the bag had a lore would that naturally prevent it from stacking?

**Comment by Time6628** [comment]
Yes.

**Comment by iKaneki-Ken** [comment]
This isn't a bug, depending on how items are spawned in, if they share the same data, they'll stack, even if the item normally isn't supposed to stack.
