### ISSUE TITLE
Add "Instant-Inv-Removal"

### ISSUE THREAD

**Issue by Zilacon** [TCPR/Thermos#307]
Like the current world instant removal add a inventory one that removes items from the inventory when it enters it.

Also add the item drops or item entities laying on the ground to the world instant removal.

Also if possible add a chat event for the inventory and blockplace event for any banned items. So when someone tries to place a banned block down it will say in chat "&cThe item (ID/Name) is banned." and when its removed from their inventory "&cThe item (ID/Name) is banned and has been removed from your inventory."

**Comment by Time6628** [comment]
Have you tried a banned items plugin?

**Comment by Zilacon** [comment]
Im using Tekkit Customizer right now and the amount of server load that thing puts on the server is unreal. Other plugins are just as bad. Which is why i was excited to see Thermos implementing a similar banning system to get rid of these lag inducing plugins.

**Comment by Time6628** [comment]
Try ItemRestrict. I haven't had any problems with it decreasing server performance.

**Comment by Zilacon** [comment]
Tried that. It does decrease performance. They have endless loops that check every block in every chunk which takes a ton of server cpu usage.

**Comment by DiggyWig** [comment]
I use BanItem personally. It works flawlessly and I find that it barely adds to CPU use at all, less than 0.1% when we did a with and without comparison (with 10 players). Worth trying if you haven't already.

**Comment by Zilacon** [comment]
Banitem has stopped development at 1.7.2.

**Comment by DiggyWig** [comment]
Version 2.8 is listed as 1.7.2-R0.3 but works absolutely fine with 1.7.10, in fact I even know a few people using it for 1.8.x without any issues.

**Comment by Time6628** [comment]
Bukkit plugins usually work with newer versions even if they are for an older version.

**Comment by Robotia** [comment]
I use both BanItem and ItemRestrict. Don't use the world removal, use the one available in Thermos, which does not need to "get" each block. Concerning lag, it is mostly a placebo effect -- the majority of lag for us is mod-related. Maybe at 100+ players you would begin to notice something, but at less it is unlikely.

**Comment by bookerthegeek** [comment]
You can also set most item restriction plugins to check chunk only on load.
