### ISSUE TITLE
Config option to SHUTDOWN when watchdog thread detects deadlock.

### ISSUE THREAD

**Issue by Zilacon** [TCPR/Thermos#308]
As the title states instead of offering to "restart from script" replace it with "shutdown on deadlock". Many scripts these days that run servers including mine already have "if true then else if" loop scripts that will restart the server automatically once the process has been shutdown. And from my experience with server hosts all of their consoles are setup like this as well.

By attempting to restart with the same script that it is running on it creates phantom scripts on my server. Basically multiple start scripts running all constantly restarting over and over due to port bind failure due to multiple processes trying to find to the same port. This creates a massive amount of cpu usage and even forces me to shutdown every single server of mine to track down those additional "SH" scripts running.

TickThreading has a simple "shutdown on deadlock if it cannot recover in 30 seconds" option and has worked great for years for my older servers. It will also notify players in chat that the server has deadlocked.

**Comment by Robotia** [comment]
This is not necessary, if the restart script is not found, the server cannot restart so it will just shut down. Rename it to something that isn't a file in your server directory.

**Comment by Zilacon** [comment]
Oh ok. On spigot its different it will just hang there for eternity if there is no restart script.

**Comment by Bogdan-G** [comment]
do not use the built-restarter, use an external script to do so. The server is better to stop and then start, so there will be less problems and data loss.
