### ISSUE TITLE
Multiverse Inventories keeping same inventory; ignoring groups

### ISSUE THREAD

**Issue by xJonL** [TCPR/Thermos#315]
**Server Log:** 
https://gist.github.com/7bea6f8cc91b0946e2a366bd6e97590e
**FML Log(s):** 
https://gist.github.com/4fd1107f32bc2067e4d271eb9561e2ab
**Explanation of issue:**
Plugin works fine with Spigot/PaperSpigot however with Thermos, it seems to ignore inventory groups.
**How to recreate this issue:**
Create a world with multiverse and make sure to exclude it out of your groups.yml for example here is my config https://gist.github.com/xJonL/0f658d81675975798aa34f0ea5e4a538
Anyways when teleporting between worlds, you keep the same inventory rather it keeping it separate.
**Modpack Name:** *(Only if public)*
N/A
**Mods Installed:**
Aether II 1.7.10-1.6
**Plugins Installed:**
Multiverse-Core-2.5, Multiverse-Inventories-2.5, Multiverse-Portals-2.5
**Warmroast Report:** *(Optional)*
N/A
**Thermos Version:**
Thermos Build 54 (BETA)
**Forge Version:**
10.13.4.1614

**Comment by djoveryde** [comment]
Try using Multiverse 2.4 versions. 2.5 doesnt like Thermos

**Comment by Time6628** [comment]
I'm no multiverse expert but wouldn't setting `share: all` make all worlds share inventories...?

**Comment by Time6628** [comment]
Multiverse inventories is no longer being supported my multiverse, try https://www.spigotmc.org/resources/per-world-inventory.4482/ :cat:

**Comment by xJonL** [comment]
All right thanks for the replies, I will try later and reply is this fixed it or not, hope you don't mind me keeping it open for a bit more

**Comment by xJonL** [comment]
Hey guys just wanna say these works, thanks for the help!

**Comment by Robotia** [comment]
Awesome, glad your problem was solved!
