### ISSUE TITLE
Thaumic Energistics golems crashes the server.

### ISSUE THREAD

**Issue by djoveryde** [TCPR/Thermos#319]
**Server Log:** 
http://pastebin.com/ABqHnkpN

**Explanation of issue:**
Placing golems crashes the server. THis is a new crash only occurred since updating thermos to 55

**Modpack Name:** *(Only if public)*
Hexx Reloaded

**Thermos Version**
55

**Forge Version:**
1614

**Comment by linkinkov** [comment]
Because AE2 need rv3 version, not the stable rv2

**Comment by fewizz** [comment]
No, bcs Thaumic Energistics need Java 8

**Comment by djoveryde** [comment]
Yup that was exactly the answer, didn't realise my core was still using java 7.
