### ISSUE TITLE
[Need Help] HQM Mod not work well with Thermos

### ISSUE THREAD

**Issue by Dream-Master** [TCPR/Thermos#322]
Hi everyone

Your guys are the last chance I have to let HQM(Hardcore Questing Mod) in my Modpack. 
I have a Modpack GT New Horizons (link below) which using HQM Mod (link below) and others. The Mod authors not support Thermos but most of the Servers running Thermos, KCauldron, Cauldron, Bukkit etc.
The Mod support only Forge but who use this on a Server?

From time to time for no reason the files get corrupt (after a Modpack update or only when I add some new Quests) and crash the server. The only way is to delete the Quest save file and start from scratch. People on my Server get board allot. 

I know is not your mod and I know its maybe the wrong place but maybe you can get me helped with that, a fix or a advice.

Thanks in advance.

HQM Mod:

https://github.com/lorddusk/HQM

HQM Issue:

https://github.com/lorddusk/HQM/issues/177

CRASH report Server:

https://gist.github.com/Dream-Master/c608639dce437bcb43ccf9a5d261b0d1#file-hqm-crash

FML Server log

https://gist.github.com/Dream-Master/05f67c1f282368ae28ea7f97d39c18fc#file-fml

Modpack and Mods :

https://github.com/GTNewHorizons/NewHorizons
http://www.technicpack.net/modpack/mcnewhorizons.677387

Thermos Version 56 with older version I get the same error.

Froge Version 1614  Minecraft 1.7.10

**Comment by Time6628** [comment]
This is a problem with the HQM mod itself, not thermos.

**Comment by Robotia** [comment]
1 of the files is corrupt it seems, is there any HQM specific data you can delete?

**Comment by Time6628** [comment]
Deleting world/HarcdCoreQuesting will fix this issue.

**Comment by Dream-Master** [comment]
I know how i delete this file but then People start from 0. So then i will drop HQM.

Thanks
