### ISSUE TITLE
Server not creating a world file

### ISSUE THREAD

**Issue by MrTestificate1** [TCPR/Thermos#324]
**Explanation of issue:** The server when i have installed thermos does not create a world file in the root directory rather it just sticks everything into the root directory so commands like /home and /spawn don't work because of it.

**Thermos Version:**
Thermos-1.7.10-1614-55

**Forge Version:**
1614

**Comment by Time6628** [comment]
Can you send us your server.properties?

**Comment by MrTestificate1** [comment]
yes (wouldn't let me upload the file so i pastebinned it)

http://pastebin.com/0v6kBFDj

**Comment by Time6628** [comment]
```level-name=world```
