### ISSUE TITLE
Projectile not firing

### ISSUE THREAD

**Issue by Shybella** [TCPR/Thermos#42]
Having a issue with projectiles not firing unless the target is a block. If you try to fire with no block present it will not shoot. 

Happening with mods 

Tinker's Construct 
DivineRPG

Offical KCauldron has this issue aswell.

**Comment by Shybella** [comment]
Also does not fire at mobs.

**Comment by Robotia** [comment]
@Shybella Have you tested this on Vanilla Forge?

**Comment by Shybella** [comment]
Works on Singleplayer and Vanilla Forge. 

Also found this
https://gitlab.prok.pw/KCauldron/KCauldron/issues/150

**Comment by iKaneki-Ken** [comment]
Can confirm what @Shybella is saying, this has been an issue with KCauldron for the last 3~ months, still hasn't been fixed.

**Comment by Robotia** [comment]
@Shybella and @iKaneki-Ken I will look into this, can't promise anything yet though.

**Comment by iKaneki-Ken** [comment]
Tis all good, take your time, you're doing this without expecting anything in return.

**Comment by Robotia** [comment]
This is a very interesting problem...I wonder what was done to cause it 0.o

**Comment by Robotia** [comment]
Redstone Arsenal's Flux-Infused Bow works perfectly. Must be a problem related to custom entity shooting or something.

**Comment by Robotia** [comment]
@Shybella That is something I also will have to fix, I don't think it's related but we'll see.

**Comment by Robotia** [comment]
@Shybella @iKaneki-Ken Just fixed the related QuiverBow issue, ridiculous that that has been around this long and never touched. Will upload changes soon.

**Comment by iKaneki-Ken** [comment]
Wtf. I thought that that would be harder to fix given it's been around for 3+ months.

**Comment by Robotia** [comment]
@iKaneki-Ken :smile: Be amazed!

**Comment by Robotia** [comment]
@iKaneki-Ken https://github.com/TCPR/KCauldron/commit/9a7ac8c5289bb7b1678ce5fd8506df61a43fdfad

**Comment by Shybella** [comment]
Not working for me on latest build.

**Comment by Robotia** [comment]
I did not fix it yet sorry, otherwise I would've closed this issue.

**Comment by Robotia** [comment]
@Shybella Can you create a video of this where you compare it to a regular minecraft bow?

**Comment by Robotia** [comment]
@Shybella ^

**Comment by Shybella** [comment]
https://gitlab.prok.pw/KCauldron/KCauldron/commit/3b321e311694ed641c34f5a32de3d88c1a298be6

Fixes the problem.
