### ISSUE TITLE
Bees lose data when dropped.

### ISSUE THREAD

**Issue by Time6628** [TCPR/Thermos#49]
When a forestry bee is dropped on version KCauldron-1.7.10-1614.175.3-TCPR-UNOFFICIAL they lose all data and become plain bees with no attributes. This does not happen with vanilla forge.

**Comment by KasperFranz** [comment]
I don't have that issue are you using build 3 - try updating to 12?

**Comment by Time6628** [comment]
Still persists after updating to 12.

**Comment by KasperFranz** [comment]
what modpack are you using?

**Comment by Robotia** [comment]
@Time6628 Did this happen on official?

**Comment by Time6628** [comment]
@Robotia Did not try with official.

@KasperFranz BeeHappy.

**Comment by Robotia** [comment]
@Time6628 Please try the official.

**Comment by Robotia** [comment]
@Time6628 Also, please provide a video.

**Comment by Time6628** [comment]
I will try the official when I can. Also this affects botania flowers as well.

**Comment by Time6628** [comment]
https://www.youtube.com/watch?v=4sZwvjASAl8 - Video

**Comment by Robotia** [comment]
@Time6628 Can you try something for me? Move the bees around in your inventory and between chests. I want to see if that resets the data, or if it's just when it drops itself.

**Comment by TerdyTheTerd** [comment]
Interesting, just tested on my fresh KCauldron release 13, with bees and botania flowers, the data stayed the same. Wonder if another mod is messing with the data, but from looking at the modpack mods there is only 2 or 3 mods that aren't already running on my server. Did you add any server side mods?

**Comment by iKaneki-Ken** [comment]
This is a HQM mod issue. HQM has been knowning for causing issues with item data structures. Same issues happen with Agrarian Skies 2 and all other modpacks that use HQM.

**Comment by Time6628** [comment]
@iKaneki-Ken Is there a way to fix it? I have another pack that has HQM, Botania, and Forestry and it does not happen there.

@Robotia I will test in a moment.

**Comment by iKaneki-Ken** [comment]
It all really depends on how the modpack devs programs it. All in all I can confirm this isn't a KCauldron issue as I have 6 different servers using Forestry and I don't have this issue with bees or Botania.

**Comment by TerdyTheTerd** [comment]
Must be a pretty specific issue, I wonder if it only occurs if you have bee's or flowers selected as target items in the quest system, my pack also has HQM but does not have quest yet that uses flowers/bees. I would assume if the items retain data by moving them between inventories then there is an issue with onItemPickUp or EntityItemPickupEvent maybe resetting nbt data or not properly storing/passing it. Either way looks like you better hit the devs up over at [HQM](https://github.com/lorddusk/HQM/issues)

**Comment by Time6628** [comment]
@TerdyTheTerd My other pack that does not have this issue has quests for bees and with bees.

**Comment by TerdyTheTerd** [comment]
What is the name of the other pack, maybe there is a specific mod causing issues that one pack has over the other, maybe old config files that never got deleted before version updates, I've seen some weird stuff happen with config files that got messed up with version updates.

**Comment by Time6628** [comment]
BeeHappy is the one with the issues. Revolution does not have the issues.

**Comment by Robotia** [comment]
@Time6628 Did you try the unofficial builds?

**Comment by iKaneki-Ken** [comment]
@Time6628 Again, it depends on how the modpack author programs the quest and the modpack overall. Regardless of this, this is a HQM issue. I can guarantee you of that. So I suggest you talk to the modpack author or the mod author about this.

**Comment by devryb** [comment]
Are you using uskyblock?

**Comment by Time6628** [comment]
Yes.

**Comment by devryb** [comment]
Set this to false in its config

  protection:
    # Whether or not, items dropped on the ground should be limited to party-members.
    item-drops: false

**Comment by Robotia** [comment]
(Non Thermos Issue)
