### ISSUE TITLE
Suggestion: Auto Flat Bedrock gen

### ISSUE THREAD

**Issue by djoveryde** [TCPR/Thermos#57]
Is it possible to add a feature to the world gen where it auto gen's bedrock as 1 layer?
Perhaps have a configurable option to use classic bedrock gen or new bedrock 1 layer gen.
Saves on requiring a mod to do this.

Looking through the paper spigot code. Seems they already implented this.
Appologies if this has already been implemented into KC

https://github.com/PaperSpigot/Paper-1.7/commit/11556b4717cf12edbef03ece167cbb8220c0b7ef

**Comment by Robotia** [comment]
@djoveryde 
This is available in CoFH Core, which most packs have:
nano `config/cofh/core/common.cfg`
`FlatBedrock=true`
`RetroactiveFlatBedrock=true` (only if you already have an active server and want to regen all of that bedrock to be flat)

**Comment by djoveryde** [comment]
COFHcore actually does crash some players. I had to remove it from my modpack due to that (no idea why it would).

**Comment by enterprise12nx** [comment]
Ive never known it to crash anyone, it all depends on how you put things together with other mods.

I own a populer modpack with over 96k downloads, my players experience no problems and according to forge it has 126 mods including cofh

**Comment by spannerman79** [comment]
> COFHcore actually does crash some players

Then you must be using a mod that uses an outdated rf api for that to happen.

**Comment by Robotia** [comment]
Did you update CoFH when you updated legends?

**Comment by Robotia** [comment]
Closed because this is already a feature of add-on mods.
