### ISSUE TITLE
Very strange dupe with chest and NULL items

### ISSUE THREAD

**Issue by linkinkov** [TCPR/Thermos#62]
https://www.youtube.com/watch?v=sIe5IojlP8g
Its was fixed?

**Comment by Robotia** [comment]
Please explain, I do not know Russian :(

**Comment by Robotia** [comment]
@linkinkov

**Comment by linkinkov** [comment]
I cant explain because cant reproduce, but players on server do it.
I will ask they about instruction and write here, soon as possible

**Comment by spannerman79** [comment]
I hit mute when i was playing that YouTube vid

I'd say its related to #54 

On a server setup in a LAN where the lag is <1ms (or ~0.5ms) that doesn't happen.

@linkinkov can you ask your users to do a pathping to your server? I've got this feeling that their path hits more then 200ms.

**Comment by Robotia** [comment]
@linkinkov Were you able to replicate it?

**Comment by Bogdan-G** [comment]
deception packet?

**Comment by Robotia** [comment]
@linkinkov

**Comment by iKaneki-Ken** [comment]
It's not a deception packet, basically this is like how you store something inside a chest or something right before a restart and the item is in your chest and your inventory.

This is them duplicating items by abusing their high ping. The do things too fast for the network to be able to keep up with ergo causing a duplication.

**Comment by Bogdan-G** [comment]
where checking for duplication in mod?

**Comment by Robotia** [comment]
@linkinkov

**Comment by linkinkov** [comment]
I cant reproduce, but dupers can, i do plugin for check null items, hope its was fixed.
Also i use modfix plugins, maybe strange issue with him.
If disable 1-9 click in chest and other inventory by:
event.getClick() == ClickType.NUMBER_KEY they cant dupe, but its ruined game mechanics

**Comment by Robotia** [comment]
Weird, going to try something to fix it.

**Comment by linkinkov** [comment]
Wow, thank you @Robotia, I will test it soon as possible.

**Comment by tyler2k15** [comment]
@linkinkov Did this resolve your issue?

**Comment by Robotia** [comment]
https://gitlab.prok.pw/KCauldron/KCauldron/commit/f3a73d8d68796229078017861f695fa8a76f61c4

**Comment by Robotia** [comment]
https://gitlab.prok.pw/KCauldron/KCauldron/commit/f6ba538998663720e77fe47978159c9b75e96ace

**Comment by linkinkov** [comment]
@Robotia you think that this commits do something strange?

**Comment by linkinkov** [comment]
@tyler2k15 I cant fully reproduce...

**Comment by Robotia** [comment]
I am thinking so @linkinkov

**Comment by Robotia** [comment]
Did you ever figure this out @linkinkov ?
