### ISSUE TITLE
ebean / mbean issues

### ISSUE THREAD

**Issue by TomberWolf** [TCPR/Thermos#620]
Server Log:
http://pastebin.com/umbErCn2

Explanation of issue: Thermos causes mbean / ebean issues

How to recreate this issue: Use plugins with ebean like Gringotts

Plugins Installed: Gringotts

Thermos Version: Thermos-1.7.10-1614-58

Forge Version: 1.7.10-1614-58

**Comment by Eufranio** [comment]
Thermos isn't receiving support anymore, and that's a known issue. I haven't found a fix yet.

**Comment by Bogdan-G** [comment]
^ and:
`net.milkbowl.vault.economy.plugins.Economy_Gringotts.hasAccount`
change versions plugins? vault/ebean

**Comment by TomberWolf** [comment]
I tried nearly every version / combination without any success :-/
