### ISSUE TITLE
no mob spawn night

### ISSUE THREAD

**Issue by croziors** [TCPR/Thermos#622]
You will receive NO SUPPORT if you do not follow the template below. (Vous ne receverez pas aucune aide si vous effacer ce modèle)

**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*

**FML Log(s): http://paste.feed-the-beast.com/view/2b21fdce

**Explanation of issue:** they are no mob spawn in the night 

**How to recreate this issue:**

**Modpack Name:** *(Only if public)*

**Mods Installed:**

**Plugins Installed:**

**Warmroast Report:** *(Optional)*

**Thermos Version:** last version Thermos-1.7.10-1614-server.jar

**Forge Version:**

**Comment by Bogdan-G** [comment]
`java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/PacketPlayOutWorldParticles`

**Comment by croziors** [comment]
for this issues what i need to do

**Comment by croziors** [comment]
it s cauldron error  i see on internet 
so i think they are issus on thermos

**Comment by croziors** [comment]
sorry i have send bad past
http://paste.feed-the-beast.com/view/4620b935
