### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by TheChomper** [TCPR/Thermos#625]
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
[cPHdnuEp.txt](https://github.com/CyberdyneCC/Thermos/files/805030/cPHdnuEp.txt)

**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
[hcqcgvy8.txt](https://github.com/CyberdyneCC/Thermos/files/805025/hcqcgvy8.txt)

**Explanation of issue:**
I don't know what happened which is sort of the reason for making this issue. All I know is the server crashed.

**How to recreate this issue:**
No idea.

**Mods Installed:**
[1.7.10] The Lord of the Rings Mod B31.3

**Plugins Installed:**
WorldEdit, WorldGuard, AdminEssentials, ControlTPA, FirstJoinPlus, SetSpawn

**Thermos Version:**
1.7.10-1614-58-server

**Comment by Eufranio** [comment]
I suggest you to not use Lord Of The Rings mod, it's causing your issues, and it will probably not be fixed in the Thermos side.
