### ISSUE TITLE
Serve crash while running the 1.7.10 Modpack

### ISSUE THREAD

**Issue by TheDecembrist** [TCPR/Thermos#627]
**Server Log:** *(http://paste.ubuntu.com/24119829/)*

**FML Log(s):** *(http://paste.ubuntu.com/24119838/)*

**Crash Report:** *(http://paste.ubuntu.com/24119790/)*

**Explanation of issue:**
After playing for several hours I stopped the server. On the next day i couldnt start the server anymore.

**How to recreate this issue:**
Really dont know.

**Modpack Name:** *The 1.7.10 Pack (Technic Launcher)*

**Mods Installed:**
https://www.technicpack.net/modpack/the-1710-pack.453902/mods

**Plugins Installed:**

**Forge Version:**
forge-1.7.10-10.13.4.1614-1.7.10-universal

**Comment by Eufranio** [comment]
You could remove the ChickenChunks mod, altrough I'm not sure that's the best solution.
