### ISSUE TITLE
World Edit Forge version - all World edit command are unknown

### ISSUE THREAD

**Issue by DeaSTL** [TCPR/Thermos#630]
**Server Log: https://gist.github.com/DeaSTL/a6ca1122dc695e945df102e99a50c5f0

**FML Log(s): https://gist.github.com/DeaSTL/01f8ddcd766dcb3c6ad5c2cae0f6e833

Explanation of issue: When I type "//" or any world edit command it shows up in red, "Unknown Command. Try /help for a list of commands"

**How to recreate this issue: Install worldedit-forge-mc1.7.10-6.0-beta-01 on a server running Thermos Version: 1.7.10-1614-58 

**Modpack Name: https://www.technicpack.net/modpack/xiaconpack.1002831

**Mods Installed: worldedit-forge-mc1.7.10-6.0-beta-01**

**Plugins Installed: None**

**Warmroast Report:** *(Optional)*

**Thermos Version: 1.7.10-1614-58 **

**Forge Version: 1614**

**Comment by Eufranio** [comment]
You need the WorldEdit plugin too, you need both Forge and Bukkit ones when using Thermos.

**Comment by DeaSTL** [comment]
Then I can't copy and paste blocks from the project red mod.

**Comment by Eufranio** [comment]
You can, install WorldEdit Bukkit.

**Comment by DeaSTL** [comment]
Do you have a link to a version for 1.7.10?

**Comment by Eufranio** [comment]
You can use latest: https://dev.bukkit.org/projects/worldedit/files

**Comment by DeaSTL** [comment]
How can I made it work with Forge Multipart mods?

**Comment by DeaSTL** [comment]
How can I use this with Forge micro blocks and project red
