### ISSUE TITLE
Player Skins Missing

### ISSUE THREAD

**Issue by megumann** [TCPR/Thermos#633]
You will receive NO SUPPORT if you do not follow the template below. (Vous ne receverez pas aucune aide si vous effacer ce modèle)

**Server Log:** *https://pastebin.com/bSXqQFrL*

**FML Log(s):** *https://pastebin.com/vj4nVAYM*

**Explanation of issue:** When playing on my multiplayer modded server, I can see my own skin but not my friend's. We've already tried relogging and restarting the client. EXAMPLE: 
![2017-05-06_18 03 35](https://cloud.githubusercontent.com/assets/20714689/25777073/8696e8e4-3286-11e7-8ebc-7bd3300dd7ca.png)

**How to recreate this issue:** No idea

**Modpack Name:** *ZGaming's Space Pack (found in the technic launcher, created by me)*

**Mods Installed:** 
Armorer's Workshop
BiblioCraft
BigReactors
Carpenter's Blocks
Chicken Chunks
Chisel2
Code Chicken Core
CoFH Core
Computer Craft
coroutil
Eureka
Flans Mod
Galacticraft Core
Galacticraft Planets
GalaxySpace (Galacticraft addon)
iChunUtil
ironchest
malisiscore
malisisdoors
Mantle
MatterOverdrive
Minecraft Comes Alive
MDK
Mekanism
Mekanism Generators
Mekanism Tools
Micdoodle Core
Minecraft Flight Simulator
MrCrayfishFurnitureMod
Not Enough Items
RadixCore
secretroomsmod
TConstruct
ThermalExpansion
ThermalFoundation
UpdateCheckerMod
Waila
weather2

**Plugins Installed:** N/A

**Thermos Version:** LATEST: 1614-58

**Forge Version:** Whatever version Thermos uses.

**Comment by sameer** [comment]
You are running in offline mode -- you need a plugin to load skins

**Comment by megumann** [comment]
@sameer I'll put it back into online mode; Would this be through the server config, or will it be in the spigot.yml? thermos.yml? What plugin do I need?

**Comment by Brend-Smits** [comment]
Server.properties 
Plugin like [SkinRestorer](https://www.spigotmc.org/resources/skinsrestorer.2124/)

**Comment by megumann** [comment]
@Rubbertjuh I believe I've already tried this plugin, but I'll try it again. I have it set to online mode. This plugin I thought was meant to allow players to change their skins from a command, not load them.

**Comment by Eufranio** [comment]
This plugin ALSO loads them. I use FastLogin tho.
