### ISSUE TITLE
Random Instant 100%CPU TIckrate freeze

### ISSUE THREAD

**Issue by Jacob345k** [TCPR/Thermos#635]
You will receive NO SUPPORT if you do not follow the template below. (Vous ne receverez pas aucune aide si vous effacer ce modèle)

**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
https://gist.github.com/Jacob345k/84af9aa3c0e3c792aa271ee9a488bbaf
**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
https://gist.github.com/Jacob345k/974a6199d43a3f02b6c588eff5acffe4
**Explanation of issue:**
After an amount of time, The CPU Usage goes all the way up and the server stops ticking.
**How to recreate this issue:**
Exist for a bit
**Modpack Name:** *(Only if public)*
The Coven Realm
**Mods Installed:**
http://i.imgur.com/L4gja9B.png
**Plugins Installed:**
http://i.imgur.com/anOG6Tz.png
**Warmroast Report:** *(Optional)*

**Thermos Version:**
1.7.10.1558.57
**Forge Version:**
1.7.10 - 10.13.4.1558

**Comment by Eufranio** [comment]
Install the Sampler mod: http://files.player.to/sampler-1.60.jar and it will generate an stall-report with what is causing the freeze.
