### ISSUE TITLE
Previous thread closed, Still needing Help

### ISSUE THREAD

**Issue by Jacob345k** [TCPR/Thermos#636]
You will receive NO SUPPORT if you do not follow the template below. (Vous ne receverez pas aucune aide si vous effacer ce modèle)
Previous issue that was closed: https://github.com/CyberdyneCC/Thermos/issues/635
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
Used Before
**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
Used Before
**Explanation of issue:**
I do not know how to read the stall reports
**How to recreate this issue:**
Have eyes
**Modpack Name:** *(Only if public)*
The Coven Realm
**Mods Installed:**
Used before
**Plugins Installed:**
Used Before
**Warmroast Report:** *(Optional)*
https://cdn.discordapp.com/attachments/270616929952071680/313874409205268481/stall-reports.7z
**Thermos Version:**
Those are the stall reports
**Forge Version:**
Please help

**Comment by TheUnderTaker11** [comment]
I am a mod developer for forge that is helping him out, and I have no idea what I'm looking at with the report it spits out.
After some research I found out each part of the report is a thread that was running at the time, but I still don't know how I should tell which thread is the problem.

**Comment by Eufranio** [comment]
The issue was closed because Thermos isn't developed anymore, and this one will probably be closed to. Please upload the stall-report in gist, hastebin or so, can't open 7z files rn :P
