### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Jacob345k** [TCPR/Thermos#637]
You will receive NO SUPPORT if you do not follow the template below. (Vous ne receverez pas aucune aide si vous effacer ce modèle)

**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
https://gist.github.com/Jacob345k/008ef6ff60e47fef2c98849d2dd2ca06
**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
https://gist.github.com/Jacob345k/307e203034f5789be88bfdb7d572f60b
**Explanation of issue:**
Server crashes a couple seconds after starting it with a bat only. This started happening after i changed my GRAPHICS CARD. Yes i know. No change to the bat files or config files.
**How to recreate this issue:**
Turn the server on
**Modpack Name:** *(Only if public)*
An Unamed Modpack
**Mods Installed:**
http://i.imgur.com/eN92WCH.png
**Plugins Installed:**
![image](https://cloud.githubusercontent.com/assets/25356889/26711138/fe9b3e10-4723-11e7-930c-46242178fd05.png)
**Warmroast Report:** *(Optional)*

**Thermos Version:**
Thermos-1.7.10-1558-57
**Forge Version:**
forge-1.7.10-10.13.4.1558-1.7.10-universal

**Comment by Eufranio** [comment]
Remove the tileentities.yml and entities.yml from your server folder
