### ISSUE TITLE
Thermos Revived

### ISSUE THREAD

**Issue by josephworks** [TCPR/Thermos#647]
It is 2019, and I am STILL using thermos. If you could revive thermos, that would be great! If you miss developing thermos, then check out https://gitlab.com/AtomMC/Atom It is basically thermos for 1.12.2. And IT WORKS!

**Comment by Tiagox42** [comment]
I am creating a server in thermos, and this is a great news I am very happy with the development round

**Comment by josephworks** [comment]
That's great!
Glad To hear!

Joseph R.
