### ISSUE TITLE
Thermos & Ars Magica 2

### ISSUE THREAD

**Issue by djoveryde** [TCPR/Thermos#65]
For some reason the Ars Magica 2 Dev refuses to support Cauldron of any version.
Basically players are unable to spawn the Winter guardian that you can usually spawn using magical casting. 
Not sure if theres a compatibility issue that just need tweaking or wether its a flat out no go area with AM2.

**Comment by Robotia** [comment]
Have you tested this with Forge?

**Comment by djoveryde** [comment]
I haven't personally but a player has and says it works fine in forge/single player.

**Comment by bookerthegeek** [comment]
I can verify that the latest build of AM2 works as expected in regards to this with forge.

**Comment by Robotia** [comment]
@djoveryde @bookerthegeek Share a video please?

**Comment by bookerthegeek** [comment]
Sure. It will be a bit till I get home.

**Comment by djoveryde** [comment]
Just waiting for the video to upload. From what I can see its actually just the winter guardian that fails to spawn. Basically you place 2 Blue Topaz Blocks on top of each other in the middle of a snowy biome with a block of ice on top. Spawn in 3 snow golems. Then place a gold inlay ring around the Topaz blocks. The golems should all die which they do and its meant to power the middle blocks, once all 3 have died those blocks then turns into the winter guardian. But it doesnt.

**Comment by bookerthegeek** [comment]
Sorry, I'm having issues with my environment. I'll ask some  policy to see if they can post a video.

**Comment by NEXUS2345** [comment]
Just a quick update for you guys, Mithion has announced that a new update to Ars Magica 2 is in the works by some community members, which should fix some bugs. Not sure when it will be released, but thought this information might be of use.

**Comment by TsumiHokiro** [comment]
@NEXUS2345 It has already been released.
@djoveryde I have been able to summon the winter guardian in version 20 of Thermos without problems...
Though I'm using version 008, not the dev version in my server.

**Comment by djoveryde** [comment]
Hmm I'll give it another go, maybe I missed something, on a side note it seems that the dispelling enchantment will completely crash a player when its added to any armor. Any attempts to tell mithion had the issue closed due to him not supporting cauldron

**Comment by TsumiHokiro** [comment]
@djoveryde I'm wondering. Does this only happens with the Winter Guardian or are there other Guardians which don't summon?

**Comment by Robotia** [comment]
Was this solved in the fixed version?

**Comment by djoveryde** [comment]
Winter Guardian now spawns in Version 45 :) :+1:
