### ISSUE TITLE
Low TPS

### ISSUE THREAD

**Issue by enterprise12nx** [TCPR/Thermos#66]
So my servers tps is at 1-3 with no players on, about 5 forced chunks loaded and like 300 chunks loaded total.

Not sure if its a cauldron bug, but i dont see what else it could be

**Comment by Robotia** [comment]
@enterprise12nx I can't do anything about this without some info :confused: . If you have Opis or TickProfiler installed, those could be the sources.

**Comment by enterprise12nx** [comment]
opis crashes with the latest cauldron now, i have tried both mobious and opis core fixes

**Comment by djoveryde** [comment]
Try removing those, basically test the server with no plugins first or at least minimal plugins (essentials). See if the problem still happens. If not then its one of the plugins likely Opis.

**Comment by enterprise12nx** [comment]
i removed opis already since it doesnt work, still persists.
it is not the plugins, its been happening ever since i moved over from normal cauldron on gitlab

**Comment by Robotia** [comment]
Very strange...I have never had this issue myself. By any chance are you using mystcraft?

**Comment by enterprise12nx** [comment]
nope, restarting fixes it, i wish i had more info but the logs show nothing.

we had 5 forced loaded chunks using /chunkloader from chickenchunks
and only 300 loaded chunks, no other dimensions loaded checked using
/cofh tps
/gc
/tps
/forge tps

the only thing i could think of is again the already decorating error crash which maybe is causing it occasionally. 
otherwise we have 18tps and it drastically drops in seconds until a restart

**Comment by Robotia** [comment]
I believe this is because of the forced chunk loading...it will require more investigation. Do you have a dedicated server or are you using a service?

**Comment by Bogdan-G** [comment]
a similar problem, but another set of mods, mc 3-10, despite the fact that I have reduced the tick-time, and removed most of the entities / objects / tiles.

**Comment by enterprise12nx** [comment]
Im using BisectHosting, its not one of their $100 dedicated plans, but i use it for a 24/7 public server.

**Comment by Robotia** [comment]
@Bogdan-G WarmRoast profile results?

**Comment by Robotia** [comment]
@Bogdan-G https://www.youtube.com/watch?v=c0ffjooX7Jw&feature=youtu.be sorry it is English

**Comment by iKaneki-Ken** [comment]
Just started a server up with 15 players, all the latest commits and my servers TPS is staying strong at 20. I'm thinking it may be a mod that is in the modpack you guys are using.

**Comment by Cracks777** [comment]
same here mine is running smooth also.

**Comment by Bogdan-G** [comment]
@Robotia no use WarmRoast, Opis. etc. Only `/tps /cofh tps /forge tps /cauldron chunks`

**Comment by Robotia** [comment]
@Bogdan-G What do you mean?

**Comment by Bogdan-G** [comment]
@Robotia in the sense of?
