### ISSUE TITLE
Error Compiling

### ISSUE THREAD

**Issue by TerdyTheTerd** [TCPR/Thermos#67]
So I checked out this repo to test the current commits, but when trying to build the jar package the build always fails. I ran with --stacktrace and --debug, --stacktrace was the only one that gave additional info imo. [Here](http://pastebin.com/PqYG2MDS) is the -stacktrace output, not sure if the code is incomplete, or if this is an error with the new name change that happened a few hours ago.

**Comment by Robotia** [comment]
You don't have command line git configured on your computer

**Comment by TerdyTheTerd** [comment]
Hmm, the gradle used for this repo must be different than other ones I've compiled before, I've compiled a few other mods and they worked fine so I assumed the error wasn't with my, sorry for wasting time :p

**Comment by Robotia** [comment]
Don't worry, you're fine!

**Comment by TerdyTheTerd** [comment]
@Robotia Is there something I'm missing? Turns out I had reinstalled recently and my path variables were wrong, but now when compiling I get a compile error with [this](http://pastebin.com/YnTWeieD) Not sure if there is a dependency that isn't being checked out, or maybe I'm just a nub and have some path set wrong, but as far as I can tell its telling me that the code is bork :/ Thanks for any help

**Comment by Robotia** [comment]
@TerdyTheTerd There is something wrong with the way you have it set up :confused: It is a very strange error. Instead of going to `Cauldron` it should default to `cauldron`.

**Comment by Robotia** [comment]
@TerdyTheTerd Works perfectly for me on both windows and linux. Are you doing `./gradlew clean setupCauldron jar`?

**Comment by TerdyTheTerd** [comment]
arg maybe thats the issue, I have been using <code>gradlew clean setupCauldron jar packageBundle</code> guessing its the package part thats killing me :/

**Comment by Robotia** [comment]
Hmm I don't know why that's there...I'll just remove it
