### ISSUE TITLE
Lastest update Crash with AM2 Block?

### ISSUE THREAD

**Issue by djoveryde** [TCPR/Thermos#68]
I am having issues with the server crashing randomly with a certain AM2 block.
I'm running the latest Thermos Version.

http://pastebin.com/dHR8n6U5

And another error with AM2 this time exception ticking world:

http://pastebin.com/pXM84xXe

**Comment by iKaneki-Ken** [comment]
Can you confirm this happens every time you attempt to use AM2's Iron Inlays?

**Comment by Robotia** [comment]
Interesting...going to see if I can fix this.

**Comment by Robotia** [comment]
Actually, this *might* be fixed by B21.

**Comment by djoveryde** [comment]
Is b21 stable enough for live servers? I can add it in and test it.

**Comment by Robotia** [comment]
B21 is not out yet because we are not sure if it stable yet, Kaneki was testing it for me early morning today.

**Comment by Robotia** [comment]
Fixed in 36
