### ISSUE TITLE
Exception getting block type in world - Chest

### ISSUE THREAD

**Issue by djoveryde** [TCPR/Thermos#70]
This error is coming from a Tekkit Legends server, issue seems to be a vanilla chest. Issue is the items tend to be random although I have seen most items coming from forestry I believe.

http://pastebin.com/enuKWVtY

**Comment by Robotia** [comment]
@djoveryde I think your world is corrupted or something about your settings is strange. I have never had this before on my Tekkit Legends server.

**Comment by Bogdan-G** [comment]
randomly error gg

**Comment by Robotia** [comment]
Not related to Thermos.
