### ISSUE TITLE
Tile Entities giving permanent RedStone Signal.

### ISSUE THREAD

**Issue by iKaneki-Ken** [TCPR/Thermos#73]
![redstone](https://cloud.githubusercontent.com/assets/7756987/12849380/f422e8bc-cbf9-11e5-8694-42b9ee245027.png)

Happens with any tile entity that can emit a Redstone Signal.

**Comment by Robotia** [comment]
@iKaneki-Ken Is it stuck this way?

**Comment by iKaneki-Ken** [comment]
Yep, we even remived the lever and each piece of redstone one by one. The Redstone signal did not stop until it was down to a 2x2 formation and a piece was broken from the 2x2 formation.

**Comment by iKaneki-Ken** [comment]
Fast with fixes as usual Robotia, thank you very much!

**Comment by iKaneki-Ken** [comment]
This issue is still persisting.
![redstone](https://cloud.githubusercontent.com/assets/7756987/12859314/e39f650c-cc2f-11e5-96e3-358a73592e57.png)
