### ISSUE TITLE
Critical bug Build 14

### ISSUE THREAD

**Issue by enterprise12nx** [TCPR/Thermos#74]
Updated to build 14 and all mekanism pipes, cables, etc are all disconnected, cannot be wrenched or broke.

![2016-02-05_15 52 39](https://cloud.githubusercontent.com/assets/3360014/12858904/d1f86fc4-cc20-11e5-8545-1b81f65763fd.png)

using /gc
![2016-02-05_15 59 24](https://cloud.githubusercontent.com/assets/3360014/12859024/9188a458-cc21-11e5-81e2-cc22a3987566.png)

**Comment by iKaneki-Ken** [comment]
Yeah, this just happened to me as well. World Edit doesn't work either.

**Comment by enterprise12nx** [comment]
gotta creative mode and break and replace it all

**Comment by iKaneki-Ken** [comment]
Yes, I noticed that as well. For now, backdate to B14.

**Comment by Robotia** [comment]
Working on it as we speak. Did B13 work fine?

**Comment by enterprise12nx** [comment]
B13 worked fine yes

**Comment by Robotia** [comment]
@iKaneki-Ken @enterprise12nx Should be fixed in B16.

**Comment by Robotia** [comment]
Fixed
