### ISSUE TITLE
Bukkit interaction doubling still persisting.

### ISSUE THREAD

**Issue by iKaneki-Ken** [TCPR/Thermos#75]
Did as was ask of in commit 34e591d554b7319e724ba44e019b61ddcda9bd5a and tested it. Event doubling is still persisting.

I wrote a script that activates on left click, instead of consuming 1 item on left click, it consumed 8.

**Comment by Robotia** [comment]
@iKaneki-Ken It should only do it once, are you certain?

**Comment by Robotia** [comment]
Turns out this is not related to anything I have done, problem is from BloodMC's time. Requires further investigation
