### ISSUE TITLE
Hang gliders no longer work in latest release

### ISSUE THREAD

**Issue by tyler2k15** [TCPR/Thermos#76]
I don't know if this is a coincidence or an issue. But I installed Revenge of The C Team, and hang gliders from openBlocks worked. But Then I needed to update to Thermod from kCauldron due to the tick sync crash, and now they don't work.

**Comment by Robotia** [comment]
@tyler2k15 What version of KCauldron were you originally using? Can you confirm that it works in the latest version?

**Comment by tyler2k15** [comment]
KCauldron version 1.7.10-1492.150 (MC: 1.7.10) <<-- That is the version that Hang Gliders were known to work on, but do not work on Thermos

**Comment by Robotia** [comment]
@tyler2k15 It may be the version of Forge...Thermos uses the latest 1614 Forge. We do not have any backports right now to 1492. Sorry!

**Comment by iKaneki-Ken** [comment]
@tyler2k15 Are you using BungeeCordÉ

**Comment by tyler2k15** [comment]
Yes, I am using Bungee

**Comment by tyler2k15** [comment]
@Robotia I know they worked on versions after that, I just don't know the version numbers because I rename my jar's to cauldron.jar or thermos.jar to make it easier (I use multicraft)

**Comment by iKaneki-Ken** [comment]
That's your issue. If you have a sub-domain, create a link that directly connects you to the modded server you're trying to use Hang Gliders on.

ex. server.exampledomain.net

**Comment by Robotia** [comment]
@tyler2k15 
Are you using the fixed version of Bungee from the TCPR fix repo?
Also, do /version for cauldron to see which KC version you were using. If it was 1492, that's a much older version of Forge than Thermos uses.

**Comment by tyler2k15** [comment]
Thanks @iKaneki-Ken 
I forgot about some items being stupid with bungee. 
I disconnected and reconnected with the direct address again and the solved it. Apologies for my derp moment.

Also, yes @Robotia we are using the Bungee fixes from the repo.
