### ISSUE TITLE
WorldEdit Wand bug [Thermos b14-b18]

### ISSUE THREAD

**Issue by linkinkov** [TCPR/Thermos#80]
Left click with wand tool does not work.
How reproduce:
1) //wand
2) Left click - nothing happen

But right click work :dancers: 
Anyway on last KCauldron worked properly.
i think its https://github.com/TCPR/Thermos/commit/34e591d554b7319e724ba44e019b61ddcda9bd5a do

**Comment by linkinkov** [comment]
On 13 stable all right

**Comment by Robotia** [comment]
Fixed in B19.

**Comment by Robotia** [comment]
Still happening, found the problem, will be fixed in B20.
