### ISSUE TITLE
Add more details on differences between Thermos and KCauldron?

### ISSUE THREAD

**Issue by ChrisLane** [TCPR/Thermos#81]
I'm a little uncertain on the differences between KCauldron and Thermos and would appreciate it if a wiki page could be setup or the README to be adjusted to make this a bit clearer.

**Comment by iKaneki-Ken** [comment]
From what I can tell, performance is undoubtedly better with Thermos. On startup with KCauldron, exact same conditions, literally cloned 2 different server directories, 8-12ms per tick. With Thermos, this went down to 2-6ms per tick on startup.

Tick stutters have become less noticable as well.

**Comment by ChrisLane** [comment]
And this is done how? Code optimisations or reductions in certain game aspects?

**Comment by iKaneki-Ken** [comment]
From what I can tell rewrites of certain sections of Thermos that speeds up processing time.

**Comment by ChrisLane** [comment]
Looks like more info has been added to the readme :+1:
