### ISSUE TITLE
Player Interact event [Build 19]

### ISSUE THREAD

**Issue by TerdyTheTerd** [TCPR/Thermos#82]
Just tested build 19 and I cannon interact with items unless looking at a block. Such as backpacks for opening them, changing modes on a weapon ect. The build I test was Build 14, so I am not sure at this point which commit changed this, I will update if I find the specific commit

**Comment by Robotia** [comment]
@TerdyTheTerd I think I know what it is....trying it now.

**Comment by TerdyTheTerd** [comment]
While its not a big deal, it would cause issues if you are flying and there are no blocks to click on (lets face it, on modded servers everyone and their brothers can fly)

**Comment by TerdyTheTerd** [comment]
Just tested it on Build 17 and it works, I'm guessing it has to do with Builds 18 "Fix interactions sometimes not working" although there isn't a linked commit for that.

**Comment by Robotia** [comment]
Hmm...trying to figure it out

**Comment by TerdyTheTerd** [comment]
Scratch that, looks like build 18 also works, must be build 19 somehow? I did notice in your new server bundle it includes both KCauldron 1492-155 and KCauldron 1517-168, why both?

**Comment by Robotia** [comment]
@TerdyTheTerd What do you mean?

**Comment by Robotia** [comment]
ccca867c9fd10cdf0ef3768746114bb063a601d8

**Comment by TerdyTheTerd** [comment]
![Thermos](http://i.imgur.com/DXabUVA.png)

In the libraries there are two versions of kcauldron included, was just curious as to why

**Comment by Robotia** [comment]
Oh might've been leftover from when I used to use KCauldron.

**Comment by Robotia** [comment]
Removed those just now

**Comment by Robotia** [comment]
Ok,  fixed this issue with a commit, will post soon.

**Comment by TerdyTheTerd** [comment]
I found another issue :( will make a new issue though for easier tracking
