### ISSUE TITLE
Unsure how but it happens. Force op hack?

### ISSUE THREAD

**Issue by djoveryde** [TCPR/Thermos#83]
On one of my servers it seems players are somehow force op'ing themselves. 
I can't seem to find how they are doing it. Wether they are forcing the server into thinking it's one of the op staff or not?

Any ideas? I know on YouTube there's a lot of how to hack 1.7.10 servers.

Hopefully you can find what causes this issue.

djoveryde

Edit: would adding something like a captcha for op'ing a player help? Like say I did /op robotia it would then give me 5 seconds to input a randomised code before it cancelled the op request. That way in theory a remote hack program would be denied the op request every time as it can't input the random key because it's only been sent to the person they are tricking the system to be.

**Comment by Yive** [comment]
Temporarily fix: Use a plugin to prevent the op command to be run ingame until further notice of if this will be a fix or not.

**Comment by Robotia** [comment]
Disable the in-game op command with world guard.

**Comment by iKaneki-Ken** [comment]
Or negate the permission node using your permissions plugin. The one thing a hacked client can't do is overrule the permissions system built into Minecraft.
