### ISSUE TITLE
Exception while updating neighbours

### ISSUE THREAD

**Issue by enterprise12nx** [TCPR/Thermos#88]
Getting a new crash with build 20
Never had it before
http://pastebin.com/wBWRpq42

this too, looks new
http://pastebin.com/cMXyh0FG

**Comment by Robotia** [comment]
It deals with out of synch errors, I have yet to work on this further, sorry!

**Comment by enterprise12nx** [comment]
np, i'll just wait for a fix

**Comment by TerdyTheTerd** [comment]
Hopefully that isn't a pvp server, all the player cords are in there still :p

**Comment by iKaneki-Ken** [comment]
Easy fix in the meantime, turn off block physics for now.

**Comment by enterprise12nx** [comment]
@iKaneki-Ken how do i do that?

**Comment by iKaneki-Ken** [comment]
Use WorldGuard. There's an option in there for it.

**Comment by Robotia** [comment]
Fixed by B21 (soon to be released).
