### ISSUE TITLE
[Crash] [Thermos 22] java.lang.NullPointerException: Ticking entity

### ISSUE THREAD

**Issue by Esctogrillo** [TCPR/Thermos#92]
It never happened before.
I don't know how to reproduce.
Crash-report: http://pastebin.com/RWu6vkS5

**Comment by Robotia** [comment]
Strange, it looks like it was caused by a custom mob. What were you using to create it?

**Comment by iKaneki-Ken** [comment]
InfernalMobs{1.6.2} [Infernal Mobs] (InfernalMobs-1.7.10.jar)

That's the culprit.

**Comment by Esctogrillo** [comment]
The name "§r§a||||||||||||||||§7||||" is created by HealthBar plugin.

**Comment by Esctogrillo** [comment]
Server crashes again (6 times this afternoon) with new crash report:
http://pastebin.com/NBvpU9Jf

**Comment by iKaneki-Ken** [comment]
As well, if you're open to suggestions, I recommend switching to BloodMC's version of Prism. It has support for modded inventories such as AE systems, Barrels and such.

**Comment by enterprise12nx** [comment]
@iKaneki-Ken
Can i have a link to that version of prism?
@Robotia
Seems the worldgen crash is fixed, greatly appreciated! Will be donating when im home tonight

**Comment by Robotia** [comment]
Thanks @enterprise12nx!

**Comment by spannerman79** [comment]
@enterprise12nx http://dhmc.us:8080/job/Prism-Cauldron/

**Comment by Robotia** [comment]
@spannerman79 I think they might've removed the cauldron one :confused: http://dhmc.us:8080/job/Prism/ works though.

**Comment by enterprise12nx** [comment]
@Robotia and this works with modded blocks?

**Comment by Robotia** [comment]
I do not know how Prism works, sorry D:
And you can donate [here](https://www.patreon.com/robotia?ty=h).

**Comment by enterprise12nx** [comment]
is there a way to donate only once? i cannot donate monthly :( @Robotia

**Comment by spannerman79** [comment]
@Robotia create a paypal.me url - what would be easiest ( https://www.paypal.me/ )

**Comment by enterprise12nx** [comment]
tried using that prism, get this error
http://pastebin.com/ykk7Sth1

**Comment by spannerman79** [comment]
@enterprise12nx because that one is for **Sponge**

@Robotia the Cauldron version is still there - just no builds made, source is https://github.com/prism/Prism-Bukkit/tree/master-cauldron

**Comment by enterprise12nx** [comment]
@spannerman79 i cannot code and stuff, so idk how to make a build  /=

**Comment by Robotia** [comment]
@spannerman79 Thanks!
@enterprise12nx http://paypal.me/robotia and we might be able to put up a jar under the TCPR repo for "fixes"

**Comment by enterprise12nx** [comment]
ok cool @Robotia 
Also @spannerman79 is there a working opis and mobious core version yet? the patched versions dont work

**Comment by iKaneki-Ken** [comment]
@enterprise12nx No, and there likely won't be for Thermos either as it's been hardcoded into Thermos to ignore Opis on load.

**Comment by spannerman79** [comment]
> Also @spannerman79 is there a working opis and mobious core version yet? the patched versions dont work

Only one that works for me is https://gitlab.prok.pw/KCauldron/KCauldron/wikis/patched-mods

**Comment by enterprise12nx** [comment]
@iKaneki-Ken oh ok, is there something else i can use? i use a server host as well (Bisect Hosting)

**Comment by iKaneki-Ken** [comment]
If you have access to edit command line arguments, you can force load TickProfiler.

**Comment by Robotia** [comment]
Wait....I removed the Opis hard-coding, it's only TickProfiler at the moment. Nallar gave the arg for force-loading TickProfiler under #52.

**Comment by iKaneki-Ken** [comment]
Apologies then, seems I'm not up to date with the commits.

**Comment by Robotia** [comment]
@Esctogrillo Is this issue persisting?

**Comment by Esctogrillo** [comment]
@Robotia Fortunately it did not happen more :)
