### ISSUE TITLE
14k entities?

### ISSUE THREAD

**Issue by enterprise12nx** [TCPR/Thermos#93]
soo using build 22 and our tps is at 1..went and checked

Overworld was the same till i did, /killall all

10.02 21:45:41 [Server] INFO CONSOLE issued server command: /gc 
10.02 21:45:41 [Server] INFO Uptime: 1 hour 23 minutes 23 seconds
10.02 21:45:41 [Server] INFO Current TPS = 2.17
10.02 21:45:41 [Server] INFO Maximum memory: 3,996 MB.
10.02 21:45:41 [Server] INFO Allocated memory: 3,996 MB.
10.02 21:45:41 [Server] INFO Free memory: 992 MB.
10.02 21:45:41 [Server] INFO World "world": 953 chunks, 182 entities, 12,396 tiles.
10.02 21:45:41 [Server] INFO World "DIM7": 0 chunks, 0 entities, 0 tiles.
10.02 21:45:41 [Server] INFO World "DIM-19": 0 chunks, 0 entities, 0 tiles.
10.02 21:45:41 [Server] INFO World "DIM-42": 0 chunks, 0 entities, 0 tiles.
10.02 21:45:41 [Server] INFO The End "DIM1": 0 chunks, 0 entities, 0 tiles.
**10.02 21:45:41 [Server] INFO Nether "DIM-1": 1 chunks, 459,970 entities, 0 tiles.**
10.02 21:45:41 [Server] INFO World "DIM-30": 0 chunks, 0 entities, 0 tiles.
10.02 21:45:41 [Server] INFO World "DIM-29": 0 chunks, 0 entities, 0 tiles.
10.02 21:45:41 [Server] INFO World "DIM-28": 16 chunks, 8 entities, 309 tiles.
10.02 21:45:41 [Server] INFO World "tardis/DIM11": 1 chunks, 0 entities, 4 tiles.
10.02 21:45:41 [Server] INFO World "tardis/DIM10": 1 chunks, 0 entities, 4 tiles.
10.02 21:45:41 [Server] INFO World "tardis/DIM9": 1 chunks, 0 entities, 0 tiles.
10.02 21:45:41 [Server] INFO World "tardis/DIM8": 1 chunks, 0 entities, 0 tiles.
10.02 21:45:41 [Server] INFO World "tardis/DIM6": 0 chunks, 0 entities, 0 tiles.
10.02 21:45:41 [Server] INFO World "tardis/DIM5": 0 chunks, 0 entities, 0 tiles.
10.02 21:45:41 [Server] INFO World "tardis/DIM4": 0 chunks, 0 entities, 0 tiles.
10.02 21:45:41 [Server] INFO World "tardis/DIM3": 0 chunks, 0 entities, 0 tiles.
10.02 21:45:41 [Server] INFO World "DIM_SPACESTATION2": 31 chunks, 0 entities, 6,328 tiles.

**Comment by Robotia** [comment]
@enterprise12nx This is likely items dropped on the ground, I had this issue once on my server where a player had created something that was spewing stacks upon stacks of iron bars all over the place, similar lag issues resulted. You will need to clear the items in that area.

**Comment by enterprise12nx** [comment]
@Robotia in both dimensions though?
i havent seen this problem before, i will look around and see

**Comment by Robotia** [comment]
12K tiles is normal, on my server I can get over 60K on a daily basis.
```
[21:36:47 INFO]: Uptime: 6 minutes 26 seconds
[21:36:47 INFO]: Current TPS = 19.88
[21:36:47 INFO]: Maximum memory: 12,288 MB.
[21:36:47 INFO]: Allocated memory: 11,604 MB.
[21:36:47 INFO]: Free memory: 7,803 MB.
[21:36:48 INFO]: World "world": 3,688 chunks, 1,607 entities, 22,341 tiles.
[21:36:48 INFO]: The End "DIM1": 0 chunks, 0 entities, 0 tiles.
[21:36:48 INFO]: Nether "DIM-1": 1 chunks, 0 entities, 0 tiles.
[21:36:48 INFO]: World "Hoth": 460 chunks, 20 entities, 4,363 tiles.
[21:36:48 INFO]: World "Spawn": 10 chunks, 41 entities, 227 tiles.

```

**Comment by enterprise12nx** [comment]
yes but mine are entities @Robotia

**Comment by enterprise12nx** [comment]
459,970 entities

**Comment by Robotia** [comment]
That is likely itemstacks on the ground, which can be cleared with a plugin like ClearLag

**Comment by iKaneki-Ken** [comment]
This isn't an issue being caused by Thermos. Run the command /killall drops and your issue be will fixed.
