### ISSUE TITLE
Player entity triggering death event when switching dimensions

### ISSUE THREAD

**Issue by NEXUS2345** [TCPR/Thermos#95]
It appears that when switching dimensions, the player entity is throwing a death event, but not actually dying. I am making this observation as whenever I change dimension, I get the Blood Magic 'Soul Fray' potion effect, which only applies after the player has died. The other observation is that my Angel Ring from Extra Utilities will stop working until I relog, something I had only previously noted after dying.

For the record, this is on @iKaneki-Ken 's server

**Comment by Robotia** [comment]
Related to the fix for #55

**Comment by TerdyTheTerd** [comment]
I would like to add an issue that I believe is related. On my server, when users teleport across dimension using commands, their ars magica levels/research resets to 0, however if I look inside their player.dat file their levels are the same as they were, even after leaving the server their levels remain the same as they were. Once relogging their levels are back to normal. Maybe the mod thinks the player is dead and defaults their levels to 0? If this issue doesn't seem related I will make a new issue with much greater detail/version numbers/links/videos.

**Comment by Robotia** [comment]
This is related to the player cloner, it is not passing player properties on when a player "re spawns" or teleports.

**Comment by Robotia** [comment]
@TerdyTheTerd Related to #98

**Comment by Robotia** [comment]
@iKaneki-Ken please try B23 to see if it's fixed.

**Comment by Robotia** [comment]
@TerdyTheTerd Are you using B23? If so, did it occur with B22?

**Comment by TerdyTheTerd** [comment]
Would love to test but I can't get the latest version to even launch, keeps crashing on a clean install, might be something I'm messing up

**Comment by Robotia** [comment]
@TerdyTheTerd Did you redownload the new libraries?

**Comment by TerdyTheTerd** [comment]
Ahh, didn't realize they had new libraries for the newer versions. Figured it was something on my part
