### ISSUE TITLE
Bukkit PlayerMoveEvent appears to be doubled up

### ISSUE THREAD

**Issue by DraksterAU** [TCPR/Thermos#97]
PlayerMoveEvent for bukkit appears to be doubled up, causing faction territory change messages to be duplicated.

This is also a bug in KCauldron.... I've looked at the source for Factions and they're doing it right... listening for the event and calling sendMessage to the player once per event.

**Comment by Robotia** [comment]
What build of Thermos are you using?

**Comment by Robotia** [comment]
And it is strange...I do not see the doubling of events on my factions server. They only receive the message of moving to another block of land once.

**Comment by DraksterAU** [comment]
22, your latest one

**Comment by Robotia** [comment]
So it happens for both Thermos and KCauldron?

**Comment by iKaneki-Ken** [comment]
Can confirm this. Happens on dimension change as well.

**Comment by DraksterAU** [comment]
Yep

**Comment by Bogdan-G** [comment]
It may increase the amount of data, so changes are such as this.

**Comment by DraksterAU** [comment]
What do you mean?

**Comment by Robotia** [comment]
@Bogdan-G I bumped the delta so there would be fewer move events.

**Comment by Bogdan-G** [comment]
@DraksterAU more mods, more traffics, more pool size packet.

**Comment by DraksterAU** [comment]
Hi @robotia

Can you respond when you've released this for me to test ? :)

**Comment by DraksterAU** [comment]
@Robotia B24 didn't fix this one :( sadface.

**Comment by Robotia** [comment]
How are you seeing the event doubled up?

**Comment by DraksterAU** [comment]
Factions/WorldGuard/Towny use the PlayerMoveEvent to detect chunk changes and therefore territory changes.
Every time territory changes in any of these plugins the messages are duplicated.

I've looked at the source for Factions and can see it only fires 1 change message per PlayerMoveEvent that results in a chunk+Territory change.

**Comment by Robotia** [comment]
@DraksterAU I believe this is an issue unique to you. On my Tekkit Legends server running B23 with Factions, I have never had this problem. 0.o

**Comment by DraksterAU** [comment]
@robotia on both the post where and with the KCauldron Devs I have people confirming they also have the issue.

I've also tried running JUST Factions with thermos and KCauldron and the issue persists.
 and JUST KCauldron with factions

**Comment by DraksterAU** [comment]
What version of thermos + factions are you running?

**Comment by Cracks777** [comment]
I believe this is an issue unique to you. On my Tekkit Legends server running B23?

**Comment by DraksterAU** [comment]
@Cracks777 your not making sense...

**Comment by Robotia** [comment]
Copy + paste master
Let me check on my server quick

**Comment by Cracks777** [comment]
running B23

**Comment by Cracks777** [comment]
lol he said he was running build 23

**Comment by DraksterAU** [comment]
@Cracks777 the more important half of that is his version of factions.

**Comment by Cracks777** [comment]
lol just truing to help.

**Comment by DraksterAU** [comment]
@Cracks777 PS I have tried B23 with @Robotia's factions build under fixes here on both a Linux and Windows machine with Java 8 and issue persists.

**Comment by Robotia** [comment]
Nevermind, you were right @DraksterAU somehow I missed it.

**Comment by DraksterAU** [comment]
Lol @Robotia no worries. Just fending off the others so the issue doesn't get closed prematurely lol

**Comment by DraksterAU** [comment]
Hi @Robotia I tested... doesn't fix :(

**Comment by Time6628** [comment]
Can confirm this issue still persists. Also, it appears the second message is sent a bit late. For example, if you /f claim auto: http://prntscr.com/adbcry, you can see it claims the chunk but then also tells you that you already have the chunk. There is a slight delay after the first message, not sure if that helps or not :smile_cat:

**Comment by DraksterAU** [comment]
@time6628 markehme and I have developed work arounds For  v2.8.5 of Factions.

Install the plugin here to resolve the issues;
https://github.com/MarkehMe/MassiveCoreForgeFixes

**Comment by Time6628** [comment]
@DraksterAU I have that plugin installed and the messages still appear. :cat:

**Comment by DraksterAU** [comment]
Try the jars in https://GitHub.com/StargateMC/server

It was done to my server before mark made the plugin.

Let me know if it still persists after that?

**Comment by DraksterAU** [comment]
@time6628

**Comment by Time6628** [comment]
I am using 2.8.7Beta.

**Comment by DraksterAU** [comment]
@time6628 I wouldn't use that with cauldron - and the fixes plugin is only tested with 2.8.6 and below.

2.8.7 is for 1.9

**Comment by Robotia** [comment]
Fixed in B47.
