### ISSUE TITLE
Conflict with Advanced Genetics v.1.5.9

### ISSUE THREAD

**Issue by tyler2k15** [TCPR/Thermos#98]
I hate to be the bearer of bad news, but I believe I have another Thermos bug (have tested both on the server and on single player)

Using the latest version of advanced genetics, the ``Swim in Lava`` genetic doesn't do what it's suppose to. (To allow you to swim in lava without taking damage, or any dire damage)

As you can probably tell, the gene doesn't protect you and you die.

**Comment by Robotia** [comment]
@tyler2k15 Have you tested this with a regular forge server? ProjectE's gem armor protects you from lava, so it must be something to do with player attributes.

**Comment by tyler2k15** [comment]
Note: Updating Thermos to https://github.com/TCPR/Thermos/releases/tag/24

**Comment by tyler2k15** [comment]
Issue persists in Build 24

**Comment by Robotia** [comment]
@tyler2k15 Ok, will look into it further.

**Comment by Robotia** [comment]
This requires further investigation. I decompiled the advanced genetics mod code and found that it should receive events properly. However, now the question is whether the Forge Event for lava damage is being called correctly.

**Comment by Robotia** [comment]
Code in ForgeHooks was incorrect - server was ignoring canceled forge damage events. Fixed now, closing.
